// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.staves
import com.omnifret.gplayer.core.*

/**
 * A Staff represents a single line within a StaffSystem.
 * It stores BarRenderer instances created from a given factory.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class RenderStaff
{
    private var _factory: com.omnifret.gplayer.rendering.BarRendererFactory
    
    private var _sharedLayoutData: com.omnifret.gplayer.collections.Map<String, Any?> = com.omnifret.gplayer.collections.Map<String, Any?>()
    
    public lateinit var staffTrackGroup: com.omnifret.gplayer.rendering.staves.StaffTrackGroup
    
    public lateinit var system: com.omnifret.gplayer.rendering.staves.StaffSystem
    
    public var barRenderers: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.BarRendererBase> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.BarRendererBase>(
    )
    
    
    
    public var x: Double = 0.0
    
    
    public var y: Double = 0.0
    
    
    public var height: Double = 0.0
    
    
    public var index: Double = 0.0
    
    
    public var staffIndex: Double = 0.0
    
    
    public var isVisible: Boolean = false
    
    
    private var _emptyBarCount: Double = 0.0
    
    public val isFirstInSystem: Boolean
    get(){
        return this.system.firstVisibleStaff == this
    }
    
    public var topEffectInfos: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
    )
    
    
    
    public var bottomEffectInfos: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
    )
    
    
    
    /**
     * This is the index of the track being rendered. This is not the index of the track within the model,
     * but the n-th track being rendered. It is the index of the  array defining
     * which tracks should be rendered.
     * For single-track rendering this will always be zero.
     */
    public var trackIndex: Double = 0.0
    
    
    public var modelStaff: com.omnifret.gplayer.model.Staff
    
    public val staffId: String
    get(){
        return this._factory.staffId
    }
    
    /**
     * This is the visual offset from top where the
     * Staff contents actually start. Used for grouping
     * using a accolade
     */
    public var staffTop: Double = 0.0
    
    
    public var topPadding: Double = 0.0
    
    
    public var bottomPadding: Double = 0.0
    
    
    /**
     * This is the visual offset from top where the
     * Staff contents actually ends. Used for grouping
     * using a accolade
     */
    public var staffBottom: Double = 0.0
    
    
    public val contentTop: Double
    get(){
        return this.y + this.staffTop + this.topPadding + this.topOverflow
    }
    
    public val contentBottom: Double
    get(){
        return this.y + this.topPadding + this.topOverflow + this.staffBottom
    }
    
    public constructor(system: com.omnifret.gplayer.rendering.staves.StaffSystem, trackIndex: Double, staff: com.omnifret.gplayer.model.Staff, factory: com.omnifret.gplayer.rendering.BarRendererFactory){
        this._factory = factory
        this.trackIndex = trackIndex
        this.modelStaff = staff
        this.system = system
        for (b in factory.effectBands)
        {
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(b.shouldCreate)) && !b.shouldCreate!!(staff)))
            {
                continue
            }
            when (b.mode)
            {
                com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, com.omnifret.gplayer.rendering.EffectBandMode.SharedTop -> 
                {
                    this.topEffectInfos.push(b)
                }
                com.omnifret.gplayer.rendering.EffectBandMode.OwnedBottom, com.omnifret.gplayer.rendering.EffectBandMode.SharedBottom -> 
                {
                    this.bottomEffectInfos.push(b)
                }
                else -> { }
            }
        }
        this._updateVisibility()
    }
    
    /**
     */
    public fun <T>getSharedLayoutData(key: String, def: T): T{
        if (this._sharedLayoutData.has(key))
        {
            return (this._sharedLayoutData.get(key) as T)
        }
        return def
    }
    
    /**
     */
    public fun <T>setSharedLayoutData(key: String, def: T): Unit{
        this._sharedLayoutData.set(key, def)
    }
    
    /**
     */
    public fun registerStaffTop(offset: Double): Unit{
        if (offset > this.staffTop)
        {
            this.staffTop = offset
        }
    }
    
    /**
     */
    public fun registerStaffBottom(offset: Double): Unit{
        if (offset > this.staffBottom)
        {
            this.staffBottom = offset
        }
    }
    
    /**
     */
    public fun addBarRenderer(renderer: com.omnifret.gplayer.rendering.BarRendererBase): Unit{
        renderer.staff = this
        renderer.index = this.barRenderers.length
        renderer.reLayout()
        this.barRenderers.push(renderer)
        this.system.layout.registerBarRenderer(this.staffId, renderer)
        if (renderer.bar.isEmpty || renderer.bar.isRestOnly)
        {
            this._emptyBarCount++
        }
        this._updateVisibility()
    }
    
    private fun _updateVisibility(): Unit{
        var stylesheet: com.omnifret.gplayer.model.RenderStylesheet = this.modelStaff.track.score.stylesheet
        var canHideEmptyStaves: Boolean = stylesheet.hideEmptyStaves && (stylesheet.hideEmptyStavesInFirstSystem || this.system.index > 0)
        if (canHideEmptyStaves)
        {
            this.isVisible = this._emptyBarCount < this.barRenderers.length
        }
        else 
        {
            this.isVisible = true
        }
    }
    
    /**
     */
    public fun addBar(bar: com.omnifret.gplayer.model.Bar, layoutingInfo: com.omnifret.gplayer.rendering.staves.BarLayoutingInfo, additionalMultiBarsRestBars: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Bar>?): Unit{
        var renderer: com.omnifret.gplayer.rendering.BarRendererBase = this._factory.create(this.system.layout.renderer, bar)
        renderer.topEffects.infos = this.topEffectInfos
        renderer.bottomEffects.infos = this.bottomEffectInfos
        renderer.additionalMultiRestBars = additionalMultiBarsRestBars
        renderer.staff = this
        renderer.index = this.barRenderers.length
        renderer.layoutingInfo = layoutingInfo
        renderer.doLayout()
        this.barRenderers.push(renderer)
        this.system.layout.registerBarRenderer(this.staffId, renderer)
        if (bar.isEmpty || bar.isRestOnly)
        {
            this._emptyBarCount++
        }
        this._updateVisibility()
    }
    
    public fun revertLastBar(): com.omnifret.gplayer.rendering.BarRendererBase{
        this.resetSharedLayoutData()
        var lastBar: com.omnifret.gplayer.rendering.BarRendererBase = this.barRenderers[(this.barRenderers.length - (1.0).toDouble()).toInt()]
        this.barRenderers.splice(this.barRenderers.length - (1.0).toDouble(), 1.0)
        this.topOverflow = 0.0
        this.bottomOverflow = 0.0
        for (r in this.barRenderers)
        {
            r.afterStaffBarReverted()
        }
        if (lastBar.bar.isEmpty || lastBar.bar.isRestOnly)
        {
            this._emptyBarCount--
        }
        this._updateVisibility()
        return lastBar
    }
    
    public fun resetSharedLayoutData(): Unit{
        this._sharedLayoutData.clear()
    }
    
    public var topOverflow: Double = 0.0
    
    
    /**
     */
    public fun registerOverflowTop(overflow: Double): Unit{
        if (overflow > this.topOverflow)
        {
            this.topOverflow = overflow
        }
    }
    
    public var bottomOverflow: Double = 0.0
    
    
    /**
     */
    public fun registerOverflowBottom(overflow: Double): Unit{
        if (overflow > this.bottomOverflow)
        {
            this.bottomOverflow = overflow
        }
    }
    
    /**
     * Performs an early calculation of the expected staff height for the size calculation in the
     * accolade (e.g. for braces). This typically happens after the first bar renderers were created
     * and we can do an early placement of the render staffs.
     */
    public fun calculateHeightForAccolade(): Unit{
        this._applyStaffPaddings()
        this.height = if(this.barRenderers.length > 0)  this.barRenderers[(0).toInt()].height else 0.0
        if (this.height > 0)
        {
            this.height += com.omnifret.gplayer.core.ecmaScript.Math.ceil(this.topPadding + this.topOverflow + this.bottomOverflow + this.bottomPadding)
        }
    }
    
    private fun _applyStaffPaddings(): Unit{
        var isFirst: Boolean = this.index == 0.0
        var isLast: Boolean = this.index == this.system.staves.length - (1.0).toDouble()
        var settings: com.omnifret.gplayer.DisplaySettings = this.system.layout.renderer.settings.display
        this.topPadding = if(isFirst)  settings.firstNotationStaffPaddingTop else settings.notationStaffPaddingTop
        this.bottomPadding = if(isLast)  settings.lastNotationStaffPaddingBottom else settings.notationStaffPaddingBottom
    }
    
    public fun finalizeStaff(): Unit{
        this._applyStaffPaddings()
        this.height = 0.0
        var needsSecondPass: Boolean = false
        var topOverflow: Double = this.topOverflow
        for (renderer in this.barRenderers)
        {
            renderer.registerMultiSystemSlurs(this.system.layout!!.slurRegistry.getAllContinuations(renderer))
            if (renderer.finalizeRenderer())
            {
                needsSecondPass = true
            }
            this.height = com.omnifret.gplayer.core.ecmaScript.Math.max(this.height, renderer.height)
        }
        if (needsSecondPass)
        {
            topOverflow = this.topOverflow
            for (renderer in this.barRenderers)
            {
                renderer.y = this.topPadding + topOverflow
            }
            for (renderer in this.barRenderers)
            {
                renderer.finalizeRenderer()
            }
        }
        if (this.height > 0)
        {
            this.height += this.topPadding + topOverflow + this.bottomOverflow + this.bottomPadding
        }
        this.height = com.omnifret.gplayer.core.ecmaScript.Math.ceil(this.height)
        this._updateVisibility()
    }
    
    /**
     */
    public fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas, startIndex: Double, count: Double): Unit{
        if (this.height == 0.0 || count == 0.0)
        {
            return
        }
        if (true) {
            var i: Double = startIndex
            var j: Double = com.omnifret.gplayer.core.ecmaScript.Math.min(startIndex + count, this.barRenderers.length)
            
            while(i < j){
                this.barRenderers[(i).toInt()].paint(cx + this.x, cy + this.y, canvas)
                i++
            }
        }
    }
    
}

