// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.effects
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class HarmonicsEffectInfo: com.omnifret.gplayer.rendering.effects.NoteEffectInfoBase
{
    private var _harmonicType: com.omnifret.gplayer.model.HarmonicType
    
    private var _beat: com.omnifret.gplayer.model.Beat? = null
    
    private var _effectId: String
    
    public override val effectId: String
    get(){
        return this._effectId
    }
    
    public override val notationElement: com.omnifret.gplayer.NotationElement
    get(){
        return com.omnifret.gplayer.NotationElement.EffectHarmonics
    }
    
    public constructor(harmonicType: com.omnifret.gplayer.model.HarmonicType)
        : super(){
        this._harmonicType = harmonicType
        when (harmonicType)
        {
            com.omnifret.gplayer.model.HarmonicType.None -> 
            {
                this._effectId = "harmonics-none"
            }
            com.omnifret.gplayer.model.HarmonicType.Natural -> 
            {
                this._effectId = "harmonics-natural"
            }
            com.omnifret.gplayer.model.HarmonicType.Artificial -> 
            {
                this._effectId = "harmonics-artificial"
            }
            com.omnifret.gplayer.model.HarmonicType.Pinch -> 
            {
                this._effectId = "harmonics-pinch"
            }
            com.omnifret.gplayer.model.HarmonicType.Tap -> 
            {
                this._effectId = "harmonics-tap"
            }
            com.omnifret.gplayer.model.HarmonicType.Semi -> 
            {
                this._effectId = "harmonics-semi"
            }
            com.omnifret.gplayer.model.HarmonicType.Feedback -> 
            {
                this._effectId = "harmonics-feedback"
            }
            else -> 
            {
                this._effectId = ""
            }
        }
    }
    
    /**
     */
    protected override fun shouldCreateGlyphForNote(note: com.omnifret.gplayer.model.Note): Boolean{
        if (!note.isHarmonic || note.harmonicType != this._harmonicType)
        {
            return false
        }
        if (note.beat != this._beat)
        {
            this._beat = note.beat
        }
        return true
    }
    
    public override val sizingMode: com.omnifret.gplayer.rendering.EffectBarGlyphSizing
    get(){
        return com.omnifret.gplayer.rendering.EffectBarGlyphSizing.GroupedOnBeat
    }
    
    /**
     * Creates a new effect glyph for the given beat.
     */
    public override fun createNewGlyph(_renderer: com.omnifret.gplayer.rendering.BarRendererBase, _beat: com.omnifret.gplayer.model.Beat): com.omnifret.gplayer.rendering.glyphs.EffectGlyph{
        return com.omnifret.gplayer.rendering.glyphs.LineRangedGlyph(com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo.harmonicToString(this._harmonicType), com.omnifret.gplayer.NotationElement.EffectHarmonics)
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun harmonicToString(type: com.omnifret.gplayer.model.HarmonicType): String{
            when (type)
            {
                com.omnifret.gplayer.model.HarmonicType.Natural -> 
                {
                    return "N.H."
                }
                com.omnifret.gplayer.model.HarmonicType.Artificial -> 
                {
                    return "A.H."
                }
                com.omnifret.gplayer.model.HarmonicType.Pinch -> 
                {
                    return "P.H."
                }
                com.omnifret.gplayer.model.HarmonicType.Tap -> 
                {
                    return "T.H."
                }
                com.omnifret.gplayer.model.HarmonicType.Semi -> 
                {
                    return "S.H."
                }
                com.omnifret.gplayer.model.HarmonicType.Feedback -> 
                {
                    return "Fdbk."
                }
                else -> { }
            }
            return ""
        }
        
    }
}

