// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.effects
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class NumberedBarKeySignatureEffectInfo: com.omnifret.gplayer.rendering.EffectInfo
{
    public override val notationElement: com.omnifret.gplayer.NotationElement
    get(){
        return com.omnifret.gplayer.NotationElement.EffectNumberedNotationKeySignature
    }
    
    public override val hideOnMultiTrack: Boolean
    get(){
        return false
    }
    
    public override val canShareBand: Boolean
    get(){
        return false
    }
    
    public override val sizingMode: com.omnifret.gplayer.rendering.EffectBarGlyphSizing
    get(){
        return com.omnifret.gplayer.rendering.EffectBarGlyphSizing.FullBar
    }
    
    /**
     * Checks whether the given beat has the appropriate effect set and
     * needs a glyph creation
     */
    public override fun shouldCreateGlyph(_settings: com.omnifret.gplayer.Settings, beat: com.omnifret.gplayer.model.Beat): Boolean{
        var bar: com.omnifret.gplayer.model.Bar = beat.voice.bar
        return (beat.index == 0.0 && beat.voice.index == 0.0 && (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(bar.previousBar)) || bar.keySignature != bar.previousBar!!.keySignature))
    }
    
    /**
     * Creates a new effect glyph for the given beat.
     */
    public override fun createNewGlyph(renderer: com.omnifret.gplayer.rendering.BarRendererBase, _beat: com.omnifret.gplayer.model.Beat): com.omnifret.gplayer.rendering.glyphs.EffectGlyph{
        return com.omnifret.gplayer.rendering.glyphs.NumberedKeySignatureGlyph(0.0, 0.0, renderer.bar.keySignature, renderer.bar.keySignatureType)
    }
    
    /**
     * Checks whether an effect glyph can be expanded to a particular beat.
     */
    public override fun canExpand(_from: com.omnifret.gplayer.model.Beat, _to: com.omnifret.gplayer.model.Beat): Boolean{
        return false
    }
    
    public constructor()
    : super()
}

