// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.synth
import com.omnifret.gplayer.core.*

/**
 * A  implementation wrapping and underling other 
 * allowing dynamic changing of the underlying instance without loosing aspects like the
 * main playback information and event listeners.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class GPlayerSynthWrapper: com.omnifret.gplayer.synth.IGPlayerSynth
{
    private var _masterVolume: Double = 1.0
    
    private var _metronomeVolume: Double = 0.0
    
    private var _countInVolume: Double = 0.0
    
    private var _playbackSpeed: Double = 1.0
    
    private var _isLooping: Boolean = false
    
    private var _midiEventsPlayedFilter: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.midi.MidiEventType> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.midi.MidiEventType>(
    )
    
    
    private var _instance: com.omnifret.gplayer.synth.IGPlayerSynth? = null
    
    private var _instanceEventUnregister: com.omnifret.gplayer.collections.List<(() -> Unit)>? = null
    
    public var midiTickShift: Double = 0.0
    
    
    public constructor(){
        this.ready = com.omnifret.gplayer.EventEmitter(fun(): Boolean{
            return this.isReady
        }
        )
        this.readyForPlayback = com.omnifret.gplayer.EventEmitter(fun(): Boolean{
            return this.isReadyForPlayback
        }
        )
        this.midiLoaded = com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>(fun(): com.omnifret.gplayer.synth.PositionChangedEventArgs?{
            return this._instance?.loadedMidiInfo 
        }
        )
        this.stateChanged = com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PlayerStateChangedEventArgs>(fun(): com.omnifret.gplayer.synth.PlayerStateChangedEventArgs{
            return com.omnifret.gplayer.synth.PlayerStateChangedEventArgs(this.state, false)
        }
        )
        this.positionChanged = com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>(fun(): com.omnifret.gplayer.synth.PositionChangedEventArgs{
            return this.currentPosition
        }
        )
        this.playbackRangeChanged = com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs>(fun(): com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs?{
            var range: com.omnifret.gplayer.synth.PlaybackRange? = this.playbackRange
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(range)))
            {
                return com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs(range!!)
            }
            return null
        }
        )
    }
    
    public var instance: com.omnifret.gplayer.synth.IGPlayerSynth?
    get(){
        return this._instance
    }
    set(value){
        this._instance = value
        var unregister: com.omnifret.gplayer.collections.List<(() -> Unit)>? = this._instanceEventUnregister
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(unregister)))
        {
            for (e in unregister!!)
            {
                e()
            }
        }
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(value)))
        {
            var newUnregister: com.omnifret.gplayer.collections.List<(() -> Unit)> = com.omnifret.gplayer.collections.List<(() -> Unit)>(
            )
            
            newUnregister.push(value!!.ready.on({
                ((this.ready as com.omnifret.gplayer.EventEmitter)).trigger()
            }
            ))
            newUnregister.push(value!!.readyForPlayback.on({
                ((this.readyForPlayback as com.omnifret.gplayer.EventEmitter)).trigger()
            }
            ))
            newUnregister.push(value!!.finished.on({
                ((this.finished as com.omnifret.gplayer.EventEmitter)).trigger()
            }
            ))
            newUnregister.push(value!!.soundFontLoaded.on({
                ((this.soundFontLoaded as com.omnifret.gplayer.EventEmitter)).trigger()
            }
            ))
            newUnregister.push(value!!.soundFontLoadFailed.on(fun(e: kotlin.Throwable): Unit{
                return ((this.soundFontLoadFailed as com.omnifret.gplayer.EventEmitterOfT<kotlin.Throwable>)).trigger(e)
            }
            ))
            newUnregister.push(value!!.midiLoaded.on(fun(e: com.omnifret.gplayer.synth.PositionChangedEventArgs): Unit{
                ((this.midiLoaded as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>)).trigger(this._shiftPositionChangedEventArgsToApi(e)!!)
            }
            ))
            newUnregister.push(value!!.midiLoadFailed.on(fun(e: kotlin.Throwable): Unit{
                return ((this.midiLoadFailed as com.omnifret.gplayer.EventEmitterOfT<kotlin.Throwable>)).trigger(e)
            }
            ))
            newUnregister.push(value!!.stateChanged.on(fun(e: com.omnifret.gplayer.synth.PlayerStateChangedEventArgs): Unit{
                return ((this.stateChanged as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PlayerStateChangedEventArgs>)).trigger(e)
            }
            ))
            newUnregister.push(value!!.positionChanged.on(fun(e: com.omnifret.gplayer.synth.PositionChangedEventArgs): Unit{
                ((this.positionChanged as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>)).trigger(this._shiftPositionChangedEventArgsToApi(e)!!)
            }
            ))
            newUnregister.push(value!!.midiEventsPlayed.on(fun(e: com.omnifret.gplayer.synth.MidiEventsPlayedEventArgs): Unit{
                return ((this.midiEventsPlayed as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.MidiEventsPlayedEventArgs>)).trigger(e)
            }
            ))
            newUnregister.push(value!!.playbackRangeChanged.on(fun(e: com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs): Unit{
                return ((this.playbackRangeChanged as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs>)).trigger(this._shiftPlaybackRangeChangedEventArgsToApi(e))
            }
            ))
            this._instanceEventUnregister = ((newUnregister as com.omnifret.gplayer.collections.List<(() -> Unit)>))
            if (this.isReady)
            {
                value!!.masterVolume = this._masterVolume
                value!!.metronomeVolume = this._metronomeVolume
                value!!.countInVolume = this._countInVolume
                value!!.playbackSpeed = this._playbackSpeed
                value!!.isLooping = this._isLooping
                value!!.midiEventsPlayedFilter = this._midiEventsPlayedFilter
                ((this.ready as com.omnifret.gplayer.EventEmitter)).trigger()
            }
            else 
            {
                newUnregister.push(value!!.ready.on(fun(): Unit{
                    value!!.masterVolume = this._masterVolume
                    value!!.metronomeVolume = this._metronomeVolume
                    value!!.countInVolume = this._countInVolume
                    value!!.playbackSpeed = this._playbackSpeed
                    value!!.isLooping = this._isLooping
                    value!!.midiEventsPlayedFilter = this._midiEventsPlayedFilter
                }
                ))
            }
        }
        else 
        {
            this._instanceEventUnregister = null
        }
    }
    
    public override val output: com.omnifret.gplayer.synth.ISynthOutput
    get(){
        return this._instance!!.output
    }
    
    public override val isReady: Boolean
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._instance!!.isReady else false
    }
    
    public override val isReadyForPlayback: Boolean
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._instance!!.isReadyForPlayback else false
    }
    
    public override val state: com.omnifret.gplayer.synth.PlayerState
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._instance!!.state else com.omnifret.gplayer.synth.PlayerState.Paused
    }
    
    public override var logLevel: com.omnifret.gplayer.LogLevel
    get(){
        return com.omnifret.gplayer.Logger.logLevel
    }
    set(value){
        com.omnifret.gplayer.Logger.logLevel = value
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.logLevel = value
        }
    }
    
    public override var masterVolume: Double
    get(){
        return this._masterVolume
    }
    set(value){
        var paramvalue = value
        paramvalue = com.omnifret.gplayer.core.ecmaScript.Math.max(paramvalue, com.omnifret.gplayer.synth.SynthConstants.MinVolume)
        this._masterVolume = paramvalue
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.masterVolume = paramvalue
        }
    }
    
    public override var metronomeVolume: Double
    get(){
        return this._metronomeVolume
    }
    set(value){
        var paramvalue = value
        paramvalue = com.omnifret.gplayer.core.ecmaScript.Math.max(paramvalue, com.omnifret.gplayer.synth.SynthConstants.MinVolume)
        this._metronomeVolume = paramvalue
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.metronomeVolume = paramvalue
        }
    }
    
    public override var playbackSpeed: Double
    get(){
        return this._playbackSpeed
    }
    set(value){
        this._playbackSpeed = value
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.playbackSpeed = value
        }
    }
    
    public override val loadedMidiInfo: com.omnifret.gplayer.synth.PositionChangedEventArgs?
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._shiftPositionChangedEventArgsToApi(this._instance!!.loadedMidiInfo) else null
    }
    
    public override val currentPosition: com.omnifret.gplayer.synth.PositionChangedEventArgs
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._shiftPositionChangedEventArgsToApi(this._instance!!.currentPosition)!! else com.omnifret.gplayer.synth.PositionChangedEventArgs(0.0, 
        0.0, 
        0.0, 
        0.0, 
        false, 
        120.0, 
        120.0)
    }
    
    public override var tickPosition: Double
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._shiftTickToApi(this._instance!!.tickPosition) else 0.0
    }
    set(value){
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.tickPosition = this._shiftTickToPlayer(value)
        }
    }
    
    public override var timePosition: Double
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._instance!!.timePosition else 0.0
    }
    set(value){
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.timePosition = value
        }
    }
    
    public override var playbackRange: com.omnifret.gplayer.synth.PlaybackRange?
    get(){
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._shiftPlaybackRangeToApi(this._instance!!.playbackRange) else null
    }
    set(value){
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.playbackRange = this._shiftPlaybackRangeToPlayer(value)
        }
    }
    
    public override var isLooping: Boolean
    get(){
        return this._isLooping
    }
    set(value){
        this._isLooping = value
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.isLooping = value
        }
    }
    
    public override var countInVolume: Double
    get(){
        return this._countInVolume
    }
    set(value){
        this._countInVolume = value
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.countInVolume = value
        }
    }
    
    public override var midiEventsPlayedFilter: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.midi.MidiEventType>
    get(){
        return this._midiEventsPlayedFilter
    }
    set(value){
        this._midiEventsPlayedFilter = value
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.midiEventsPlayedFilter = value
        }
    }
    
    /**
     * Destroys the synthesizer and all related components
     */
    public override fun destroy(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.destroy()
            this._instance = null
        }
    }
    
    /**
     * Starts the playback if possible
     */
    public override fun play(): Boolean{
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))  this._instance!!.play() else false
    }
    
    /**
     * Pauses the playback if was running
     */
    public override fun pause(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.pause()
        }
    }
    
    /**
     * Starts the playback if possible, pauses the playback if was running
     */
    public override fun playPause(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.playPause()
        }
    }
    
    /**
     * Stopps the playback
     */
    public override fun stop(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.stop()
        }
    }
    
    /**
     * Stops any ongoing playback and plays the given midi file instead.
     */
    public override fun playOneTimeMidiFile(midi: com.omnifret.gplayer.midi.MidiFile): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.playOneTimeMidiFile(midi)
        }
    }
    
    /**
     * Loads a soundfont from the given data
     */
    public override fun loadSoundFont(`data`: com.omnifret.gplayer.core.ecmaScript.Uint8Array, append: Boolean): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.loadSoundFont(`data`, append)
        }
    }
    
    /**
     * Resets all loaded soundfonts as if they were not loaded.
     */
    public override fun resetSoundFonts(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.resetSoundFonts()
        }
    }
    
    /**
     * Loads the given midi file structure.
     */
    public override fun loadMidiFile(midi: com.omnifret.gplayer.midi.MidiFile): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.loadMidiFile(midi)
        }
    }
    
    /**
     * Loads the synchronization information from the given score (used for backing tracks and external media).
     */
    public override fun loadBackingTrack(score: com.omnifret.gplayer.model.Score): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.loadBackingTrack(score)
        }
    }
    
    /**
     * Updates the points used to synchronize the backing track with the synthesized audio for correct cursor placement.
     */
    public override fun updateSyncPoints(syncPoints: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.synth.BackingTrackSyncPoint>): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.updateSyncPoints(syncPoints)
        }
    }
    
    /**
     * Applies the given transposition pitches to be used during playback.
     */
    public override fun applyTranspositionPitches(transpositionPitches: com.omnifret.gplayer.collections.DoubleDoubleMap): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.applyTranspositionPitches(transpositionPitches)
        }
    }
    
    /**
     * Sets the transposition pitch of a given channel. This pitch is additionally applied beside the
     * ones applied already via .
     */
    public override fun setChannelTranspositionPitch(channel: Double, semitones: Double): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.setChannelTranspositionPitch(channel, semitones)
        }
    }
    
    /**
     * Sets the mute state of a channel.
     */
    public override fun setChannelMute(channel: Double, mute: Boolean): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.setChannelMute(channel, mute)
        }
    }
    
    /**
     * Resets the mute/solo state of all channels
     */
    public override fun resetChannelStates(): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.resetChannelStates()
        }
    }
    
    /**
     * Gets the solo state of a channel.
     */
    public override fun setChannelSolo(channel: Double, solo: Boolean): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.setChannelSolo(channel, solo)
        }
    }
    
    /**
     * Gets or sets the current and initial volume of the given channel.
     */
    public override fun setChannelVolume(channel: Double, volume: Double): Unit{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._instance)))
        {
            this._instance!!.setChannelVolume(channel, volume)
        }
    }
    
    /**
     * This event is fired when the player is ready to be interacted with.
     */
    public override var ready: com.omnifret.gplayer.IEventEmitter
    
    /**
     * This event is fired when all required data for playback is loaded and ready.
     */
    public override var readyForPlayback: com.omnifret.gplayer.IEventEmitter
    
    /**
     * This event is fired when the playback of the whole song finished.
     */
    public override var finished: com.omnifret.gplayer.IEventEmitter = com.omnifret.gplayer.EventEmitter()
    
    
    /**
     * This event is fired when the SoundFont needed for playback was loaded.
     */
    public override var soundFontLoaded: com.omnifret.gplayer.IEventEmitter = com.omnifret.gplayer.EventEmitter()
    
    
    /**
     * This event is fired when the loading of the SoundFont failed.
     */
    public override var soundFontLoadFailed: com.omnifret.gplayer.IEventEmitterOfT<kotlin.Throwable> = com.omnifret.gplayer.EventEmitterOfT<kotlin.Throwable>()
    
    
    /**
     * This event is fired when the Midi file needed for playback was loaded.
     */
    public override var midiLoaded: com.omnifret.gplayer.IEventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>
    
    /**
     * This event is fired when the loading of the Midi file failed.
     */
    public override var midiLoadFailed: com.omnifret.gplayer.IEventEmitterOfT<kotlin.Throwable> = com.omnifret.gplayer.EventEmitterOfT<kotlin.Throwable>()
    
    
    /**
     * This event is fired when the playback state changed.
     */
    public override var stateChanged: com.omnifret.gplayer.IEventEmitterOfT<com.omnifret.gplayer.synth.PlayerStateChangedEventArgs>
    
    /**
     * This event is fired when the current playback position of/ the song changed.
     */
    public override var positionChanged: com.omnifret.gplayer.IEventEmitterOfT<com.omnifret.gplayer.synth.PositionChangedEventArgs>
    
    /**
     * The event is fired when certain midi events were sent to the audio output device for playback.
     */
    public override var midiEventsPlayed: com.omnifret.gplayer.IEventEmitterOfT<com.omnifret.gplayer.synth.MidiEventsPlayedEventArgs> = com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.synth.MidiEventsPlayedEventArgs>()
    
    
    /**
     * The event is fired when the playback range within the player was updated.
     */
    public override var playbackRangeChanged: com.omnifret.gplayer.IEventEmitterOfT<com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs>
    
    /**
     */
    private fun _shiftPlaybackRangeChangedEventArgsToApi(e: com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs): com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs{
        if (e.playbackRange == null)
        {
            return e
        }
        var tickShift: Double = this.midiTickShift
        if (tickShift > 0)
        {
            return com.omnifret.gplayer.synth.PlaybackRangeChangedEventArgs(this._shiftPlaybackRangeToApi(e.playbackRange!!))
        }
        else 
        {
            return e
        }
    }
    
    /**
     */
    private fun _shiftPlaybackRangeToApi(e: com.omnifret.gplayer.synth.PlaybackRange?): com.omnifret.gplayer.synth.PlaybackRange?{
        if (e == null)
        {
            return e
        }
        var tickShift: Double = this.midiTickShift
        if (tickShift > 0)
        {
            var range: com.omnifret.gplayer.synth.PlaybackRange = com.omnifret.gplayer.synth.PlaybackRange()
            range.startTick = e!!.startTick - tickShift
            range.endTick = e!!.endTick - tickShift
            return range
        }
        else 
        {
            return e!!
        }
    }
    
    /**
     */
    private fun _shiftPlaybackRangeToPlayer(e: com.omnifret.gplayer.synth.PlaybackRange?): com.omnifret.gplayer.synth.PlaybackRange?{
        if (e == null)
        {
            return e
        }
        var tickShift: Double = this.midiTickShift
        if (tickShift > 0)
        {
            var range: com.omnifret.gplayer.synth.PlaybackRange = com.omnifret.gplayer.synth.PlaybackRange()
            range.startTick = e!!.startTick + tickShift
            range.endTick = e!!.endTick + tickShift
            return range
        }
        else 
        {
            return e!!
        }
    }
    
    /**
     */
    private fun _shiftPositionChangedEventArgsToApi(e: com.omnifret.gplayer.synth.PositionChangedEventArgs?): com.omnifret.gplayer.synth.PositionChangedEventArgs?{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(e)))
        {
            return e
        }
        var tickShift: Double = this.midiTickShift
        return if(tickShift > 0)  com.omnifret.gplayer.synth.PositionChangedEventArgs(e!!.currentTime, 
        e!!.endTime, 
        e!!.currentTick - tickShift, 
        e!!.endTick - tickShift, 
        e!!.isSeek, 
        e!!.originalTempo, 
        e!!.modifiedTempo) else e!!
    }
    
    /**
     */
    private fun _shiftTickToApi(tickPosition: Double): Double{
        return tickPosition - this.midiTickShift
    }
    
    /**
     */
    private fun _shiftTickToPlayer(tickPosition: Double): Double{
        return tickPosition + this.midiTickShift
    }
    
}

