// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.synth
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class SynthConstants
{
    companion object{
        @kotlin.jvm.JvmStatic
        public val DefaultChannelCount: Double = 16.0 + 1.0
        
        @kotlin.jvm.JvmStatic
        public val MetronomeKey: Double = 33.0
        
        @kotlin.jvm.JvmStatic
        public val AudioChannels: Double = 2.0
        
        @kotlin.jvm.JvmStatic
        public val MinVolume: Double = 0.0
        
        @kotlin.jvm.JvmStatic
        public val MinProgram: Double = 0.0
        
        @kotlin.jvm.JvmStatic
        public val MaxProgram: Double = 127.0
        
        @kotlin.jvm.JvmStatic
        public val MinPlaybackSpeed: Double = 0.125
        
        @kotlin.jvm.JvmStatic
        public val MaxPlaybackSpeed: Double = 8.0
        
        @kotlin.jvm.JvmStatic
        public val PercussionChannel: Double = 9.0
        
        @kotlin.jvm.JvmStatic
        public val PercussionBank: Double = 128.0
        
        /**
         * The Midi Pitch bend message is a 15-bit value
         */
        @kotlin.jvm.JvmStatic
        public val MaxPitchWheel: Double = 16384.0
        
        /**
         * The Midi 2.0 Pitch bend message is a 32-bit value
         */
        @kotlin.jvm.JvmStatic
        public val MaxPitchWheel20: Double = 4294967296.0
        
        /**
         * The pitch wheel value for no pitch change at all.
         */
        @kotlin.jvm.JvmStatic
        public var DefaultPitchWheel: Double = com.omnifret.gplayer.synth.SynthConstants.MaxPitchWheel / (2.0).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public val MicroBufferCount: Double = 32.0
        
        @kotlin.jvm.JvmStatic
        public val MicroBufferSize: Double = 64.0
        
        /**
         * approximately -60 dB, which is inaudible to humans
         */
        @kotlin.jvm.JvmStatic
        public val AudibleLevelThreshold: Double = 0.001
        
    }
    public constructor()
}

