// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.midi
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class MidiUtils
{
    companion object{
        @kotlin.jvm.JvmStatic
        public val QuarterTime: Double = 960.0
        
        @kotlin.jvm.JvmStatic
        private val _minVelocity: Double = 15.0
        
        @kotlin.jvm.JvmStatic
        public val VelocityIncrement: Double = 16.0
        
        /**
         * Converts the given midi tick duration into milliseconds.
         * @param ticks The duration in midi ticks
         * @param tempo The current tempo in BPM.
         */
        @kotlin.jvm.JvmStatic
        public fun ticksToMillis(ticks: Double, tempo: Double): Double{
            return (((ticks * ((60000.0).toDouble() / (tempo * com.omnifret.gplayer.midi.MidiUtils.QuarterTime)))).toInt() or 0).toDouble()
        }
        
        /**
         * Converts the given midi tick duration into milliseconds.
         * @param millis The duration in milliseconds
         * @param tempo The current tempo in BPM.
         */
        @kotlin.jvm.JvmStatic
        public fun millisToTicks(millis: Double, tempo: Double): Double{
            return (((millis / ((60000.0).toDouble() / (tempo * com.omnifret.gplayer.midi.MidiUtils.QuarterTime)))).toInt() or 0).toDouble()
        }
        
        /**
         * Converts a duration value to its ticks equivalent.
         */
        @kotlin.jvm.JvmStatic
        public fun toTicks(duration: com.omnifret.gplayer.model.Duration): Double{
            return com.omnifret.gplayer.midi.MidiUtils.valueToTicks((duration.toDouble()))
        }
        
        /**
         * Converts a numerical value to its ticks equivalent.
         * @param duration the numerical proportion to convert. (i.E. timesignature denominator, note duration,...)
         */
        @kotlin.jvm.JvmStatic
        public fun valueToTicks(duration: Double): Double{
            var denomninator: Double = duration
            if (denomninator < 0)
            {
                denomninator = (1.0).toDouble() / -denomninator
            }
            return (((com.omnifret.gplayer.midi.MidiUtils.QuarterTime * ((4.0).toDouble() / denomninator))).toInt() or 0).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun applyDot(ticks: Double, doubleDotted: Boolean): Double{
            if (doubleDotted)
            {
                return ticks + (((ticks / (4.0).toDouble())).toInt() or 0) * (3.0).toDouble()
            }
            return ticks + (((ticks / (2.0).toDouble())).toInt() or 0)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun applyTuplet(ticks: Double, numerator: Double, denominator: Double): Double{
            return ((((ticks * denominator) / numerator)).toInt() or 0).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun removeTuplet(ticks: Double, numerator: Double, denominator: Double): Double{
            return ((((ticks * numerator) / denominator)).toInt() or 0).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun dynamicToVelocity(dynamicValue: com.omnifret.gplayer.model.DynamicValue, adjustment: Double = 0.0): Double{
            var velocity: Double = 1.0
            when (dynamicValue)
            {
                com.omnifret.gplayer.model.DynamicValue.PPP -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (0.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.PP -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (1.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.P -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (2.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.MP -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (3.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.MF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (4.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.F -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (5.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.FF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (6.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.FFF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (7.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.PPPP -> 
                {
                    velocity = 10.0
                }
                com.omnifret.gplayer.model.DynamicValue.PPPPP -> 
                {
                    velocity = 5.0
                }
                com.omnifret.gplayer.model.DynamicValue.PPPPPP -> 
                {
                    velocity = 3.0
                }
                com.omnifret.gplayer.model.DynamicValue.FFFF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (8.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.FFFFF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (9.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.FFFFFF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (10.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.SF, com.omnifret.gplayer.model.DynamicValue.SFP, com.omnifret.gplayer.model.DynamicValue.SFZP, com.omnifret.gplayer.model.DynamicValue.SFPP, com.omnifret.gplayer.model.DynamicValue.SFZ, com.omnifret.gplayer.model.DynamicValue.FZ -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (6.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.FP -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (5.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.RF, com.omnifret.gplayer.model.DynamicValue.RFZ, com.omnifret.gplayer.model.DynamicValue.SFFZ -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + (5.0).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
                }
                com.omnifret.gplayer.model.DynamicValue.N -> 
                {
                    velocity = 1.0
                }
                com.omnifret.gplayer.model.DynamicValue.PF -> 
                {
                    velocity = com.omnifret.gplayer.midi.MidiUtils._minVelocity + ((((4.5).toDouble() * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement)).toInt() or 0)
                }
                else -> { }
            }
            velocity += adjustment * com.omnifret.gplayer.midi.MidiUtils.VelocityIncrement
            return com.omnifret.gplayer.core.ecmaScript.Math.min(com.omnifret.gplayer.core.ecmaScript.Math.max(velocity, 1.0), 127.0)
        }
        
    }
    public constructor()
}

