// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.utils
import com.omnifret.gplayer.core.*

/**
 * Represents the boundaries of a single bar.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class BarBounds
{
    /**
     * Gets or sets the reference to the related 
     */
    public lateinit var masterBarBounds: com.omnifret.gplayer.rendering.utils.MasterBarBounds
    
    /**
     * Gets or sets the bounds covering all visually visible elements spanning this bar.
     */
    public lateinit var visualBounds: com.omnifret.gplayer.rendering.utils.Bounds
    
    /**
     * Gets or sets the actual bounds of the elements in this bar including whitespace areas.
     */
    public lateinit var realBounds: com.omnifret.gplayer.rendering.utils.Bounds
    
    /**
     * Gets or sets the bar related to this boundaries.
     */
    public lateinit var bar: com.omnifret.gplayer.model.Bar
    
    /**
     * Gets or sets a list of the beats contained in this lookup.
     */
    public var beats: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.utils.BeatBounds> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.utils.BeatBounds>(
    )
    
    
    
    /**
     * Adds a new beat to this lookup.
     * @param bounds The beat bounds to add.
     */
    public fun addBeat(bounds: com.omnifret.gplayer.rendering.utils.BeatBounds): Unit{
        bounds.barBounds = this
        this.beats.push(bounds)
        this.masterBarBounds.addBeat(bounds)
    }
    
    /**
     * Tries to find the beat at the given X-position.
     * @param x The X-position of the beat to find.
     */
    public fun findBeatAtPos(x: Double): com.omnifret.gplayer.rendering.utils.BeatBounds?{
        var beat: com.omnifret.gplayer.rendering.utils.BeatBounds? = null
        for (t in this.beats)
        {
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(beat)) || t.realBounds.x < x)
            {
                beat = t
            }
            else if (t.realBounds.x > x)
            {
                break
            }
        }
        return beat
    }
    
    /**
     * Finishes the lookup object and optimizes itself for fast access.
     */
    public fun finish(scale: Double = 1.0): Unit{
        this.realBounds.scaleWith(scale)
        this.visualBounds.scaleWith(scale)
        this.beats.sort(fun(a: com.omnifret.gplayer.rendering.utils.BeatBounds, b: com.omnifret.gplayer.rendering.utils.BeatBounds): Double{
            return a.realBounds.x - b.realBounds.x
        }
        )
        for (b in this.beats)
        {
            b.finish(scale)
        }
    }
    
    public constructor()
}

