// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering
import com.omnifret.gplayer.core.*

/**
 * Lists the different position modes for 
 */
internal enum class BeatXPosition(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    /**
     * Gets the pre-notes position which is located before the accidentals
     */
    PreNotes(0),
    /**
     * Gets the on-notes position which is located after the accidentals but before the note heads.
     */
    OnNotes(1),
    /**
     * Gets the middle-notes position which is located after in the exact center of the note heads.
     */
    MiddleNotes(2),
    /**
     * Gets position of the stem for this beat
     */
    Stem(3),
    /**
     * Get the post-notes position which is located at after the note heads.
     */
    PostNotes(4),
    /**
     * Get the end-beat position which is located at the end of the beat. This position is almost
     * equal to the pre-notes position of the next beat.
     */
    EndBeat(5);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<BeatXPosition>{
        public override val values = arrayOf(PreNotes, OnNotes, MiddleNotes, Stem, PostNotes, EndBeat) 
        public override fun fromValue(v:Double): BeatXPosition{
            return when(v.toInt()){
                PreNotes.value -> PreNotes
                OnNotes.value -> OnNotes
                MiddleNotes.value -> MiddleNotes
                Stem.value -> Stem
                PostNotes.value -> PostNotes
                EndBeat.value -> EndBeat
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

