// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class EffectBandSizingInfo
{
    private var _effectSlot: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.EffectBandSlot>
    
    private var _assignedSlots: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.EffectBand, com.omnifret.gplayer.rendering.EffectBandSlot>
    
    public var slots: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandSlot>
    
    public var owner: com.omnifret.gplayer.rendering.EffectBandContainer
    
    public constructor(owner: com.omnifret.gplayer.rendering.EffectBandContainer){
        this.slots = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandSlot>(
        )
        
        this._effectSlot = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.EffectBandSlot>()
        this._assignedSlots = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.EffectBand, com.omnifret.gplayer.rendering.EffectBandSlot>()
        this.owner = owner
    }
    
    public fun reset(): Unit{
        this._effectSlot.clear()
        this._assignedSlots.clear()
        this.slots = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandSlot>(
        )
        
    }
    
    /**
     */
    public fun getOrCreateSlot(band: com.omnifret.gplayer.rendering.EffectBand): com.omnifret.gplayer.rendering.EffectBandSlot{
        if (this._assignedSlots.has(band))
        {
            return this._assignedSlots.get(band)!!
        }
        if (this._effectSlot.has(band.info.effectId))
        {
            var slot: com.omnifret.gplayer.rendering.EffectBandSlot = this._effectSlot.get(band.info.effectId)!!
            if (slot.canBeUsed(band))
            {
                this._assignedSlots.set(band, slot)
                return slot
            }
        }
        for (slot in this.slots)
        {
            if (slot.canBeUsed(band))
            {
                this._assignedSlots.set(band, slot)
                return slot
            }
        }
        var newSlot: com.omnifret.gplayer.rendering.EffectBandSlot = com.omnifret.gplayer.rendering.EffectBandSlot()
        this.slots.push(newSlot)
        this._assignedSlots.set(band, newSlot)
        return newSlot
    }
    
    /**
     */
    public fun register(effectBand: com.omnifret.gplayer.rendering.EffectBand): Unit{
        var freeSlot: com.omnifret.gplayer.rendering.EffectBandSlot = this.getOrCreateSlot(effectBand)
        freeSlot.update(effectBand)
        this._effectSlot.set(effectBand.info.effectId, freeSlot)
    }
    
    /**
     */
    public fun sortSlots(sortOrder: com.omnifret.gplayer.collections.ObjectDoubleMap<com.omnifret.gplayer.rendering.EffectInfo>): Unit{
        for (s in this.slots)
        {
            s.bands.sort(fun(a: com.omnifret.gplayer.rendering.EffectBand, b: com.omnifret.gplayer.rendering.EffectBand): Double{
                var ai: Double = sortOrder.get(a.info)!!
                var bi: Double = sortOrder.get(b.info)!!
                return ai - bi
            }
            )
        }
        this.slots.sort(fun(a: com.omnifret.gplayer.rendering.EffectBandSlot, b: com.omnifret.gplayer.rendering.EffectBandSlot): Double{
            var ai: Double = sortOrder.get(a.bands[(0).toInt()].info)!!
            var bi: Double = sortOrder.get(b.bands[(0).toInt()].info)!!
            return ai - bi
        }
        )
    }
    
}

