// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering
import com.omnifret.gplayer.core.*

/**
 * This BarRenderer renders a bar using standard music notation.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreBarRenderer: com.omnifret.gplayer.rendering.LineBarRenderer
{
    public var accidentalHelper: com.omnifret.gplayer.rendering.utils.AccidentalHelper
    
    public constructor(renderer: com.omnifret.gplayer.rendering.ScoreRenderer, bar: com.omnifret.gplayer.model.Bar)
        : super(renderer, bar){
        this.accidentalHelper = com.omnifret.gplayer.rendering.utils.AccidentalHelper(this)
    }
    
    public override val repeatsBarSubElement: com.omnifret.gplayer.model.BarSubElement
    get(){
        return com.omnifret.gplayer.model.BarSubElement.StandardNotationRepeats
    }
    
    public override val barNumberBarSubElement: com.omnifret.gplayer.model.BarSubElement
    get(){
        return com.omnifret.gplayer.model.BarSubElement.StandardNotationBarNumber
    }
    
    public override val barLineBarSubElement: com.omnifret.gplayer.model.BarSubElement
    get(){
        return com.omnifret.gplayer.model.BarSubElement.StandardNotationBarLines
    }
    
    public override val staffLineBarSubElement: com.omnifret.gplayer.model.BarSubElement
    get(){
        return com.omnifret.gplayer.model.BarSubElement.StandardNotationStaffLine
    }
    
    public override val lineSpacing: Double
    get(){
        return this.smuflMetrics.oneStaffSpace
    }
    
    public override val heightLineCount: Double
    get(){
        return com.omnifret.gplayer.core.ecmaScript.Math.max(5.0, this.bar.staff.standardNotationLineCount)
    }
    
    public override val drawnLineCount: Double
    get(){
        return this.bar.staff.standardNotationLineCount
    }
    
    /**
     * Gets the relative y position of the given steps relative to first line.
     * @param steps the amount of steps while 2 steps are one line
     */
    public fun getScoreY(steps: Double): Double{
        return super.getLineY(steps / (2.0).toDouble())
    }
    
    /**
     * Gets the height of an element that spans the given amount of steps.
     * @param steps the amount of steps while 2 steps are one line
     */
    public fun getScoreHeight(steps: Double): Double{
        return super.getLineHeight(steps / (2.0).toDouble())
    }
    
    /**
     */
    protected override fun calculateOverflows(rendererTop: Double, rendererBottom: Double): Unit{
        super.calculateOverflows(rendererTop, rendererBottom)
        if (this.bar.isEmpty)
        {
            return
        }
        this.calculateBeamingOverflows(rendererTop, rendererBottom)
    }
    
    protected override val flagsSubElement: com.omnifret.gplayer.model.BeatSubElement
    get(){
        return com.omnifret.gplayer.model.BeatSubElement.StandardNotationFlags
    }
    
    protected override val beamsSubElement: com.omnifret.gplayer.model.BeatSubElement
    get(){
        return com.omnifret.gplayer.model.BeatSubElement.StandardNotationBeams
    }
    
    protected override val tupletSubElement: com.omnifret.gplayer.model.BeatSubElement
    get(){
        return com.omnifret.gplayer.model.BeatSubElement.StandardNotationTuplet
    }
    
    /**
     */
    protected override fun getFlagTopY(beat: com.omnifret.gplayer.model.Beat, direction: com.omnifret.gplayer.rendering.utils.BeamDirection): Double{
        var position: com.omnifret.gplayer.rendering.NoteYPosition = if(direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)  com.omnifret.gplayer.rendering.NoteYPosition.TopWithStem else com.omnifret.gplayer.rendering.NoteYPosition.StemDown
        if (beat.isRest)
        {
            return this.getRestY(beat, ((position as com.omnifret.gplayer.rendering.NoteYPosition)))
        }
        else 
        {
            return this.voiceContainer.getHighestNoteY(beat, ((position as com.omnifret.gplayer.rendering.NoteYPosition)))
        }
    }
    
    /**
     */
    protected override fun getFlagBottomY(beat: com.omnifret.gplayer.model.Beat, direction: com.omnifret.gplayer.rendering.utils.BeamDirection): Double{
        var position: com.omnifret.gplayer.rendering.NoteYPosition = if(direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)  com.omnifret.gplayer.rendering.NoteYPosition.StemUp else com.omnifret.gplayer.rendering.NoteYPosition.BottomWithStem
        if (beat.isRest)
        {
            return this.getRestY(beat, ((position as com.omnifret.gplayer.rendering.NoteYPosition)))
        }
        else 
        {
            return this.voiceContainer.getLowestNoteY(beat, ((position as com.omnifret.gplayer.rendering.NoteYPosition)))
        }
    }
    
    /**
     */
    protected override fun getBeamDirection(helper: com.omnifret.gplayer.rendering.utils.BeamingHelper): com.omnifret.gplayer.rendering.utils.BeamDirection{
        return if(this._beamDirections.has(helper))  this._beamDirections.get(helper)!! else com.omnifret.gplayer.rendering.utils.BeamDirection.Up
    }
    
    /**
     */
    public fun centerStaffStemY(direction: com.omnifret.gplayer.rendering.utils.BeamDirection): Double{
        var isStandardFive: Boolean = this.bar.staff.standardNotationLineCount == com.omnifret.gplayer.model.Staff.DefaultStandardNotationLineCount
        if (isStandardFive)
        {
            return this.getScoreY(this.bar.staff.standardNotationLineCount - (1.0).toDouble())
        }
        if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        {
            return this.getScoreY(this.bar.staff.standardNotationLineCount * (2.0).toDouble())
        }
        return this.getScoreY(0.0)
    }
    
    public override val middleYPosition: Double
    get(){
        return this.getScoreY(this.bar.staff.standardNotationLineCount - (1.0).toDouble())
    }
    
    public override fun applyLayoutingInfo(): Boolean{
        var result: Boolean = super.applyLayoutingInfo()
        if (result && this.bar.isMultiVoice)
        {
            var top: Double = this.getScoreY(-2.0)
            var bottom: Double = this.getScoreY(this.heightLineCount * (2.0).toDouble())
            var minMax: com.omnifret.gplayer.collections.DoubleList = this.helpers.collisionHelper.getBeatMinMaxY()
            if (minMax[(0).toInt()] < top)
            {
                this.registerOverflowTop(com.omnifret.gplayer.core.ecmaScript.Math.abs(minMax[(0).toInt()]))
            }
            if (minMax[(1).toInt()] > bottom)
            {
                this.registerOverflowBottom(com.omnifret.gplayer.core.ecmaScript.Math.abs(minMax[(1).toInt()]) - bottom)
            }
        }
        return result
    }
    
    /**
     */
    protected override fun getMinLineOfBeat(beat: com.omnifret.gplayer.model.Beat): Double{
        return this.accidentalHelper.getMinSteps(beat) / (2.0).toDouble()
    }
    
    /**
     */
    protected override fun getMaxLineOfBeat(beat: com.omnifret.gplayer.model.Beat): Double{
        return this.accidentalHelper.getMaxSteps(beat) / (2.0).toDouble()
    }
    
    protected override fun createLinePreBeatGlyphs(): Unit{
        var hasClef: Boolean = false
        if (this.isFirstOfStaff || this.bar.clef != this.bar.previousBar!!.clef || this.bar.clefOttava != this.bar.previousBar!!.clefOttava)
        {
            var offset: Double = 0.0
            when (this.bar.clef)
            {
                com.omnifret.gplayer.model.Clef.Neutral -> 
                {
                    offset = this.bar.staff.standardNotationLineCount - (1.0).toDouble()
                }
                com.omnifret.gplayer.model.Clef.F4 -> 
                {
                    offset = 2.0
                }
                com.omnifret.gplayer.model.Clef.C3 -> 
                {
                    offset = 4.0
                }
                com.omnifret.gplayer.model.Clef.C4 -> 
                {
                    offset = 2.0
                }
                com.omnifret.gplayer.model.Clef.G2 -> 
                {
                    offset = 6.0
                }
                else -> { }
            }
            this.createStartSpacing()
            this.addPreBeatGlyph(com.omnifret.gplayer.rendering.glyphs.ClefGlyph(0.0, this.getScoreY(offset), this.bar.clef, this.bar.clefOttava))
            this.addPreBeatGlyph(com.omnifret.gplayer.rendering.glyphs.SpacingGlyph(0.0, 0.0, this.smuflMetrics.preBeatGlyphSpacing))
            hasClef = true
        }
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(hasClef || (this.index == 0.0 && this.bar.keySignature != com.omnifret.gplayer.model.KeySignature.C) || com.omnifret.gplayer.core.TypeHelper.isTruthy((com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar)) && this.bar.keySignature != this.bar.previousBar!!.keySignature)))))
        {
            this.createStartSpacing()
            this._createKeySignatureGlyphs()
        }
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar)) || (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar!!)) && this.bar.masterBar.timeSignatureNumerator != this.bar.previousBar!!.masterBar.timeSignatureNumerator) || (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar!!)) && this.bar.masterBar.timeSignatureDenominator != this.bar.previousBar!!.masterBar.timeSignatureDenominator) || (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar!!)) && this.bar.masterBar.isFreeTime && this.bar.masterBar.isFreeTime != this.bar.previousBar!!.masterBar.isFreeTime))
        {
            this.createStartSpacing()
            this._createTimeSignatureGlyphs()
        }
    }
    
    private fun _createKeySignatureGlyphs(): Unit{
        var offsetClef: Double = 0.0
        var currentKey: Double = this.bar.keySignature.toDouble()
        var previousKey: Double = if(!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.bar.previousBar)))  0.0 else (this.bar.previousBar!!.keySignature.toDouble())
        when (this.bar.clef)
        {
            com.omnifret.gplayer.model.Clef.Neutral -> 
            {
                offsetClef = 0.0
            }
            com.omnifret.gplayer.model.Clef.G2 -> 
            {
                offsetClef = 1.0
            }
            com.omnifret.gplayer.model.Clef.F4 -> 
            {
                offsetClef = 3.0
            }
            com.omnifret.gplayer.model.Clef.C3 -> 
            {
                offsetClef = 2.0
            }
            com.omnifret.gplayer.model.Clef.C4 -> 
            {
                offsetClef = 0.0
            }
            else -> { }
        }
        var glyph: com.omnifret.gplayer.rendering.glyphs.KeySignatureGlyph = com.omnifret.gplayer.rendering.glyphs.KeySignatureGlyph()
        glyph.gap = this.smuflMetrics.accidentalPadding
        glyph.renderer = this
        var newLines: com.omnifret.gplayer.collections.DoubleBooleanMap = com.omnifret.gplayer.collections.DoubleBooleanMap()
        var newGlyphs: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph>(
        )
        
        if (com.omnifret.gplayer.model.ModelUtils.keySignatureIsSharp(currentKey))
        {
            if (true) {
                var i: Double = 0.0
                
                while(i < com.omnifret.gplayer.core.ecmaScript.Math.abs(currentKey)){
                    var step: Double = com.omnifret.gplayer.rendering.ScoreBarRenderer._sharpKsSteps[(i).toInt()] + offsetClef
                    newGlyphs.push(com.omnifret.gplayer.rendering.glyphs.AccidentalGlyph(0.0, this.getScoreY(step), com.omnifret.gplayer.model.AccidentalType.Sharp, 1.0))
                    newLines.set(step, true)
                    i++
                }
            }
        }
        else 
        {
            if (true) {
                var i: Double = 0.0
                
                while(i < com.omnifret.gplayer.core.ecmaScript.Math.abs(currentKey)){
                    var step: Double = com.omnifret.gplayer.rendering.ScoreBarRenderer._flatKsSteps[(i).toInt()] + offsetClef
                    newGlyphs.push(com.omnifret.gplayer.rendering.glyphs.AccidentalGlyph(0.0, this.getScoreY(step), com.omnifret.gplayer.model.AccidentalType.Flat, 1.0))
                    newLines.set(step, true)
                    i++
                }
            }
        }
        if (this.bar.keySignature == com.omnifret.gplayer.model.KeySignature.C)
        {
            var naturalizeSymbols: Double = com.omnifret.gplayer.core.ecmaScript.Math.abs(previousKey)
            var previousKeyPositions: com.omnifret.gplayer.collections.DoubleList = if(com.omnifret.gplayer.model.ModelUtils.keySignatureIsSharp(previousKey))  com.omnifret.gplayer.rendering.ScoreBarRenderer._sharpKsSteps else com.omnifret.gplayer.rendering.ScoreBarRenderer._flatKsSteps
            if (true) {
                var i: Double = 0.0
                
                while(i < naturalizeSymbols){
                    var step: Double = previousKeyPositions[(i).toInt()] + offsetClef
                    if (!newLines.has(step))
                    {
                        glyph.addGlyph(com.omnifret.gplayer.rendering.glyphs.AccidentalGlyph(0.0, this.getScoreY(previousKeyPositions[(i).toInt()] + offsetClef), com.omnifret.gplayer.model.AccidentalType.Natural, 1.0))
                    }
                    i++
                }
            }
        }
        for (newGlyph in newGlyphs)
        {
            glyph.addGlyph(newGlyph)
        }
        this.addPreBeatGlyph(glyph)
        if (!glyph.isEmpty)
        {
            this.addPreBeatGlyph(com.omnifret.gplayer.rendering.glyphs.SpacingGlyph(0.0, 0.0, this.smuflMetrics.preBeatGlyphSpacing))
        }
    }
    
    private fun _createTimeSignatureGlyphs(): Unit{
        var lines: Double = this.bar.staff.standardNotationLineCount - (1.0).toDouble()
        this.addPreBeatGlyph(com.omnifret.gplayer.rendering.glyphs.ScoreTimeSignatureGlyph(0.0, 
        this.getScoreY(lines), 
        this.bar.masterBar.timeSignatureNumerator, 
        this.bar.masterBar.timeSignatureDenominator, 
        this.bar.masterBar.timeSignatureCommon, 
        this.bar.masterBar.isFreeTime))
        this.addPreBeatGlyph(com.omnifret.gplayer.rendering.glyphs.SpacingGlyph(0.0, 0.0, this.smuflMetrics.preBeatGlyphSpacing))
    }
    
    /**
     */
    protected override fun createVoiceGlyphs(v: com.omnifret.gplayer.model.Voice): Unit{
        super.createVoiceGlyphs(v)
        for (b in v.beats)
        {
            this.addBeatGlyph(com.omnifret.gplayer.rendering.ScoreBeatContainerGlyph(b))
        }
    }
    
    /**
     */
    public override fun getNoteLine(note: com.omnifret.gplayer.model.Note): Double{
        return this.accidentalHelper.getNoteSteps(note) / (2.0).toDouble()
    }
    
    /**
     */
    public fun getNoteSteps(n: com.omnifret.gplayer.model.Note): Double{
        return this.accidentalHelper.getNoteSteps(n)
    }
    
    private var _beamDirections: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.utils.BeamingHelper, com.omnifret.gplayer.rendering.utils.BeamDirection> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.utils.BeamingHelper, com.omnifret.gplayer.rendering.utils.BeamDirection>()
    
    /**
     */
    public override fun completeBeamingHelper(helper: com.omnifret.gplayer.rendering.utils.BeamingHelper): Unit{
        var direction: com.omnifret.gplayer.rendering.utils.BeamDirection = this._calculateBeamDirection(helper)
        this._beamDirections.set(helper, direction)
    }
    
    /**
     */
    private fun _calculateBeamDirection(helper: com.omnifret.gplayer.rendering.utils.BeamingHelper): com.omnifret.gplayer.rendering.utils.BeamDirection{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(helper.voice)))
        {
            return com.omnifret.gplayer.rendering.utils.BeamDirection.Up
        }
        if (helper.preferredBeamDirection != null)
        {
            return helper.preferredBeamDirection!!
        }
        if (helper.voice!!.index > 0)
        {
            return this._invertBeamDirection(helper, com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
        }
        if (helper.voice!!.bar.isMultiVoice)
        {
            return this._invertBeamDirection(helper, com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        }
        if (helper.beats[(0).toInt()].graceType != com.omnifret.gplayer.model.GraceType.None)
        {
            return this._invertBeamDirection(helper, com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        }
        if (helper.beats.length == 1.0 && helper.beats[(0).toInt()].slashed)
        {
            return this._invertBeamDirection(helper, com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
        }
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(helper.highestNoteInHelper)) && com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(helper.lowestNoteInHelper))))
        {
            var highestNotePosition: Double = this._getNoteCenterYBeforeLayouting(helper.highestNoteInHelper!!)
            var lowestNotePosition: Double = this._getNoteCenterYBeforeLayouting(helper.lowestNoteInHelper!!)
            var avg: Double = (highestNotePosition + lowestNotePosition) / (2.0).toDouble()
            return this._invertBeamDirection(helper, if(this.middleYPosition < avg)  com.omnifret.gplayer.rendering.utils.BeamDirection.Up else com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
        }
        return this._invertBeamDirection(helper, com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
    }
    
    /**
     */
    private fun _getNoteCenterYBeforeLayouting(note: com.omnifret.gplayer.model.Note): Double{
        var steps: Double = com.omnifret.gplayer.rendering.utils.AccidentalHelper.computeStepsWithoutAccidentals(this.bar, note)
        return this.getScoreY(steps)
    }
    
    /**
     */
    private fun _invertBeamDirection(helper: com.omnifret.gplayer.rendering.utils.BeamingHelper, direction: com.omnifret.gplayer.rendering.utils.BeamDirection): com.omnifret.gplayer.rendering.utils.BeamDirection{
        if (!helper.invertBeamDirection)
        {
            return direction
        }
        when (direction)
        {
            com.omnifret.gplayer.rendering.utils.BeamDirection.Down -> 
            {
                return com.omnifret.gplayer.rendering.utils.BeamDirection.Up
            }
            else -> 
            {
                return com.omnifret.gplayer.rendering.utils.BeamDirection.Down
            }
        }
    }
    
    /**
     */
    protected override fun paintBeamingStem(beat: com.omnifret.gplayer.model.Beat, 
    _cy: Double, 
    x: Double, 
    topY: Double, 
    bottomY: Double, 
    canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        (com.omnifret.gplayer.rendering.utils.ElementStyleHelper.beat(canvas, com.omnifret.gplayer.model.BeatSubElement.StandardNotationStem, beat))
        .use {
            canvas.fillRect(x, topY, this.smuflMetrics.stemThickness, bottomY - topY)
        }
    }
    
    companion object{
        @kotlin.jvm.JvmStatic
        public val StaffId: String = "score"
        
        @kotlin.jvm.JvmStatic
        private var _sharpKsSteps: com.omnifret.gplayer.collections.DoubleList = com.omnifret.gplayer.collections.DoubleList(
            -1.0, 
            2.0, 
            -2.0, 
            1.0, 
            4.0, 
            0.0, 
            3.0)
        
        
        @kotlin.jvm.JvmStatic
        private var _flatKsSteps: com.omnifret.gplayer.collections.DoubleList = com.omnifret.gplayer.collections.DoubleList(
            3.0, 
            0.0, 
            4.0, 
            1.0, 
            5.0, 
            2.0, 
            6.0)
        
        
    }
}

