// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Lists all types of how to brush multiple notes on a beat.
 */
public enum class BrushType(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    /**
     * No brush.
     */
    None(0),
    /**
     * Normal brush up.
     */
    BrushUp(1),
    /**
     * Normal brush down.
     */
    BrushDown(2),
    /**
     * Arpeggio up.
     */
    ArpeggioUp(3),
    /**
     * Arpeggio down.
     */
    ArpeggioDown(4);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<BrushType>{
        public override val values = arrayOf(None, BrushUp, BrushDown, ArpeggioUp, ArpeggioDown) 
        public override fun fromValue(v:Double): BrushType{
            return when(v.toInt()){
                None.value -> None
                BrushUp.value -> BrushUp
                BrushDown.value -> BrushDown
                ArpeggioUp.value -> ArpeggioUp
                ArpeggioDown.value -> ArpeggioDown
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

