// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Lists all types of grace notes
 */
public enum class GraceType(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    /**
     * No grace, normal beat.
     */
    None(0),
    /**
     * The beat contains on-beat grace notes.
     */
    OnBeat(1),
    /**
     * The beat contains before-beat grace notes.
     */
    BeforeBeat(2),
    /**
     * The beat contains very special bend-grace notes used in SongBook style displays.
     */
    BendGrace(3);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<GraceType>{
        public override val values = arrayOf(None, OnBeat, BeforeBeat, BendGrace) 
        public override fun fromValue(v:Double): GraceType{
            return when(v.toInt()){
                None.value -> None
                OnBeat.value -> OnBeat
                BeforeBeat.value -> BeforeBeat
                BendGrace.value -> BendGrace
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

