// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Represents the lyrics of a song.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Lyrics
{
    /**
     * Gets or sets he start bar on which the lyrics should begin.
     */
    public var startBar: Double = 0.0
    
    
    /**
     * Gets or sets the raw lyrics text in Guitar Pro format.
     * (spaces split word syllables, plus merge syllables, [..] are comments)
     */
    public var text: String = ""
    
    
    /**
     * Gets or sets the prepared chunks of the lyrics to apply to beats.
     */
    public lateinit var chunks: com.omnifret.gplayer.collections.List<String>
    
    /**
     */
    public fun finish(skipEmptyEntries: Boolean = false): Unit{
        this.chunks = com.omnifret.gplayer.collections.List<String>(
        )
        
        this._parse(this.text, 0.0, this.chunks, skipEmptyEntries)
    }
    
    /**
     */
    private fun _parse(str: String, p: Double, _chunks: com.omnifret.gplayer.collections.List<String>, skipEmptyEntries: Boolean): Unit{
        var paramp = p
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(str)))
        {
            return
        }
        var state: com.omnifret.gplayer.model.LyricsState = com.omnifret.gplayer.model.LyricsState.Begin
        var next: com.omnifret.gplayer.model.LyricsState = com.omnifret.gplayer.model.LyricsState.Begin
        var skipSpace: Boolean = false
        var start: Double = 0.0
        while (paramp < str.length.toDouble())
        {
            var c: Double = str.charCodeAt(paramp)
            when (state)
            {
                com.omnifret.gplayer.model.LyricsState.IgnoreSpaces -> 
                {
                    when (c)
                    {
                        com.omnifret.gplayer.model.Lyrics._charCodeLF, com.omnifret.gplayer.model.Lyrics._charCodeCR, com.omnifret.gplayer.model.Lyrics._charCodeTab -> 
                        {
                        }
                        com.omnifret.gplayer.model.Lyrics._charCodeSpace -> 
                        {
                            if (!skipSpace)
                            {
                                state = next
                                continue
                            }
                        }
                        else -> 
                        {
                            skipSpace = false
                            state = next
                            continue
                        }
                    }
                }
                com.omnifret.gplayer.model.LyricsState.Begin -> 
                {
                    when (c)
                    {
                        com.omnifret.gplayer.model.Lyrics._charCodeBrackedOpen -> 
                        {
                            state = com.omnifret.gplayer.model.LyricsState.Comment
                        }
                        else -> 
                        {
                            start = paramp
                            state = com.omnifret.gplayer.model.LyricsState.Text
                            continue
                        }
                    }
                }
                com.omnifret.gplayer.model.LyricsState.Comment -> 
                {
                    when (c)
                    {
                        com.omnifret.gplayer.model.Lyrics._charCodeBrackedClose -> 
                        {
                            state = com.omnifret.gplayer.model.LyricsState.Begin
                        }
                        else -> { }
                    }
                }
                com.omnifret.gplayer.model.LyricsState.Text -> 
                {
                    when (c)
                    {
                        com.omnifret.gplayer.model.Lyrics._charCodeDash -> 
                        {
                            state = com.omnifret.gplayer.model.LyricsState.Dash
                        }
                        com.omnifret.gplayer.model.Lyrics._charCodeCR, com.omnifret.gplayer.model.Lyrics._charCodeLF, com.omnifret.gplayer.model.Lyrics._charCodeSpace -> 
                        {
                            var txt: String = str.substr(start, paramp - start)
                            this._addChunk(txt, skipEmptyEntries)
                            state = com.omnifret.gplayer.model.LyricsState.IgnoreSpaces
                            next = com.omnifret.gplayer.model.LyricsState.Begin
                        }
                        else -> { }
                    }
                }
                com.omnifret.gplayer.model.LyricsState.Dash -> 
                {
                    when (c)
                    {
                        com.omnifret.gplayer.model.Lyrics._charCodeDash -> 
                        {
                        }
                        else -> 
                        {
                            var txt: String = str.substr(start, paramp - start)
                            this._addChunk(txt, skipEmptyEntries)
                            skipSpace = true
                            state = com.omnifret.gplayer.model.LyricsState.IgnoreSpaces
                            next = com.omnifret.gplayer.model.LyricsState.Begin
                            continue
                        }
                    }
                }
                else -> { }
            }
            paramp += 1.0
        }
        if (state == com.omnifret.gplayer.model.LyricsState.Text)
        {
            if (paramp != start)
            {
                this._addChunk(str.substr(start, paramp - start), skipEmptyEntries)
            }
        }
    }
    
    /**
     */
    private fun _addChunk(txt: String, skipEmptyEntries: Boolean): Unit{
        var paramtxt = txt
        paramtxt = this._prepareChunk(paramtxt)
        if (!skipEmptyEntries || (paramtxt.length.toDouble() > 0 && paramtxt != "-"))
        {
            this.chunks.push(paramtxt)
        }
    }
    
    /**
     */
    private fun _prepareChunk(txt: String): String{
        var chunk: String = txt.splitBy("+").join(" ")
        var endLength: Double = chunk.length.toDouble()
        while (endLength > 0 && chunk.charAt(endLength - (1.0).toDouble()) == "_")
        {
            endLength--
        }
        return if(endLength != chunk.length.toDouble())  chunk.substr(0.0, endLength) else chunk
    }
    
    companion object{
        @kotlin.jvm.JvmStatic
        private val _charCodeLF: Double = 10.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeTab: Double = 9.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeCR: Double = 13.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeSpace: Double = 32.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeBrackedClose: Double = 93.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeBrackedOpen: Double = 91.0
        
        @kotlin.jvm.JvmStatic
        private val _charCodeDash: Double = 45.0
        
    }
    public constructor()
}

internal enum class LyricsState(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    IgnoreSpaces(0),
    Begin(1),
    Text(2),
    Comment(3),
    Dash(4);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<LyricsState>{
        public override val values = arrayOf(IgnoreSpaces, Begin, Text, Comment, Dash) 
        public override fun fromValue(v:Double): LyricsState{
            return when(v.toInt()){
                IgnoreSpaces.value -> IgnoreSpaces
                Begin.value -> Begin
                Text.value -> Text
                Comment.value -> Comment
                Dash.value -> Dash
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

