// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * The MasterBar stores information about a bar which affects
 * all tracks.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class MasterBar
{
    /**
     * Gets or sets the bitflag for the alternate endings. Each bit defines for which repeat counts
     * the bar is played.
     */
    public var alternateEndings: Double = 0.0
    
    
    /**
     * Gets or sets the next masterbar in the song.
     */
    public var nextMasterBar: com.omnifret.gplayer.model.MasterBar? = null
    
    
    /**
     * Gets or sets the next masterbar in the song.
     */
    public var previousMasterBar: com.omnifret.gplayer.model.MasterBar? = null
    
    
    /**
     * Gets the zero based index of the masterbar.
     */
    public var index: Double = 0.0
    
    
    public val hasChanges: Boolean
    get(){
        if (this.index == 0.0)
        {
            return false
        }
        var hasChangesToPrevious: Boolean = this.timeSignatureCommon != this.previousMasterBar!!.timeSignatureCommon || this.timeSignatureNumerator != this.previousMasterBar!!.timeSignatureNumerator || this.timeSignatureDenominator != this.previousMasterBar!!.timeSignatureDenominator || this.tripletFeel != this.previousMasterBar!!.tripletFeel
        if (hasChangesToPrevious)
        {
            return true
        }
        return (com.omnifret.gplayer.core.TypeHelper.isTruthy(this.alternateEndings != 0.0 || this.isRepeatStart || this.isRepeatEnd || this.isFreeTime || this.isSectionStart || this.tempoAutomations.length > 0 || com.omnifret.gplayer.core.TypeHelper.isTruthy((com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.syncPoints)) && this.syncPoints!!.length > 0)))) || (this.fermata != null && this.fermata!!.size > 0) || (this.directions != null && this.directions!!.size > 0) || this.isAnacrusis)
    }
    
    public var keySignature: com.omnifret.gplayer.model.KeySignature
    get(){
        return this.score.tracks[(0).toInt()].staves[(0).toInt()].bars[(this.index).toInt()].keySignature
    }
    set(value){
        this.score.tracks[(0).toInt()].staves[(0).toInt()].bars[(this.index).toInt()].keySignature = value
    }
    
    public var keySignatureType: com.omnifret.gplayer.model.KeySignatureType
    get(){
        return this.score.tracks[(0).toInt()].staves[(0).toInt()].bars[(this.index).toInt()].keySignatureType
    }
    set(value){
        this.score.tracks[(0).toInt()].staves[(0).toInt()].bars[(this.index).toInt()].keySignatureType = value
    }
    
    /**
     * Gets or sets whether a double bar is shown for this masterbar.
     */
    @kotlin.Deprecated("Use Bar.barLineLeft and Bar.barLineRight")
    public var isDoubleBar: Boolean = false
    
    
    /**
     * Gets or sets whether a repeat section starts on this masterbar.
     */
    public var isRepeatStart: Boolean = false
    
    
    public val isRepeatEnd: Boolean
    get(){
        return this.repeatCount > 0
    }
    
    /**
     * Gets or sets the number of repeats for the current repeat section.
     */
    public var repeatCount: Double = 0.0
    
    
    /**
     * Gets or sets the repeat group this bar belongs to.
     */
    public lateinit var repeatGroup: com.omnifret.gplayer.model.RepeatGroup
    
    /**
     * Gets or sets the time signature numerator.
     */
    public var timeSignatureNumerator: Double = 4.0
    
    
    /**
     * Gets or sets the time signature denominiator.
     */
    public var timeSignatureDenominator: Double = 4.0
    
    
    /**
     * Gets or sets whether this is bar has a common time signature.
     */
    public var timeSignatureCommon: Boolean = false
    
    
    /**
     * Defines the custom beaming rules which should be applied to this bar and all bars following.
     */
    public var beamingRules: com.omnifret.gplayer.model.BeamingRules? = null
    
    /**
     * The actual (custom) beaming rules to use for this bar if any were specified.
     */
    internal var actualBeamingRules: com.omnifret.gplayer.model.BeamingRules? = null
    
    /**
     * Gets or sets whether the bar indicates a free time playing.
     */
    public var isFreeTime: Boolean = false
    
    
    /**
     * Gets or sets the triplet feel that is valid for this bar.
     */
    public var tripletFeel: com.omnifret.gplayer.model.TripletFeel = com.omnifret.gplayer.model.TripletFeel.NoTripletFeel
    
    
    /**
     * Gets or sets the new section information for this bar.
     */
    public var section: com.omnifret.gplayer.model.Section? = null
    
    
    public val isSectionStart: Boolean
    get(){
        return !!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.section))
    }
    
    public val tempoAutomation: com.omnifret.gplayer.model.Automation?
    get(){
        return if(this.tempoAutomations.length > 0)  this.tempoAutomations[(0).toInt()] else null
    }
    
    /**
     * Gets or sets all tempo automation for this bar.
     */
    public var tempoAutomations: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Automation> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Automation>(
    )
    
    
    
    /**
     * The sync points for this master bar to synchronize the the library time axis with the
     * external backing track audio.
     */
    public var syncPoints: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Automation>? = null
    
    /**
     * Gets or sets the reference to the score this song belongs to.
     */
    public lateinit var score: com.omnifret.gplayer.model.Score
    
    /**
     * Gets or sets the fermatas for this bar. The key is the offset of the fermata in midi ticks.
     */
    public var fermata: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.Fermata>? = null
    
    
    /**
     * The timeline position of the voice within the whole score. (unit: midi ticks)
     */
    public var start: Double = 0.0
    
    
    /**
     * Gets or sets a value indicating whether the master bar is an anacrusis (aka. pickup bar)
     */
    public var isAnacrusis: Boolean = false
    
    
    /**
     * Gets a percentual scale for the size of the bars when displayed in a multi-track layout.
     */
    public var displayScale: Double = 1.0
    
    
    /**
     * An absolute width of the bar to use when displaying in a multi-track layout.
     */
    public var displayWidth: Double = -1.0
    
    
    /**
     * The directions applied to this masterbar.
     */
    public var directions: com.omnifret.gplayer.core.ecmaScript.Set<com.omnifret.gplayer.model.Direction>? = null
    
    
    /**
     * Calculates the time spent in this bar. (unit: midi ticks)
     */
    public fun calculateDuration(respectAnacrusis: Boolean = true): Double{
        if (this.isAnacrusis && respectAnacrusis)
        {
            var duration: Double = 0.0
            for (track in this.score.tracks)
            {
                for (staff in track.staves)
                {
                    var barDuration: Double = if(this.index < staff.bars.length)  staff.bars[(this.index).toInt()].calculateDuration() else 0.0
                    if (barDuration > duration)
                    {
                        duration = barDuration
                    }
                }
            }
            return duration
        }
        return this.timeSignatureNumerator * com.omnifret.gplayer.midi.MidiUtils.valueToTicks(this.timeSignatureDenominator)
    }
    
    /**
     * Adds a fermata to the masterbar.
     * @param offset The offset of the fermata within the bar in midi ticks.
     * @param fermata The fermata.
     */
    public fun addFermata(offset: Double, fermata: com.omnifret.gplayer.model.Fermata): Unit{
        var fermataMap: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.Fermata>? = this.fermata
        if (fermataMap == null)
        {
            fermataMap = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.Fermata>()
            this.fermata = fermataMap!!
        }
        fermataMap!!.set(offset, fermata)
    }
    
    /**
     * Adds a direction to the masterbar.
     * @param direction The direction to add.
     */
    public fun addDirection(direction: com.omnifret.gplayer.model.Direction): Unit{
        if (this.directions == null)
        {
            this.directions = com.omnifret.gplayer.core.ecmaScript.Set<com.omnifret.gplayer.model.Direction>()
        }
        this.directions!!.add(direction)
    }
    
    /**
     * Gets the fermata for a given beat.
     * @param beat The beat to get the fermata for.
     */
    public fun getFermata(beat: com.omnifret.gplayer.model.Beat): com.omnifret.gplayer.model.Fermata?{
        var fermataMap: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.Fermata>? = this.fermata
        if (fermataMap == null)
        {
            return null
        }
        if (fermataMap!!.has(beat.playbackStart))
        {
            return fermataMap!!.get(beat.playbackStart)!!
        }
        if (beat.index == 0.0 && fermataMap!!.has(0.0))
        {
            return fermataMap!!.get(0.0)!!
        }
        return null
    }
    
    /**
     * Adds the given sync point to the list of sync points for this bar.
     * @param syncPoint The sync point to add.
     */
    public fun addSyncPoint(syncPoint: com.omnifret.gplayer.model.Automation): Unit{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.syncPoints)))
        {
            this.syncPoints = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Automation>(
            )
            
        }
        this.syncPoints!!.push(syncPoint)
    }
    
    /**
     */
    public fun finish(sharedDataBag: com.omnifret.gplayer.collections.Map<String, Any?>): Unit{
        var beamingRules: com.omnifret.gplayer.model.BeamingRules? = this.beamingRules
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(beamingRules)))
        {
            beamingRules!!.timeSignatureNumerator = this.timeSignatureNumerator
            beamingRules!!.timeSignatureDenominator = this.timeSignatureDenominator
            beamingRules!!.finish()
        }
        if (this.index > 0)
        {
            this.start = this.previousMasterBar!!.start + this.previousMasterBar!!.calculateDuration()
            var previousRules: com.omnifret.gplayer.model.BeamingRules? = if(sharedDataBag.has("beamingRules"))  ((sharedDataBag.get("beamingRules")!! as com.omnifret.gplayer.model.BeamingRules)) else null
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(previousRules)) && previousRules!!.uniqueId == beamingRules?.uniqueId))
            {
                this.beamingRules = null
                beamingRules = previousRules!!
            }
            else if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(beamingRules)))
            {
                beamingRules = previousRules
            }
        }
        this.actualBeamingRules = beamingRules
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.beamingRules)))
        {
            sharedDataBag.set("beamingRules", beamingRules)
        }
    }
    
    companion object{
        @kotlin.jvm.JvmStatic
        public val MaxAlternateEndings: Double = 8.0
        
    }
    public constructor()
}

/**
 * Defines the custom beaming rules which define how beats are beamed together or split apart
 * during the automatic beaming when displayed.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class BeamingRules
{
    private var _singleGroupKey: com.omnifret.gplayer.model.Duration? = null
    
    /**
     * The the group for a given "longest duration" within the bar.
     */
    public var groups: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>()
    
    
    internal var uniqueId: String = ""
    
    
    internal var timeSignatureNumerator: Double = 0.0
    
    
    internal var timeSignatureDenominator: Double = 0.0
    
    
    /**
     */
    internal fun findRule(shortestDuration: com.omnifret.gplayer.model.Duration): com.omnifret.gplayer.core.IArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>{
        var singleGroupKey: com.omnifret.gplayer.model.Duration? = this._singleGroupKey
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(singleGroupKey)))
        {
            return com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>(singleGroupKey!!, this.groups.get(singleGroupKey!!)!!)
        }
        if (shortestDuration < com.omnifret.gplayer.model.Duration.Quarter)
        {
            return com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>(shortestDuration, com.omnifret.gplayer.collections.DoubleList(
            )
            )
        }
        var durationValue: Double = shortestDuration.toDouble()
        do
        {
            var duration: com.omnifret.gplayer.model.Duration = com.omnifret.gplayer.model.Duration.fromValue(durationValue)
            if (this.groups.has(duration))
            {
                return com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>(duration, this.groups.get(duration)!!)
            }
            durationValue = durationValue * (2.0).toDouble()
        }
        while (durationValue <= (com.omnifret.gplayer.model.Duration.TwoHundredFiftySixth.toDouble()))
        durationValue = (shortestDuration.toDouble()) / (2.0).toDouble()
        do
        {
            var duration: com.omnifret.gplayer.model.Duration = com.omnifret.gplayer.model.Duration.fromValue(durationValue)
            if (this.groups.has(duration))
            {
                return com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>(duration, this.groups.get(duration)!!)
            }
            durationValue = durationValue / (2.0).toDouble()
        }
        while (durationValue > (com.omnifret.gplayer.model.Duration.Half.toDouble()))
        return com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.model.Duration, com.omnifret.gplayer.collections.DoubleList>(shortestDuration, com.omnifret.gplayer.collections.DoubleList(
        )
        )
    }
    
    internal fun finish(): Unit{
        var uniqueId: String = """${(this.timeSignatureNumerator).toTemplate()}_${(this.timeSignatureDenominator).toTemplate()}"""
        for ((k, v) in this.groups)
        {
            uniqueId += """__${(k).toTemplate()}"""
            var lastZero: Double = v.length
            if (true) {
                var i: Double = v.length - (1.0).toDouble()
                
                while(i >= 0){
                    if (v[(i).toInt()] == 0.0)
                    {
                        lastZero = i
                    }
                    else 
                    {
                        break
                    }
                    i--
                }
            }
            if (lastZero < v.length)
            {
                v.splice(lastZero, v.length - lastZero)
            }
            uniqueId += """_${(v.join("_")).toTemplate()}"""
            if (this.groups.size == 1.0)
            {
                this._singleGroupKey = k
            }
        }
        this.uniqueId = uniqueId
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        internal fun createSimple(timeSignatureNumerator: Double, timeSignatureDenominator: Double, duration: com.omnifret.gplayer.model.Duration, groups: com.omnifret.gplayer.collections.DoubleList): com.omnifret.gplayer.model.BeamingRules{
            var r: com.omnifret.gplayer.model.BeamingRules = com.omnifret.gplayer.model.BeamingRules()
            r.timeSignatureNumerator = timeSignatureNumerator
            r.timeSignatureDenominator = timeSignatureDenominator
            r.groups.set(duration, groups)
            r.finish()
            return r
        }
        
    }
    public constructor()
}

