// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class PercussionMapper
{
    companion object{
        @kotlin.jvm.JvmStatic
        public var instrumentArticulations: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.model.InstrumentArticulation> = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.model.InstrumentArticulation>(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.InstrumentArticulation>(
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                38.0
                , 
                "Snare"
                , 
                3.0
                , 
                38.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                37.0
                , 
                "Snare"
                , 
                3.0
                , 
                37.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                91.0
                , 
                "Snare"
                , 
                3.0
                , 
                38.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                42.0
                , 
                "Charley"
                , 
                -1.0
                , 
                42.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                92.0
                , 
                "Charley"
                , 
                -1.0
                , 
                46.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleSlash
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleSlash
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleSlash
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                46.0
                , 
                "Charley"
                , 
                -1.0
                , 
                46.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadCircleX
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                44.0
                , 
                "Charley"
                , 
                9.0
                , 
                44.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                35.0
                , 
                "Acoustic Kick Drum"
                , 
                8.0
                , 
                35.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                36.0
                , 
                "Kick Drum"
                , 
                7.0
                , 
                36.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                50.0
                , 
                "Tom Very High"
                , 
                1.0
                , 
                50.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                48.0
                , 
                "Tom High"
                , 
                2.0
                , 
                48.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                47.0
                , 
                "Tom Medium"
                , 
                4.0
                , 
                47.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                45.0
                , 
                "Tom Low"
                , 
                5.0
                , 
                45.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                43.0
                , 
                "Tom Very Low"
                , 
                6.0
                , 
                43.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                93.0
                , 
                "Ride"
                , 
                0.0
                , 
                51.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.PictEdgeOfCymbal
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Above
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                51.0
                , 
                "Ride"
                , 
                0.0
                , 
                51.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                53.0
                , 
                "Ride"
                , 
                0.0
                , 
                53.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                94.0
                , 
                "Ride"
                , 
                0.0
                , 
                51.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.ArticStaccatoAbove
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                55.0
                , 
                "Splash"
                , 
                -2.0
                , 
                55.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                95.0
                , 
                "Splash"
                , 
                -2.0
                , 
                55.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.ArticStaccatoAbove
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                52.0
                , 
                "China"
                , 
                -3.0
                , 
                52.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                96.0
                , 
                "China"
                , 
                -3.0
                , 
                52.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyXHat
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                49.0
                , 
                "Crash High"
                , 
                -2.0
                , 
                49.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                97.0
                , 
                "Crash High"
                , 
                -2.0
                , 
                49.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.ArticStaccatoAbove
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                57.0
                , 
                "Crash Medium"
                , 
                -1.0
                , 
                57.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                98.0
                , 
                "Crash Medium"
                , 
                -1.0
                , 
                57.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHeavyX
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.ArticStaccatoAbove
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                99.0
                , 
                "Cowbell Low"
                , 
                1.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                100.0
                , 
                "Cowbell Low"
                , 
                1.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                56.0
                , 
                "Cowbell Medium"
                , 
                0.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                101.0
                , 
                "Cowbell Medium"
                , 
                0.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                102.0
                , 
                "Cowbell High"
                , 
                -1.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                103.0
                , 
                "Cowbell High"
                , 
                -1.0
                , 
                56.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                77.0
                , 
                "Woodblock Low"
                , 
                -9.0
                , 
                77.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                76.0
                , 
                "Woodblock High"
                , 
                -10.0
                , 
                76.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                60.0
                , 
                "Bongo High"
                , 
                -4.0
                , 
                60.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                104.0
                , 
                "Bongo High"
                , 
                -5.0
                , 
                60.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                105.0
                , 
                "Bongo High"
                , 
                -6.0
                , 
                60.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                61.0
                , 
                "Bongo Low"
                , 
                -7.0
                , 
                61.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                106.0
                , 
                "Bongo Low"
                , 
                -8.0
                , 
                61.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                107.0
                , 
                "Bongo Low"
                , 
                -16.0
                , 
                61.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                66.0
                , 
                "Timbale Low"
                , 
                10.0
                , 
                66.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                65.0
                , 
                "Timbale High"
                , 
                9.0
                , 
                65.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                68.0
                , 
                "Agogo Low"
                , 
                12.0
                , 
                68.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                67.0
                , 
                "Agogo High"
                , 
                11.0
                , 
                67.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                64.0
                , 
                "Conga Low"
                , 
                17.0
                , 
                64.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                108.0
                , 
                "Conga Low"
                , 
                16.0
                , 
                64.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                109.0
                , 
                "Conga Low"
                , 
                15.0
                , 
                64.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                63.0
                , 
                "Conga High"
                , 
                14.0
                , 
                63.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                110.0
                , 
                "Conga High"
                , 
                13.0
                , 
                63.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                62.0
                , 
                "Conga High"
                , 
                19.0
                , 
                62.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                72.0
                , 
                "Whistle Low"
                , 
                -11.0
                , 
                72.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                71.0
                , 
                "Whistle High"
                , 
                -17.0
                , 
                71.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                73.0
                , 
                "Guiro"
                , 
                38.0
                , 
                73.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                74.0
                , 
                "Guiro"
                , 
                37.0
                , 
                74.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                86.0
                , 
                "Surdo"
                , 
                36.0
                , 
                86.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                87.0
                , 
                "Surdo"
                , 
                35.0
                , 
                87.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                54.0
                , 
                "Tambourine"
                , 
                3.0
                , 
                54.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                111.0
                , 
                "Tambourine"
                , 
                2.0
                , 
                54.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Above
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                112.0
                , 
                "Tambourine"
                , 
                1.0
                , 
                54.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadTriangleUpBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsDownBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Above
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                113.0
                , 
                "Tambourine"
                , 
                -7.0
                , 
                54.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                79.0
                , 
                "Cuica"
                , 
                30.0
                , 
                79.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                78.0
                , 
                "Cuica"
                , 
                29.0
                , 
                78.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                58.0
                , 
                "Vibraslap"
                , 
                28.0
                , 
                58.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                81.0
                , 
                "Triangle"
                , 
                27.0
                , 
                81.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                80.0
                , 
                "Triangle"
                , 
                26.0
                , 
                80.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadParenthesis
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Inside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                114.0
                , 
                "Grancassa"
                , 
                25.0
                , 
                43.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                115.0
                , 
                "Piatti"
                , 
                18.0
                , 
                49.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                116.0
                , 
                "Piatti"
                , 
                24.0
                , 
                49.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                69.0
                , 
                "Cabasa"
                , 
                23.0
                , 
                69.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                117.0
                , 
                "Cabasa"
                , 
                22.0
                , 
                69.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                85.0
                , 
                "Castanets"
                , 
                21.0
                , 
                85.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                75.0
                , 
                "Claves"
                , 
                20.0
                , 
                75.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                70.0
                , 
                "Left Maraca"
                , 
                -12.0
                , 
                70.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                118.0
                , 
                "Left Maraca"
                , 
                -13.0
                , 
                70.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                119.0
                , 
                "Right Maraca"
                , 
                -14.0
                , 
                70.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                120.0
                , 
                "Right Maraca"
                , 
                -15.0
                , 
                70.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                82.0
                , 
                "Shaker"
                , 
                -23.0
                , 
                82.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                122.0
                , 
                "Shaker"
                , 
                -24.0
                , 
                82.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                84.0
                , 
                "Bell Tree"
                , 
                -18.0
                , 
                53.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                123.0
                , 
                "Bell Tree"
                , 
                -19.0
                , 
                53.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.StringsUpBow
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                83.0
                , 
                "Jingle Bell"
                , 
                -20.0
                , 
                53.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                83.0
                , 
                "Tinkle Bell"
                , 
                -20.0
                , 
                53.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                124.0
                , 
                "Golpe"
                , 
                -21.0
                , 
                62.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.GuitarGolpe
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Below
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                125.0
                , 
                "Golpe"
                , 
                -22.0
                , 
                62.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadNull
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.GuitarGolpe
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Above
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                39.0
                , 
                "Hand Clap"
                , 
                3.0
                , 
                39.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                40.0
                , 
                "Electric Snare"
                , 
                3.0
                , 
                40.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                31.0
                , 
                "Sticks"
                , 
                3.0
                , 
                40.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadSlashedBlack2
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadSlashedBlack2
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadSlashedBlack2
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                41.0
                , 
                "Very Low Floor Tom"
                , 
                5.0
                , 
                41.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadHalf
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadWhole
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                59.0
                , 
                "Ride Cymbal 2"
                , 
                2.0
                , 
                59.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.PictEdgeOfCymbal
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Above
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                126.0
                , 
                "Ride Cymbal 2"
                , 
                2.0
                , 
                59.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                127.0
                , 
                "Ride Cymbal 2"
                , 
                2.0
                , 
                59.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhite
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                29.0
                , 
                "Ride Cymbal 2"
                , 
                2.0
                , 
                59.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.ArticStaccatoAbove
                , 
                com.omnifret.gplayer.model.TechniqueSymbolPlacement.Outside
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                30.0
                , 
                "Reverse Cymbal"
                , 
                -3.0
                , 
                49.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                33.0
                , 
                "Metronome"
                , 
                3.0
                , 
                37.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadXBlack
            
            ), 
            
            com.omnifret.gplayer.model.InstrumentArticulation.create(
                34.0
                , 
                "Metronome"
                , 
                3.0
                , 
                38.0
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
                , 
                com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack
            
            ))
        .map(fun(articulation: com.omnifret.gplayer.model.InstrumentArticulation): com.omnifret.gplayer.core.IArrayTuple<String, com.omnifret.gplayer.model.InstrumentArticulation>{
            return com.omnifret.gplayer.core.ArrayTuple<String, com.omnifret.gplayer.model.InstrumentArticulation>(articulation.uniqueId, articulation)
        }
        ))
        
        
        @kotlin.jvm.JvmStatic
        private var _instrumentArticulationNames: com.omnifret.gplayer.collections.Map<String, String> = com.omnifret.gplayer.collections.Map<String, String>(com.omnifret.gplayer.collections.SimpleIterable<com.omnifret.gplayer.core.IArrayTuple<String, String>>(
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (hit)", "Snare.38"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (side stick)", "Snare.37"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (rim shot)", "Snare.91"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Hi-Hat (closed)", "Charley.42"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Hi-Hat (half)", "Charley.92"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Hi-Hat (open)", "Charley.46"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Pedal Hi-Hat (hit)", "Charley.44"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Kick (hit)", "Acoustic Kick Drum.35"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Kick (hit) 2", "Kick Drum.36"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("High Floor Tom (hit)", "Tom Very High.50"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("High Tom (hit)", "Tom High.48"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Mid Tom (hit)", "Tom Medium.47"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Low Tom (hit)", "Tom Low.45"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Very Low Tom (hit)", "Tom Very Low.43"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (edge)", "Ride.93"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (middle)", "Ride.51"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (bell)", "Ride.53"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (choke)", "Ride.94"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Splash (hit)", "Splash.55"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Splash (choke)", "Splash.95"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("China (hit)", "China.52"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("China (choke)", "China.96"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Crash high (hit)", "Crash High.49"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Crash high (choke)", "Crash High.97"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Crash medium (hit)", "Crash Medium.57"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Crash medium (choke)", "Crash Medium.98"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell low (hit)", "Cowbell Low.99"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell low (tip)", "Cowbell Low.100"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell medium (hit)", "Cowbell Medium.56"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell medium (tip)", "Cowbell Medium.101"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell high (hit)", "Cowbell High.102"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cowbell high (tip)", "Cowbell High.103"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Woodblock low (hit)", "Woodblock Low.77"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Woodblock high (hit)", "Woodblock High.76"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo High (hit)", "Bongo High.60"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo High (mute)", "Bongo High.104"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo High (slap)", "Bongo High.105"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo Low (hit)", "Bongo Low.61"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo Low (mute)", "Bongo Low.106"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bongo Low (slap)", "Bongo Low.107"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Timbale low (hit)", "Timbale Low.66"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Timbale high (hit)", "Timbale High.65"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Agogo low (hit)", "Agogo Low.68"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Agogo high (hit)", "Agogo High.67"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga low (hit)", "Conga Low.64"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga low (slap)", "Conga Low.108"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga low (mute)", "Conga Low.109"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga high (hit)", "Conga High.63"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga high (slap)", "Conga High.110"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Conga high (mute)", "Conga High.62"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Whistle low (hit)", "Whistle Low.72"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Whistle high (hit)", "Whistle High.71"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Guiro (hit)", "Guiro.73"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Guiro (scrap-return)", "Guiro.74"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Surdo (hit)", "Surdo.86"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Surdo (mute)", "Surdo.87"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Tambourine (hit)", "Tambourine.54"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Tambourine (return)", "Tambourine.111"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Tambourine (roll)", "Tambourine.112"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Tambourine (hand)", "Tambourine.113"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cuica (open)", "Cuica.79"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cuica (mute)", "Cuica.78"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Vibraslap (hit)", "Vibraslap.58"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Triangle (hit)", "Triangle.81"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Triangle (mute)", "Triangle.80"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Grancassa (hit)", "Grancassa.114"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Piatti (hit)", "Piatti.115"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Piatti (hand)", "Piatti.116"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cabasa (hit)", "Cabasa.69"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Cabasa (return)", "Cabasa.117"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Castanets (hit)", "Castanets.85"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Claves (hit)", "Claves.75"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Left Maraca (hit)", "Left Maraca.70"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Left Maraca (return)", "Left Maraca.118"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Right Maraca (hit)", "Right Maraca.119"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Right Maraca (return)", "Right Maraca.120"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Shaker (hit)", "Shaker.82"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Shaker (return)", "Shaker.122"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bell Tree (hit)", "Bell Tree.84"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Bell Tree (return)", "Bell Tree.123"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Jingle Bell (hit)", "Jingle Bell.83"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Tinkle Bell (hit)", "Tinkle Bell.83"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Golpe (thumb)", "Golpe.124"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Golpe (finger)", "Golpe.125"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand Clap (hit)", "Hand Clap.39"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Electric Snare (hit)", "Electric Snare.40"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (side stick) 2", "Sticks.31"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Low Floor Tom (hit)", "Very Low Floor Tom.41"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (edge) 2", "Ride Cymbal 2.59"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (middle) 2", "Ride Cymbal 2.126"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (bell) 2", "Ride Cymbal 2.127"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Ride (choke) 2", "Ride Cymbal 2.29"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Reverse Cymbal (hit)", "Reverse Cymbal.30"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Metronome (hit)", "Metronome.33"), 
            
            com.omnifret.gplayer.core.ArrayTuple<String, String>("Metronome (bell)", "Metronome.34"))
        )
        
        @kotlin.jvm.JvmStatic
        private var _gp6ElementAndVariationToArticulation: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.collections.DoubleList> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.collections.DoubleList>(
            
            com.omnifret.gplayer.collections.DoubleList(
                35.0, 35.0, 35.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                38.0, 91.0, 37.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                99.0, 100.0, 99.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                56.0, 100.0, 56.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                102.0, 103.0, 102.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                43.0, 43.0, 43.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                45.0, 45.0, 45.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                47.0, 47.0, 47.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                48.0, 48.0, 48.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                50.0, 50.0, 50.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                42.0, 92.0, 46.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                44.0, 44.0, 44.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                57.0, 98.0, 57.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                49.0, 97.0, 49.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                55.0, 95.0, 55.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                51.0, 93.0, 127.0)
            , 
            
            com.omnifret.gplayer.collections.DoubleList(
                52.0, 96.0, 52.0)
        )
        
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun articulationFromElementVariation(element: Double, variation: Double): Double{
            var paramvariation = variation
            if (element < com.omnifret.gplayer.model.PercussionMapper._gp6ElementAndVariationToArticulation.length)
            {
                if (paramvariation >= com.omnifret.gplayer.model.PercussionMapper._gp6ElementAndVariationToArticulation.length)
                {
                    paramvariation = 0.0
                }
                return com.omnifret.gplayer.model.PercussionMapper._gp6ElementAndVariationToArticulation[(element).toInt()][(paramvariation).toInt()]
            }
            return 38.0
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getArticulationName(n: com.omnifret.gplayer.model.Note): String{
            var articulation: com.omnifret.gplayer.model.InstrumentArticulation? = com.omnifret.gplayer.model.PercussionMapper.getArticulation(n)
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(articulation)))
            {
                var uniqueId: String = articulation!!.uniqueId
                for ((name, value) in com.omnifret.gplayer.model.PercussionMapper.instrumentArticulationNames)
                {
                    if (value == uniqueId)
                    {
                        return name
                    }
                }
            }
            else 
            {
                var uniqueId: String = """.${(n.percussionArticulation).toTemplate()}"""
                for ((name, value) in com.omnifret.gplayer.model.PercussionMapper.instrumentArticulationNames)
                {
                    if (value.endsWith(uniqueId))
                    {
                        return name
                    }
                }
            }
            return "Snare (hit)"
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getArticulation(n: com.omnifret.gplayer.model.Note): com.omnifret.gplayer.model.InstrumentArticulation?{
            var articulationIndex: Double = n.percussionArticulation
            if (articulationIndex < 0)
            {
                return null
            }
            var trackArticulations: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.InstrumentArticulation> = n.beat.voice.bar.staff.track.percussionArticulations
            if (articulationIndex < trackArticulations.length)
            {
                return trackArticulations[(articulationIndex).toInt()]
            }
            return com.omnifret.gplayer.model.PercussionMapper.getArticulationById(articulationIndex)
        }
        
        @kotlin.jvm.JvmStatic
        private var _instrumentArticulationsById: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>? = null
        
        @kotlin.jvm.JvmStatic
        private fun _initArticulationsById(): com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>{
            var lookup: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>? = com.omnifret.gplayer.model.PercussionMapper._instrumentArticulationsById
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(lookup)))
            {
                lookup = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>()
                for (articulation in com.omnifret.gplayer.model.PercussionMapper.instrumentArticulations.values())
                {
                    lookup!!.set(articulation.id, articulation)
                }
                com.omnifret.gplayer.model.PercussionMapper._instrumentArticulationsById = lookup!!
            }
            return lookup!!
        }
        
        @kotlin.jvm.JvmStatic
        public fun instrumentArticulationIds(): kotlin.collections.Iterable<Double>{
            var lookup: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation> = com.omnifret.gplayer.model.PercussionMapper._initArticulationsById()
            return lookup.keys()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getArticulationById(id: Double): com.omnifret.gplayer.model.InstrumentArticulation?{
            var lookup: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation> = com.omnifret.gplayer.model.PercussionMapper._initArticulationsById()
            return if(lookup.has(id))  lookup.get(id)!! else null
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getElementAndVariation(n: com.omnifret.gplayer.model.Note): com.omnifret.gplayer.collections.DoubleList{
            var articulation: com.omnifret.gplayer.model.InstrumentArticulation? = com.omnifret.gplayer.model.PercussionMapper.getArticulation(n)
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(articulation)))
            {
                return com.omnifret.gplayer.collections.DoubleList(
                    -1.0, -1.0)
                
            }
            if (true) {
                var element: Double = 0.0
                
                while(element < com.omnifret.gplayer.model.PercussionMapper._gp6ElementAndVariationToArticulation.length){
                    var variations: com.omnifret.gplayer.collections.DoubleList = com.omnifret.gplayer.model.PercussionMapper._gp6ElementAndVariationToArticulation[(element).toInt()]
                    if (true) {
                        var variation: Double = 0.0
                        
                        while(variation < variations.length){
                            var gp6Articulation: com.omnifret.gplayer.model.InstrumentArticulation? = com.omnifret.gplayer.model.PercussionMapper.getArticulationById(variations[(variation).toInt()])
                            if (gp6Articulation?.outputMidiNumber == articulation!!.outputMidiNumber)
                            {
                                return com.omnifret.gplayer.collections.DoubleList(
                                    element, variation)
                                
                            }
                            variation++
                        }
                    }
                    element++
                }
            }
            return com.omnifret.gplayer.collections.DoubleList(
                -1.0, -1.0)
            
        }
        
        @kotlin.jvm.JvmStatic
        public var instrumentArticulationNames: com.omnifret.gplayer.collections.Map<String, String> = com.omnifret.gplayer.model.PercussionMapper._mergeNames(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.collections.Map<String, String>>(
            com.omnifret.gplayer.collections.Map<String, String>(com.omnifret.gplayer.collections.SimpleIterable<com.omnifret.gplayer.core.IArrayTuple<String, String>>(
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand (hit)", "Bongo Low.61"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Tinkle Bell (hat)", "Tingle Bell.83"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Cymbal (hit)", "Reverse Cymbal.30"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (side stick) 3", "Snare.37"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (hit) 2", "Snare.38"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Snare (hit) 3", "Snare.40"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Agogo tow (hit)", "Agogo Low.68"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Triangle (rnute)", "Triangle.80"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand (mute)", "Bongo High.104"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand (slap)", "Bongo High.105"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand (mute) 2", "Bongo Low.106"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Hand (slap) 2", "Bongo Low.107"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Piatti (hat)", "Piatti.115"), 
                
                com.omnifret.gplayer.core.ArrayTuple<String, String>("Bell Tee (return)", "Bell Tree.123"))
            ), com.omnifret.gplayer.model.PercussionMapper._instrumentArticulationNames)
        )
        
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _mergeNames(maps: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.collections.Map<String, String>>): com.omnifret.gplayer.collections.Map<String, String>{
            var merged: com.omnifret.gplayer.collections.Map<String, String> = com.omnifret.gplayer.collections.Map<String, String>(maps[(0).toInt()])
            if (true) {
                var i: Double = 1.0
                
                while(i < maps.length){
                    for ((k, v) in maps[(i).toInt()])
                    {
                        merged.set(k, v)
                    }
                    i++
                }
            }
            return merged
        }
        
        @kotlin.jvm.JvmStatic
        private var _articulationsByOutputNumber: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>? = null
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun tryMatchKnownArticulation(articulation: com.omnifret.gplayer.model.InstrumentArticulation): Double{
            var articulationsByOutputNumber: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>? = com.omnifret.gplayer.model.PercussionMapper._articulationsByOutputNumber
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(articulationsByOutputNumber)))
            {
                articulationsByOutputNumber = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.model.InstrumentArticulation>()
                for (a in com.omnifret.gplayer.model.PercussionMapper.instrumentArticulations.values())
                {
                    if (!articulationsByOutputNumber!!.has(a.outputMidiNumber))
                    {
                        articulationsByOutputNumber!!.set(a.outputMidiNumber, a)
                    }
                }
                com.omnifret.gplayer.model.PercussionMapper._articulationsByOutputNumber = articulationsByOutputNumber!!
            }
            return if(articulationsByOutputNumber!!.has(articulation.outputMidiNumber))  articulationsByOutputNumber!!.get(articulation.outputMidiNumber)!!.id else -1.0
        }
        
        @kotlin.jvm.JvmStatic
        private var _instrumentArticulationsByUniqueId: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.model.InstrumentArticulation>? = null
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getInstrumentArticulationByUniqueId(uniqueId: String): com.omnifret.gplayer.model.InstrumentArticulation?{
            var lookup: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.model.InstrumentArticulation>? = com.omnifret.gplayer.model.PercussionMapper._instrumentArticulationsByUniqueId
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(lookup)))
            {
                lookup = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.model.InstrumentArticulation>()
                for (articulation in com.omnifret.gplayer.model.PercussionMapper.instrumentArticulations.values())
                {
                    lookup!!.set(articulation.uniqueId, articulation)
                }
                com.omnifret.gplayer.model.PercussionMapper._instrumentArticulationsByUniqueId = lookup!!
            }
            return if(lookup!!.has(uniqueId))  lookup!!.get(uniqueId)!! else null
        }
        
    }
    public constructor()
}

