// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * This public class stores the midi specific information of a track needed
 * for playback.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class PlaybackInformation
{
    /**
     * Gets or sets the volume (0-16)
     */
    public var volume: Double = 15.0
    
    
    /**
     * Gets or sets the balance (0-16; 8=center)
     */
    public var balance: Double = 8.0
    
    
    /**
     * Gets or sets the midi port to use.
     */
    public var port: Double = 1.0
    
    
    /**
     * Gets or sets the midi program to use.
     */
    public var program: Double = 0.0
    
    
    /**
     * The midi bank to use.
     */
    public var bank: Double = 0.0
    
    
    /**
     * Gets or sets the primary channel for all normal midi events.
     */
    public var primaryChannel: Double = 0.0
    
    
    /**
     * Gets or sets the secondary channel for special midi events.
     */
    public var secondaryChannel: Double = 0.0
    
    
    /**
     * Gets or sets whether the track is muted.
     */
    public var isMute: Boolean = false
    
    
    /**
     * Gets or sets whether the track is playing alone.
     */
    public var isSolo: Boolean = false
    
    
    public constructor()
}

