// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Lists all Rasgueado types.
 */
public enum class Rasgueado(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    None(0),
    Ii(1),
    Mi(2),
    MiiTriplet(3),
    MiiAnapaest(4),
    PmpTriplet(5),
    PmpAnapaest(6),
    PeiTriplet(7),
    PeiAnapaest(8),
    PaiTriplet(9),
    PaiAnapaest(10),
    AmiTriplet(11),
    AmiAnapaest(12),
    Ppp(13),
    Amii(14),
    Amip(15),
    Eami(16),
    Eamii(17),
    Peami(18);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<Rasgueado>{
        public override val values = arrayOf(None, Ii, Mi, MiiTriplet, MiiAnapaest, PmpTriplet, PmpAnapaest, PeiTriplet, PeiAnapaest, PaiTriplet, PaiAnapaest, AmiTriplet, AmiAnapaest, Ppp, Amii, Amip, Eami, Eamii, Peami) 
        public override fun fromValue(v:Double): Rasgueado{
            return when(v.toInt()){
                None.value -> None
                Ii.value -> Ii
                Mi.value -> Mi
                MiiTriplet.value -> MiiTriplet
                MiiAnapaest.value -> MiiAnapaest
                PmpTriplet.value -> PmpTriplet
                PmpAnapaest.value -> PmpAnapaest
                PeiTriplet.value -> PeiTriplet
                PeiAnapaest.value -> PeiAnapaest
                PaiTriplet.value -> PaiTriplet
                PaiAnapaest.value -> PaiAnapaest
                AmiTriplet.value -> AmiTriplet
                AmiAnapaest.value -> AmiAnapaest
                Ppp.value -> Ppp
                Amii.value -> Amii
                Amip.value -> Amip
                Eami.value -> Eami
                Eamii.value -> Eamii
                Peami.value -> Peami
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

