// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * This public enumeration lists all feels of triplets.
 */
public enum class TripletFeel(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    /**
     * No triplet feel
     */
    NoTripletFeel(0),
    /**
     * Triplet 16th
     */
    Triplet16th(1),
    /**
     * Triplet 8th
     */
    Triplet8th(2),
    /**
     * Dotted 16th
     */
    Dotted16th(3),
    /**
     * Dotted 8th
     */
    Dotted8th(4),
    /**
     * Scottish 16th
     */
    Scottish16th(5),
    /**
     * Scottish 8th
     */
    Scottish8th(6);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<TripletFeel>{
        public override val values = arrayOf(NoTripletFeel, Triplet16th, Triplet8th, Dotted16th, Dotted8th, Scottish16th, Scottish8th) 
        public override fun fromValue(v:Double): TripletFeel{
            return when(v.toInt()){
                NoTripletFeel.value -> NoTripletFeel
                Triplet16th.value -> Triplet16th
                Triplet8th.value -> Triplet8th
                Dotted16th.value -> Dotted16th
                Dotted8th.value -> Dotted8th
                Scottish16th.value -> Scottish16th
                Scottish8th.value -> Scottish8th
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

