// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Represents a list of beats that are grouped within the same tuplet.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class TupletGroup
{
    private var _isEqualLengthTuplet: Boolean = true
    
    public var totalDuration: Double = 0.0
    
    
    /**
     * Gets or sets the list of beats contained in this group.
     */
    public var beats: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Beat> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Beat>(
    )
    
    
    
    /**
     * Gets or sets the voice this group belongs to.
     */
    public var voice: com.omnifret.gplayer.model.Voice
    
    /**
     * Gets a value indicating whether the tuplet group is fully filled.
     */
    public var isFull: Boolean = false
    
    
    public constructor(voice: com.omnifret.gplayer.model.Voice){
        this.voice = voice
    }
    
    /**
     */
    public fun check(beat: com.omnifret.gplayer.model.Beat): Boolean{
        if (this.beats.length == 0.0)
        {
            this.beats.push(beat)
            this.totalDuration += beat.playbackDuration
            return true
        }
        if (beat.graceType != com.omnifret.gplayer.model.GraceType.None)
        {
            return true
        }
        if (beat.voice != this.voice || this.isFull || beat.tupletNumerator != this.beats[(0).toInt()].tupletNumerator || beat.tupletDenominator != this.beats[(0).toInt()].tupletDenominator)
        {
            return false
        }
        if (beat.displayDuration != this.beats[(0).toInt()].displayDuration)
        {
            this._isEqualLengthTuplet = false
        }
        this.beats.push(beat)
        this.totalDuration += beat.displayDuration
        if (this._isEqualLengthTuplet)
        {
            if (this.beats.length == this.beats[(0).toInt()].tupletNumerator)
            {
                this.isFull = true
            }
        }
        else 
        {
            var factor: Double = (((this.beats[(0).toInt()].tupletNumerator / this.beats[(0).toInt()].tupletDenominator)).toInt() or 0).toDouble()
            for (potentialMatch in com.omnifret.gplayer.model.TupletGroup._allTicks)
            {
                if (this.totalDuration == potentialMatch * factor)
                {
                    this.isFull = true
                    break
                }
            }
        }
        return true
    }
    
    companion object{
        @kotlin.jvm.JvmStatic
        private val _halfTicks: Double = 1920.0
        
        @kotlin.jvm.JvmStatic
        private val _quarterTicks: Double = 960.0
        
        @kotlin.jvm.JvmStatic
        private val _eighthTicks: Double = 480.0
        
        @kotlin.jvm.JvmStatic
        private val _sixteenthTicks: Double = 240.0
        
        @kotlin.jvm.JvmStatic
        private val _thirtySecondTicks: Double = 120.0
        
        @kotlin.jvm.JvmStatic
        private val _sixtyFourthTicks: Double = 60.0
        
        @kotlin.jvm.JvmStatic
        private val _oneHundredTwentyEighthTicks: Double = 30.0
        
        @kotlin.jvm.JvmStatic
        private val _twoHundredFiftySixthTicks: Double = 15.0
        
        @kotlin.jvm.JvmStatic
        private var _allTicks: com.omnifret.gplayer.collections.DoubleList = com.omnifret.gplayer.collections.DoubleList(
            com.omnifret.gplayer.model.TupletGroup._halfTicks, 
            com.omnifret.gplayer.model.TupletGroup._quarterTicks, 
            com.omnifret.gplayer.model.TupletGroup._eighthTicks, 
            com.omnifret.gplayer.model.TupletGroup._sixteenthTicks, 
            com.omnifret.gplayer.model.TupletGroup._thirtySecondTicks, 
            com.omnifret.gplayer.model.TupletGroup._sixtyFourthTicks, 
            com.omnifret.gplayer.model.TupletGroup._oneHundredTwentyEighthTicks, 
            com.omnifret.gplayer.model.TupletGroup._twoHundredFiftySixthTicks)
        
        
    }
}

