// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.model
import com.omnifret.gplayer.core.*

/**
 * Lists all wah pedal modes.
 */
public enum class WahPedal(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    None(0),
    Open(1),
    Closed(2);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<WahPedal>{
        public override val values = arrayOf(None, Open, Closed) 
        public override fun fromValue(v:Double): WahPedal{
            return when(v.toInt()){
                None.value -> None
                Open.value -> Open
                Closed.value -> Closed
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

