// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.zip
import com.omnifret.gplayer.core.*

/**
 * This class contains constants used for deflation.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class DeflaterConstants
{
    companion object{
        @kotlin.jvm.JvmStatic
        public val maxWbits: Double = 15.0
        
        @kotlin.jvm.JvmStatic
        public var wsize: Double = (1 shl (com.omnifret.gplayer.zip.DeflaterConstants.maxWbits).toInt()).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public var wmask: Double = com.omnifret.gplayer.zip.DeflaterConstants.wsize - (1.0).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public val minMatch: Double = 3.0
        
        @kotlin.jvm.JvmStatic
        public val maxMatch: Double = 258.0
        
        @kotlin.jvm.JvmStatic
        public val defaultMemLevel: Double = 8.0
        
        @kotlin.jvm.JvmStatic
        public var pendingBufSize: Double = (1 shl ((com.omnifret.gplayer.zip.DeflaterConstants.defaultMemLevel + 8.0)).toInt()).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public var hashBits: Double = com.omnifret.gplayer.zip.DeflaterConstants.defaultMemLevel + 7.0
        
        
        @kotlin.jvm.JvmStatic
        public var hashSize: Double = (1 shl (com.omnifret.gplayer.zip.DeflaterConstants.hashBits).toInt()).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public var hashShift: Double = (com.omnifret.gplayer.zip.DeflaterConstants.hashBits + com.omnifret.gplayer.zip.DeflaterConstants.minMatch - (1.0).toDouble()) / com.omnifret.gplayer.zip.DeflaterConstants.minMatch
        
        
        @kotlin.jvm.JvmStatic
        public var hashMask: Double = com.omnifret.gplayer.zip.DeflaterConstants.hashSize - (1.0).toDouble()
        
        
        @kotlin.jvm.JvmStatic
        public var minLookahead: Double = com.omnifret.gplayer.zip.DeflaterConstants.maxMatch + com.omnifret.gplayer.zip.DeflaterConstants.minMatch + 1.0
        
        
        @kotlin.jvm.JvmStatic
        public var maxDist: Double = com.omnifret.gplayer.zip.DeflaterConstants.wsize - com.omnifret.gplayer.zip.DeflaterConstants.minLookahead
        
        
    }
    public constructor()
}

