// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.zip
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ZipWriter
{
    private var _data: com.omnifret.gplayer.io.IWriteable
    
    private var _centralDirectoryHeaders: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.zip.ZipCentralDirectoryHeader> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.zip.ZipCentralDirectoryHeader>(
    )
    
    
    private var _deflater: com.omnifret.gplayer.zip.Deflater = com.omnifret.gplayer.zip.Deflater()
    
    public constructor(`data`: com.omnifret.gplayer.io.IWriteable){
        this._data = `data`
    }
    
    /**
     */
    public fun writeEntry(entry: com.omnifret.gplayer.zip.ZipEntry): Unit{
        var compressionMode: Double = com.omnifret.gplayer.zip.ZipEntry.CompressionMethodDeflate
        var compressedData: com.omnifret.gplayer.io.ByteBuffer = com.omnifret.gplayer.io.ByteBuffer.empty()
        var crc32: Double = this._compress(compressedData, entry.`data`, compressionMode)
        var compressedDataArray: com.omnifret.gplayer.core.ecmaScript.Uint8Array = compressedData.toArray()
        var directoryHeader: com.omnifret.gplayer.zip.ZipCentralDirectoryHeader = com.omnifret.gplayer.zip.ZipCentralDirectoryHeader(entry, crc32, this._data.bytesWritten, compressionMode, compressedData.length)
        this._centralDirectoryHeaders.push(directoryHeader)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, com.omnifret.gplayer.zip.ZipEntry.LocalFileHeaderSignature)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, 10.0)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, 2048.0)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, compressionMode)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, crc32)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, compressedDataArray.length)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, entry.`data`.length)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, entry.fullName.length.toDouble())
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        var fileNameBuffer: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.io.IOHelper.stringToBytes(entry.fullName)
        this._data.write(fileNameBuffer, 0.0, fileNameBuffer.length)
        this._data.write(compressedDataArray, 0.0, compressedDataArray.length)
    }
    
    /**
     */
    private fun _compress(output: com.omnifret.gplayer.io.IWriteable, `data`: com.omnifret.gplayer.core.ecmaScript.Uint8Array, compressionMode: Double): Double{
        if (compressionMode != com.omnifret.gplayer.zip.ZipEntry.CompressionMethodDeflate)
        {
            var crc: com.omnifret.gplayer.zip.Crc32 = com.omnifret.gplayer.zip.Crc32()
            crc.update(`data`, 0.0, `data`.length)
            output.write(`data`, 0.0, `data`.length)
            return crc.value
        }
        var buffer: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(512.0)
        this._deflater.reset()
        this._deflater.setInput(`data`, 0.0, `data`.length)
        while (!this._deflater.isNeedingInput)
        {
            var len: Double = this._deflater.deflate(buffer, 0.0, buffer.length)
            if (len <= 0)
            {
                break
            }
            output.write(buffer, 0.0, len)
        }
        this._deflater.finish()
        while (!this._deflater.isFinished)
        {
            var len: Double = this._deflater.deflate(buffer, 0.0, buffer.length)
            if (len <= 0)
            {
                break
            }
            output.write(buffer, 0.0, len)
        }
        return this._deflater.inputCrc
    }
    
    public fun end(): Unit{
        var startOfCentralDirectory: Double = this._data.bytesWritten
        for (header in this._centralDirectoryHeaders)
        {
            this._writeCentralDirectoryHeader(header)
        }
        var endOfCentralDirectory: Double = this._data.bytesWritten
        this._writeEndOfCentralDirectoryRecord(startOfCentralDirectory, endOfCentralDirectory)
    }
    
    /**
     */
    private fun _writeEndOfCentralDirectoryRecord(startOfCentralDirectory: Double, endOfCentralDirectory: Double): Unit{
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, com.omnifret.gplayer.zip.ZipEntry.EndOfCentralDirSignature)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, this._centralDirectoryHeaders.length)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, this._centralDirectoryHeaders.length)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, endOfCentralDirectory - startOfCentralDirectory)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, startOfCentralDirectory)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
    }
    
    /**
     */
    private fun _writeCentralDirectoryHeader(header: com.omnifret.gplayer.zip.ZipCentralDirectoryHeader): Unit{
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, com.omnifret.gplayer.zip.ZipEntry.CentralFileHeaderSignature)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, 10.0)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, 10.0)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, 2048.0)
        com.omnifret.gplayer.io.IOHelper.writeUInt16LE(this._data, header.compressionMode)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, header.crc32)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, header.compressedSize)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, header.entry.`data`.length)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, header.entry.fullName.length.toDouble())
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt16LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, 0.0)
        com.omnifret.gplayer.io.IOHelper.writeInt32LE(this._data, header.localHeaderOffset)
        var fileNameBuffer: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.io.IOHelper.stringToBytes(header.entry.fullName)
        this._data.write(fileNameBuffer, 0.0, fileNameBuffer.length)
    }
    
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ZipCentralDirectoryHeader
{
    public var entry: com.omnifret.gplayer.zip.ZipEntry
    
    public var localHeaderOffset: Double
    
    public var compressedSize: Double
    
    public var crc32: Double
    
    public var compressionMode: Double
    
    public constructor(entry: com.omnifret.gplayer.zip.ZipEntry, crc32: Double, localHeaderOffset: Double, compressionMode: Double, compressedSize: Double){
        this.entry = entry
        this.crc32 = crc32
        this.localHeaderOffset = localHeaderOffset
        this.compressionMode = compressionMode
        this.compressedSize = compressedSize
    }
    
}

