// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.synth.synthesis
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class Envelope
{
    public var delay: Double = 0.0
    
    
    public var attack: Double = 0.0
    
    
    public var hold: Double = 0.0
    
    
    public var decay: Double = 0.0
    
    
    public var sustain: Double = 0.0
    
    
    public var release: Double = 0.0
    
    
    public var keynumToHold: Double = 0.0
    
    
    public var keynumToDecay: Double = 0.0
    
    
    public constructor(other: com.omnifret.gplayer.synth.synthesis.Envelope? = null){
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(other)))
        {
            this.delay = other!!.delay
            this.attack = other!!.attack
            this.hold = other!!.hold
            this.decay = other!!.decay
            this.sustain = other!!.sustain
            this.release = other!!.release
            this.keynumToHold = other!!.keynumToHold
            this.keynumToDecay = other!!.keynumToDecay
        }
    }
    
    public fun clear(): Unit{
        this.delay = 0.0
        this.attack = 0.0
        this.hold = 0.0
        this.decay = 0.0
        this.sustain = 0.0
        this.release = 0.0
        this.keynumToHold = 0.0
        this.keynumToDecay = 0.0
    }
    
    /**
     */
    public fun envToSecs(sustainIsGain: Boolean): Unit{
        this.delay = if(this.delay < -11950.0)  0.0 else com.omnifret.gplayer.synth.SynthHelper.timecents2Secs(this.delay)
        this.attack = if(this.attack < -11950.0)  0.0 else com.omnifret.gplayer.synth.SynthHelper.timecents2Secs(this.attack)
        this.release = if(this.release < -11950.0)  0.0 else com.omnifret.gplayer.synth.SynthHelper.timecents2Secs(this.release)
        if (this.keynumToHold == 0.0)
        {
            this.hold = if(this.hold < -11950.0)  0.0 else com.omnifret.gplayer.synth.SynthHelper.timecents2Secs(this.hold)
        }
        if (this.keynumToDecay == 0.0)
        {
            this.decay = if(this.decay < -11950.0)  0.0 else com.omnifret.gplayer.synth.SynthHelper.timecents2Secs(this.decay)
        }
        if (this.sustain < 0)
        {
            this.sustain = 0.0
        }
        else if (sustainIsGain)
        {
            this.sustain = com.omnifret.gplayer.synth.SynthHelper.decibelsToGain(-this.sustain / (10.0).toDouble())
        }
        else 
        {
            this.sustain = (1.0).toDouble() - this.sustain / (1000.0).toDouble()
        }
    }
    
}

