// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class BarNumberGlyph: com.omnifret.gplayer.rendering.glyphs.Glyph
{
    private var _number: String
    
    public constructor(x: Double, y: Double, num: Double)
        : super(x, y){
        this._number = """${(num).toTemplate()}  """
    }
    
    public override fun doLayout(): Unit{
        this.renderer.scoreRenderer.canvas!!.font = this.renderer.resources.elementFonts.get(com.omnifret.gplayer.NotationElement.BarNumber)!!
        var size: com.omnifret.gplayer.platform.MeasuredText = this.renderer.scoreRenderer.canvas!!.measureText(this._number)
        this.width = size.width
        this.height = size.height
        this.y -= this.height
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        if (!this.renderer.staff!!.isFirstInSystem)
        {
            return
        }
        (com.omnifret.gplayer.rendering.utils.ElementStyleHelper.bar(canvas, ((this.renderer as com.omnifret.gplayer.rendering.LineBarRenderer)).barNumberBarSubElement, this.renderer.bar, true))
        .use {
            var res: com.omnifret.gplayer.RenderingResources = this.renderer.resources
            var baseline: com.omnifret.gplayer.platform.TextBaseline = canvas.textBaseline
            canvas.font = res.elementFonts.get(com.omnifret.gplayer.NotationElement.BarNumber)!!
            canvas.textBaseline = com.omnifret.gplayer.platform.TextBaseline.Top
            canvas.fillText(this._number, cx + this.x, cy + this.y)
            canvas.textBaseline = baseline
        }
    }
    
}

