// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal open class BeatGlyphBase: com.omnifret.gplayer.rendering.glyphs.GlyphGroup
{
    private var _effectGlyphs: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph>(
    )
    
    
    private var _normalGlyphs: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.Glyph>(
    )
    
    
    public lateinit var container: com.omnifret.gplayer.rendering.glyphs.BeatContainerGlyph
    
    public var computedWidth: Double = 0.0
    
    
    public constructor()
        : super(0.0, 0.0)
    public override fun doLayout(): Unit{
        var w: Double = 0.0
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.glyphs)))
        {
            if (true) {
                var i: Double = 0.0
                var j: Double = this.glyphs!!.length
                
                while(i < j){
                    var g: com.omnifret.gplayer.rendering.glyphs.Glyph = this.glyphs!![(i).toInt()]
                    g.x = w
                    g.renderer = this.renderer
                    g.doLayout()
                    w += g.width
                    i++
                }
            }
        }
        this.width = w
        this.computedWidth = w
    }
    
    /**
     */
    protected fun noteLoop(action: ((arg1: com.omnifret.gplayer.model.Note) -> Unit)): Unit{
        if (true) {
            var i: Double = this.container.beat.notes.length - (1.0).toDouble()
            
            while(i >= 0){
                action(this.container.beat.notes[(i).toInt()])
                i--
            }
        }
    }
    
    /**
     */
    public fun addEffect(g: com.omnifret.gplayer.rendering.glyphs.Glyph): Unit{
        super.addGlyph(g)
        this._effectGlyphs.push(g)
    }
    
    /**
     */
    public fun addNormal(g: com.omnifret.gplayer.rendering.glyphs.Glyph): Unit{
        super.addGlyph(g)
        this._normalGlyphs.push(g)
    }
    
    protected open val effectElement: com.omnifret.gplayer.model.BeatSubElement?
    get(){
        return null
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        this._paintEffects(cx, cy, canvas)
        this._paintNormal(cx, cy, canvas)
    }
    
    /**
     */
    private fun _paintNormal(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        for (g in this._normalGlyphs)
        {
            g.paint(cx + this.x, cy + this.y, canvas)
        }
    }
    
    /**
     */
    private fun _paintEffects(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        (if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.effectElement)))  com.omnifret.gplayer.rendering.utils.ElementStyleHelper.beat(canvas, this.effectElement!!, this.container.beat) else null)
        .use {
            for (g in this._effectGlyphs)
            {
                g.paint(cx + this.x, cy + this.y, canvas)
            }
        }
    }
    
}

