// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal abstract class BeatOnNoteGlyphBase: com.omnifret.gplayer.rendering.glyphs.BeatGlyphBase
{
    public var onTimeX: Double = 0.0
    
    
    public var middleX: Double = 0.0
    
    
    public var stemX: Double = 0.0
    
    
    /**
     */
    public abstract fun buildBoundingsLookup(_beatBounds: com.omnifret.gplayer.rendering.utils.BeatBounds, _cx: Double, _cy: Double): Unit
    
    /**
     */
    public abstract fun getNoteX(note: com.omnifret.gplayer.model.Note, requestedPosition: com.omnifret.gplayer.rendering.NoteXPosition): Double
    
    /**
     */
    public abstract fun getNoteY(note: com.omnifret.gplayer.model.Note, requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double
    
    /**
     */
    public abstract fun getRestY(requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double
    
    /**
     */
    public abstract fun getHighestNoteY(requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double
    
    /**
     */
    public abstract fun getLowestNoteY(requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double
    
    public constructor()
        : super()
}

