// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class DiamondNoteHeadGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase
{
    public constructor(x: Double, y: Double, duration: com.omnifret.gplayer.model.Duration, isGrace: Boolean)
        : super(x, y, isGrace, com.omnifret.gplayer.rendering.glyphs.DiamondNoteHeadGlyph._getSymbol(duration))
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _getSymbol(duration: com.omnifret.gplayer.model.Duration): com.omnifret.gplayer.model.MusicFontSymbol{
            when (duration)
            {
                com.omnifret.gplayer.model.Duration.QuadrupleWhole, com.omnifret.gplayer.model.Duration.DoubleWhole, com.omnifret.gplayer.model.Duration.Whole, com.omnifret.gplayer.model.Duration.Half -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondWhiteWide
                }
                else -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.NoteheadDiamondBlackWide
                }
            }
        }
        
    }
}

