// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class FadeGlyph: com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph
{
    public constructor(type: com.omnifret.gplayer.model.FadeType)
        : super(0.0, 0.0, 1.0, com.omnifret.gplayer.rendering.glyphs.FadeGlyph._getSymbol(type)){
        this.center = true
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        super.paint(cx, cy + this.height, canvas)
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _getSymbol(type: com.omnifret.gplayer.model.FadeType): com.omnifret.gplayer.model.MusicFontSymbol{
            when (type)
            {
                com.omnifret.gplayer.model.FadeType.FadeIn -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.GuitarFadeIn
                }
                com.omnifret.gplayer.model.FadeType.FadeOut -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.GuitarFadeOut
                }
                com.omnifret.gplayer.model.FadeType.VolumeSwell -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.GuitarVolumeSwell
                }
                else -> { }
            }
            return com.omnifret.gplayer.model.MusicFontSymbol.None
        }
        
    }
}

