// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class FermataGlyph: com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph
{
    public constructor(x: Double, y: Double, fermata: com.omnifret.gplayer.model.FermataType)
        : super(x, y, 1.0, com.omnifret.gplayer.rendering.glyphs.FermataGlyph._getSymbol(fermata))
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        super.paint(cx - this.width / (2.0).toDouble(), cy + this.height, canvas)
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _getSymbol(accentuation: com.omnifret.gplayer.model.FermataType): com.omnifret.gplayer.model.MusicFontSymbol{
            when (accentuation)
            {
                com.omnifret.gplayer.model.FermataType.Short -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.FermataShortAbove
                }
                com.omnifret.gplayer.model.FermataType.Medium -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.FermataAbove
                }
                com.omnifret.gplayer.model.FermataType.Long -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.FermataLongAbove
                }
                else -> 
                {
                    return com.omnifret.gplayer.model.MusicFontSymbol.None
                }
            }
        }
        
    }
}

