// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class RepeatCountGlyph: com.omnifret.gplayer.rendering.glyphs.Glyph
{
    private var _count: Double = 0.0
    
    public constructor(x: Double, y: Double, count: Double)
        : super(x, y){
        this._count = 0.0
        this._count = count
    }
    
    public override fun doLayout(): Unit{
        this.renderer.scoreRenderer.canvas!!.font = this.renderer.resources.elementFonts.get(com.omnifret.gplayer.NotationElement.RepeatCount)!!
        var size: com.omnifret.gplayer.platform.MeasuredText = this.renderer.scoreRenderer.canvas!!.measureText("""x${(this._count).toTemplate()}""")
        this.width = 0.0
        this.height = size.height
        this.y -= size.height
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        (com.omnifret.gplayer.rendering.utils.ElementStyleHelper.bar(canvas, ((this.renderer as com.omnifret.gplayer.rendering.LineBarRenderer)).repeatsBarSubElement, this.renderer.bar))
        .use {
            var res: com.omnifret.gplayer.RenderingResources = this.renderer.resources
            var oldAlign: com.omnifret.gplayer.platform.TextAlign = canvas.textAlign
            canvas.font = res.elementFonts.get(com.omnifret.gplayer.NotationElement.RepeatCount)!!
            canvas.textAlign = com.omnifret.gplayer.platform.TextAlign.Right
            var s: String = """x${(this._count).toTemplate()}"""
            var w: Double = canvas.measureText(s).width / (1.5).toDouble()
            canvas.fillText(s, cx + this.x - w, cy + this.y)
            canvas.textAlign = oldAlign
        }
    }
    
}

