// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreWhammyBarGlyph: com.omnifret.gplayer.rendering.glyphs.ScoreHelperNotesBaseGlyph, com.omnifret.gplayer.rendering.glyphs.ITieGlyph
{
    private var _container: com.omnifret.gplayer.rendering.ScoreBeatContainerGlyph
    
    private var _beat: com.omnifret.gplayer.model.Beat
    
    private var _endGlyph: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph? = null
    
    /**
     * Whether the tie is relevant for checking on bar renderer overflows.
     * If set, the tie bounds will be requested and the overflow is applied.
     */
    public override var checkForOverflow: Boolean = false
    
    
    public constructor(container: com.omnifret.gplayer.rendering.ScoreBeatContainerGlyph)
        : super(0.0, 0.0){
        this._container = container
        this._beat = container.beat
    }
    
    public val hasBoundingBox: Boolean
    get(){
        var endGlyph: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph? = this._endGlyph
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endGlyph)))
        {
            return false
        }
        return !!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endGlyph!!.minStepsNote)) && !!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endGlyph!!.maxStepsNote))
    }
    
    public override fun getBoundingBoxTop(): Double{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._endGlyph?.minStepsNote)))
        {
            return this._endGlyph!!.minStepsNote!!.glyph.getBoundingBoxTop()
        }
        return super.getBoundingBoxTop()
    }
    
    public override fun getBoundingBoxBottom(): Double{
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._endGlyph?.maxStepsNote)))
        {
            return this._endGlyph!!.maxStepsNote!!.glyph.getBoundingBoxBottom()
        }
        return super.getBoundingBoxBottom()
    }
    
    public fun doMultiVoiceLayout(): Unit{
        this._endGlyph?.doMultiVoiceLayout()
    }
    
    public override fun doLayout(): Unit{
        var sr: com.omnifret.gplayer.rendering.ScoreBarRenderer = (this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)
        var whammyMode: com.omnifret.gplayer.NotationMode = sr.settings.notation.notationMode
        when (this._beat.whammyBarType)
        {
            com.omnifret.gplayer.model.WhammyType.None, com.omnifret.gplayer.model.WhammyType.Custom, com.omnifret.gplayer.model.WhammyType.Hold -> 
            {
                return
            }
            com.omnifret.gplayer.model.WhammyType.Dive, com.omnifret.gplayer.model.WhammyType.PrediveDive -> 
            {
                var endGlyphs: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph("postwhammy", this._beat, false)
                this._endGlyph = endGlyphs
                endGlyphs.renderer = sr
                var lastWhammyPoint: com.omnifret.gplayer.model.BendPoint = this._beat.whammyBarPoints!![(this._beat.whammyBarPoints!!.length - (1.0).toDouble()).toInt()]
                for (note in this._beat.notes)
                {
                    if (!note.isTieOrigin)
                    {
                        endGlyphs.addGlyph(this._getBendNoteValue(note, lastWhammyPoint), lastWhammyPoint.value % 2.0 != 0.0, null)
                    }
                }
                endGlyphs.doLayout()
                this.addGlyph(endGlyphs)
            }
            com.omnifret.gplayer.model.WhammyType.Dip -> 
            {
                if (whammyMode == com.omnifret.gplayer.NotationMode.SongBook)
                {
                    return
                }
                else 
                {
                    var middleGlyphs: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph("middlewhammy", this._beat, false)
                    middleGlyphs.renderer = sr
                    if (sr.settings.notation.notationMode == com.omnifret.gplayer.NotationMode.GuitarPro)
                    {
                        var middleBendPoint: com.omnifret.gplayer.model.BendPoint = this._beat.whammyBarPoints!![(1).toInt()]
                        for (note in this._beat.notes)
                        {
                            middleGlyphs.addGlyph(this._getBendNoteValue(note, this._beat.whammyBarPoints!![(1).toInt()]), middleBendPoint.value % 2.0 != 0.0, null)
                        }
                    }
                    middleGlyphs.doLayout()
                    this.addGlyph(middleGlyphs)
                    var endGlyphs: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph("postwhammy", this._beat, false)
                    endGlyphs.renderer = sr
                    this._endGlyph = endGlyphs
                    if (sr.settings.notation.notationMode == com.omnifret.gplayer.NotationMode.GuitarPro)
                    {
                        var lastBendPoint: com.omnifret.gplayer.model.BendPoint = this._beat.whammyBarPoints!![(this._beat.whammyBarPoints!!.length - (1.0).toDouble()).toInt()]
                        for (note in this._beat.notes)
                        {
                            endGlyphs.addGlyph(this._getBendNoteValue(note, lastBendPoint), lastBendPoint.value % 2.0 != 0.0, null)
                        }
                    }
                    endGlyphs.doLayout()
                    this.addGlyph(endGlyphs)
                }
            }
            com.omnifret.gplayer.model.WhammyType.Predive -> 
            {
            }
            else -> { }
        }
        super.doLayout()
        this.width = this.width / (2.0).toDouble()
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        var beat: com.omnifret.gplayer.model.Beat = this._beat
        when (beat.whammyBarType)
        {
            com.omnifret.gplayer.model.WhammyType.None, com.omnifret.gplayer.model.WhammyType.Custom -> 
            {
                return
            }
            else -> { }
        }
        var whammyMode: com.omnifret.gplayer.NotationMode = this.renderer.settings.notation.notationMode
        var startNoteRenderer: com.omnifret.gplayer.rendering.ScoreBarRenderer = (this.renderer.scoreRenderer.layout!!.getRendererForBar(this.renderer.staff!!.staffId, beat.voice.bar)!! as com.omnifret.gplayer.rendering.ScoreBarRenderer)
        var _beatStyle: Disposable? = com.omnifret.gplayer.rendering.utils.ElementStyleHelper.beat(canvas, com.omnifret.gplayer.model.BeatSubElement.StandardNotationEffects, beat)
        _beatStyle.use {
            var startX: Double = cx + startNoteRenderer.x + startNoteRenderer.getBeatX(beat, com.omnifret.gplayer.rendering.BeatXPosition.MiddleNotes)
            var beatDirection: com.omnifret.gplayer.rendering.utils.BeamDirection = this.getTieDirection(beat, startNoteRenderer)
            var direction: com.omnifret.gplayer.rendering.utils.BeamDirection = if(this._beat.notes.length == 1.0)  beatDirection else com.omnifret.gplayer.rendering.utils.BeamDirection.Up
            var textalign: com.omnifret.gplayer.platform.TextAlign = canvas.textAlign
            var noteHeadHeight: Double = this.renderer.smuflMetrics.glyphHeights.get(com.omnifret.gplayer.model.MusicFontSymbol.NoteheadBlack)!!
            if (true) {
                var i: Double = 0.0
                
                while(i < beat.notes.length){
                    var note: com.omnifret.gplayer.model.Note = beat.notes[(i).toInt()]
                    var _noteStyle: Disposable? = com.omnifret.gplayer.rendering.utils.ElementStyleHelper.note(canvas, com.omnifret.gplayer.model.NoteSubElement.StandardNotationEffects, note)
                    _noteStyle.use {
                        var startY: Double = cy + startNoteRenderer.y
                        if (i > 0 && i >= (((this._beat.notes.length / (2.0).toDouble())).toInt() or 0))
                        {
                            direction = com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                        }
                        if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
                        {
                            startY += startNoteRenderer.getNoteY(note, com.omnifret.gplayer.rendering.NoteYPosition.Bottom)
                        }
                        else 
                        {
                            startY += startNoteRenderer.getNoteY(note, com.omnifret.gplayer.rendering.NoteYPosition.Top)
                        }
                        var endX: Double = cx + startNoteRenderer.x + startNoteRenderer.getBeatX(beat, com.omnifret.gplayer.rendering.BeatXPosition.EndBeat)
                        endX -= this.renderer.smuflMetrics.postNoteEffectPadding
                        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._endGlyph)))
                        {
                            var postBeatSize: Double = this._endGlyph!!.width - this._endGlyph!!.onTimeX
                            endX -= postBeatSize
                        }
                        var slurText: String = if(beat.whammyStyle == com.omnifret.gplayer.model.BendStyle.Gradual && i == 0.0)  "grad." else ""
                        var endNoteRenderer: com.omnifret.gplayer.rendering.ScoreBarRenderer? = null
                        if (note.isTieOrigin)
                        {
                            endNoteRenderer = (this.renderer.scoreRenderer.layout!!.getRendererForBar(this.renderer.staff!!.staffId, note.tieDestination!!.beat.voice.bar) as com.omnifret.gplayer.rendering.ScoreBarRenderer?)
                            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endNoteRenderer)) && endNoteRenderer!!.staff == startNoteRenderer.staff))
                            {
                                endX = cx + endNoteRenderer!!.x + endNoteRenderer!!.getBeatX(note.tieDestination!!.beat, com.omnifret.gplayer.rendering.BeatXPosition.MiddleNotes)
                            }
                            else 
                            {
                                endNoteRenderer = null
                            }
                        }
                        var heightOffset: Double = noteHeadHeight * com.omnifret.gplayer.EngravingSettings.GraceScale * (0.5).toDouble()
                        if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
                        {
                            heightOffset = -heightOffset
                        }
                        var endValue: Double = if(beat.whammyBarPoints!!.length > 0)  this._getBendNoteValue(note, beat.whammyBarPoints!![(beat.whammyBarPoints!!.length - (1.0).toDouble()).toInt()]) else 0.0
                        var endY: Double = 0.0
                        var bendTie: Boolean = false
                        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.glyphs)) && ((this.glyphs!![(0).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)).containsNoteValue(endValue)))
                        {
                            endY = ((this.glyphs!![(0).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)).getNoteValueY(endValue) + heightOffset
                            bendTie = true
                        }
                        else if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endNoteRenderer)) && ((note.isTieOrigin && note.tieDestination!!.beat.hasWhammyBar) || note.beat.isContinuedWhammy)))
                        {
                            endY = cy + endNoteRenderer!!.y + endNoteRenderer!!.getNoteY(note.tieDestination!!, com.omnifret.gplayer.rendering.NoteYPosition.Top)
                            bendTie = true
                            if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
                            {
                                endY += noteHeadHeight
                            }
                        }
                        else if (note.isTieOrigin)
                        {
                            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(endNoteRenderer)))
                            {
                                endY = startY
                            }
                            else 
                            {
                                endY = cy + endNoteRenderer!!.y + endNoteRenderer!!.getNoteY(note.tieDestination!!, com.omnifret.gplayer.rendering.NoteYPosition.Top)
                            }
                            if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down)
                            {
                                endY += noteHeadHeight
                            }
                        }
                        when (beat.whammyBarType)
                        {
                            com.omnifret.gplayer.model.WhammyType.Hold -> 
                            {
                                if (note.isTieOrigin)
                                {
                                    com.omnifret.gplayer.rendering.glyphs.TieGlyph.paintTie(
                                        canvas
                                        , 
                                        1.0
                                        , 
                                        startX
                                        , 
                                        startY
                                        , 
                                        endX
                                        , 
                                        endY
                                        , 
                                        beatDirection == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        this.renderer.smuflMetrics.tieHeight
                                        , 
                                        this.renderer.smuflMetrics.slurMidpointThickness
                                    
                                    )
                                }
                            }
                            com.omnifret.gplayer.model.WhammyType.Dive -> 
                            {
                                if (i == 0.0)
                                {
                                    var g0: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = (this.glyphs!![(0).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)
                                    g0.x = endX - g0.onTimeX
                                    var previousY: Double = this.glyphs!![(0).toInt()].y
                                    g0.y = cy + startNoteRenderer.y
                                    g0.paint(0.0, 0.0, canvas)
                                    if (g0.containsNoteValue(endValue))
                                    {
                                        endY -= previousY
                                        endY += g0.y
                                    }
                                }
                                if (bendTie)
                                {
                                    this.drawBendSlur(
                                        canvas
                                        , 
                                        startX
                                        , 
                                        startY
                                        , 
                                        endX
                                        , 
                                        endY
                                        , 
                                        direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        slurText
                                    
                                    )
                                }
                                else if (note.isTieOrigin)
                                {
                                    com.omnifret.gplayer.rendering.glyphs.TieGlyph.paintTie(
                                        canvas
                                        , 
                                        1.0
                                        , 
                                        startX
                                        , 
                                        startY
                                        , 
                                        endX
                                        , 
                                        endY
                                        , 
                                        beatDirection == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        this.renderer.smuflMetrics.tieHeight
                                        , 
                                        this.renderer.smuflMetrics.slurMidpointThickness
                                    
                                    )
                                }
                            }
                            com.omnifret.gplayer.model.WhammyType.Dip -> 
                            {
                                if (whammyMode == com.omnifret.gplayer.NotationMode.SongBook)
                                {
                                    if (note.isTieOrigin)
                                    {
                                        com.omnifret.gplayer.rendering.glyphs.TieGlyph.paintTie(
                                            canvas
                                            , 
                                            1.0
                                            , 
                                            startX
                                            , 
                                            startY
                                            , 
                                            endX
                                            , 
                                            endY
                                            , 
                                            beatDirection == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                            , 
                                            this.renderer.smuflMetrics.tieHeight
                                            , 
                                            this.renderer.smuflMetrics.slurMidpointThickness
                                        
                                        )
                                    }
                                }
                                else 
                                {
                                    var middleX: Double = (startX + endX) / (2.0).toDouble()
                                    var g0: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = (this.glyphs!![(0).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)
                                    g0.x = middleX - g0.onTimeX
                                    g0.y = cy + startNoteRenderer.y
                                    g0.paint(0.0, 0.0, canvas)
                                    var middleValue: Double = this._getBendNoteValue(note, beat.whammyBarPoints!![(1).toInt()])
                                    var middleY: Double = g0.getNoteValueY(middleValue) + heightOffset
                                    this.drawBendSlur(
                                        canvas
                                        , 
                                        startX
                                        , 
                                        startY
                                        , 
                                        middleX
                                        , 
                                        middleY
                                        , 
                                        direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        slurText
                                    
                                    )
                                    var g1: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = (this.glyphs!![(1).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)
                                    g1.x = endX - g1.onTimeX
                                    g1.y = cy + startNoteRenderer.y
                                    g1.paint(0.0, 0.0, canvas)
                                    endY = g1.getNoteValueY(endValue) + heightOffset
                                    this.drawBendSlur(
                                        canvas
                                        , 
                                        middleX
                                        , 
                                        middleY
                                        , 
                                        endX
                                        , 
                                        endY
                                        , 
                                        direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        slurText
                                    
                                    )
                                }
                            }
                            com.omnifret.gplayer.model.WhammyType.PrediveDive, com.omnifret.gplayer.model.WhammyType.Predive -> 
                            {
                                var preX: Double = cx + startNoteRenderer.x + startNoteRenderer.getBeatX(note.beat, com.omnifret.gplayer.rendering.BeatXPosition.PreNotes)
                                preX += this._container.prebendNoteHeadOffset
                                var preY: Double = cy + startNoteRenderer.y + startNoteRenderer.getScoreY(startNoteRenderer.accidentalHelper.getNoteStepsForValue(note.displayValue - (((note.beat.whammyBarPoints!![(0).toInt()].value / (2.0).toDouble())).toInt() or 0), false)) + heightOffset
                                this.drawBendSlur(
                                    canvas
                                    , 
                                    preX
                                    , 
                                    preY
                                    , 
                                    startX
                                    , 
                                    startY
                                    , 
                                    direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                    , 
                                    slurText
                                
                                )
                                if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.glyphs)))
                                {
                                    var g0: com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph = (this.glyphs!![(0).toInt()] as com.omnifret.gplayer.rendering.glyphs.BendNoteHeadGroupGlyph)
                                    g0.x = endX - g0.onTimeX
                                    g0.y = cy + startNoteRenderer.y
                                    g0.paint(0.0, 0.0, canvas)
                                    this.drawBendSlur(
                                        canvas
                                        , 
                                        startX
                                        , 
                                        startY
                                        , 
                                        endX
                                        , 
                                        endY
                                        , 
                                        direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Down
                                        , 
                                        slurText
                                    
                                    )
                                }
                            }
                            else -> { }
                        }
                        i++
                    }
                }
            }
            canvas.textAlign = textalign
        }
    }
    
    /**
     */
    private fun _getBendNoteValue(note: com.omnifret.gplayer.model.Note, bendPoint: com.omnifret.gplayer.model.BendPoint): Double{
        return note.displayValueWithoutBend + (((bendPoint.value / (2.0).toDouble())).toInt() or 0)
    }
    
}

