// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal open class ScoreHelperNotesBaseGlyph: com.omnifret.gplayer.rendering.glyphs.GlyphGroup
{
    /**
     */
    protected fun drawBendSlur(canvas: com.omnifret.gplayer.platform.ICanvas, 
    x1: Double, 
    y1: Double, 
    x2: Double, 
    y2: Double, 
    down: Boolean, 
    slurText: String? = null): Unit{
        com.omnifret.gplayer.rendering.glyphs.TieGlyph.drawBendSlur(
            canvas
            , 
            x1
            , 
            y1
            , 
            x2
            , 
            y2
            , 
            down
            , 
            this.renderer.smuflMetrics.tieHeight
            , 
            slurText
        
        )
    }
    
    public override fun doLayout(): Unit{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.glyphs)))
        {
            return
        }
        this.width = 0.0
        for (noteHeads in this.glyphs!!)
        {
            noteHeads.doLayout()
            this.width += noteHeads.width
        }
    }
    
    /**
     */
    protected fun getTieDirection(beat: com.omnifret.gplayer.model.Beat, noteRenderer: com.omnifret.gplayer.rendering.ScoreBarRenderer): com.omnifret.gplayer.rendering.utils.BeamDirection{
        when (noteRenderer.getBeatDirection(beat))
        {
            com.omnifret.gplayer.rendering.utils.BeamDirection.Up -> 
            {
                return com.omnifret.gplayer.rendering.utils.BeamDirection.Down
            }
            else -> 
            {
                return com.omnifret.gplayer.rendering.utils.BeamDirection.Up
            }
        }
    }
    
    public constructor(x: Double, y: Double)
        : super(x, y)
}

