// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreNoteChordGlyph: com.omnifret.gplayer.rendering.glyphs.ScoreNoteChordGlyphBase
{
    private var _noteGlyphLookup: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph> = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph>()
    
    private var _notes: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Note> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.Note>(
    )
    
    
    private var _deadSlapped: com.omnifret.gplayer.rendering.glyphs.DeadSlappedBeatGlyph? = null
    
    private var _tremoloPicking: com.omnifret.gplayer.rendering.glyphs.TremoloPickingGlyph? = null
    
    private var _stemLengthExtension: Double = 0.0
    
    public var aboveBeatEffects: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.glyphs.EffectGlyph> = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.glyphs.EffectGlyph>()
    
    
    public var belowBeatEffects: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.glyphs.EffectGlyph> = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.glyphs.EffectGlyph>()
    
    
    public lateinit var beat: com.omnifret.gplayer.model.Beat
    
    public override val direction: com.omnifret.gplayer.rendering.utils.BeamDirection
    get(){
        return ((this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)).getBeatDirection(this.beat)
    }
    
    public override val hasFlag: Boolean
    get(){
        return ((this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)).hasFlag(this.beat)
    }
    
    public override val hasStem: Boolean
    get(){
        return ((this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)).hasStem(this.beat)
    }
    
    public override val scale: Double
    get(){
        return if(this.beat.graceType != com.omnifret.gplayer.model.GraceType.None)  com.omnifret.gplayer.EngravingSettings.GraceScale else 1.0
    }
    
    protected override fun getScoreChordNoteHeadInfo(): com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo{
        if (this.beat.graceType != com.omnifret.gplayer.model.GraceType.None)
        {
            return com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo(this.direction)
        }
        var staff: com.omnifret.gplayer.model.Staff = this.beat.voice.bar.staff
        var key: String = """score.noteheads.${(staff.track.index).toTemplate()}.${(staff.index).toTemplate()}.${(this.beat.voice.bar.index).toTemplate()}.${(this.beat.absoluteDisplayStart).toTemplate()}"""
        var existing: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo? = this.renderer.staff!!.getSharedLayoutData<com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo?>(key, null)
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(existing)))
        {
            existing = com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo(this.direction)
            this.renderer.staff!!.setSharedLayoutData(key, existing!!)
        }
        return existing!!
    }
    
    /**
     */
    public fun getNoteX(note: com.omnifret.gplayer.model.Note, requestedPosition: com.omnifret.gplayer.rendering.NoteXPosition): Double{
        if (this._noteGlyphLookup.has(note.id))
        {
            var n: com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph = this._noteGlyphLookup.get(note.id)!!
            var pos: Double = this.x + n.x
            when (requestedPosition)
            {
                com.omnifret.gplayer.rendering.NoteXPosition.Left -> 
                {
                }
                com.omnifret.gplayer.rendering.NoteXPosition.Center -> 
                {
                    pos += n.width / (2.0).toDouble()
                }
                com.omnifret.gplayer.rendering.NoteXPosition.Right -> 
                {
                    pos += n.width
                }
                else -> { }
            }
            return pos
        }
        return 0.0
    }
    
    /**
     */
    public fun getNoteY(note: com.omnifret.gplayer.model.Note, requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double{
        if (this._noteGlyphLookup.has(note.id))
        {
            var n: com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph = this._noteGlyphLookup.get(note.id)!!
            return this._internalGetNoteY(n, requestedPosition)
        }
        return 0.0
    }
    
    /**
     */
    public fun getLowestNoteY(requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double{
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.maxStepsNote)))  this._internalGetNoteY(this.maxStepsNote!!.glyph, requestedPosition) else 0.0
    }
    
    /**
     */
    public fun getHighestNoteY(requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double{
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.minStepsNote)))  this._internalGetNoteY(this.minStepsNote!!.glyph, requestedPosition) else 0.0
    }
    
    /**
     */
    private fun _internalGetNoteY(n: com.omnifret.gplayer.rendering.glyphs.MusicFontGlyph, requestedPosition: com.omnifret.gplayer.rendering.NoteYPosition): Double{
        var pos: Double = this.y + n.y
        var sr: com.omnifret.gplayer.rendering.ScoreBarRenderer = (this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)
        var scale: Double = if(this.beat.graceType != com.omnifret.gplayer.model.GraceType.None)  com.omnifret.gplayer.EngravingSettings.GraceScale else 1.0
        when (requestedPosition)
        {
            com.omnifret.gplayer.rendering.NoteYPosition.TopWithStem -> 
            {
                pos -= (if(sr.smuflMetrics.stemUp.has(n.symbol))  sr.smuflMetrics.stemUp.get(n.symbol)!!.bottomY else 0.0) * scale
                pos -= sr.smuflMetrics.getStemLength(this.beat.duration, sr.hasFlag(this.beat)) * scale
                pos -= this._stemLengthExtension
                var topCenterY: Double = sr.centerStaffStemY(this.direction)
                topCenterY -= this._stemLengthExtension
                return com.omnifret.gplayer.core.ecmaScript.Math.min(topCenterY, pos)
            }
            com.omnifret.gplayer.rendering.NoteYPosition.Top -> 
            {
                pos -= n.height / (2.0).toDouble()
            }
            com.omnifret.gplayer.rendering.NoteYPosition.Center -> 
            {
            }
            com.omnifret.gplayer.rendering.NoteYPosition.Bottom -> 
            {
                pos += n.height / (2.0).toDouble()
            }
            com.omnifret.gplayer.rendering.NoteYPosition.BottomWithStem -> 
            {
                pos -= (if(this.renderer.smuflMetrics.stemDown.has(n.symbol))  this.renderer.smuflMetrics.stemDown.get(n.symbol)!!.topY else -this.renderer.smuflMetrics.glyphHeights.get(n.symbol)!! / (2.0).toDouble()) * scale
                pos += sr.smuflMetrics.getStemLength(this.beat.duration, sr.hasFlag(this.beat)) * scale
                pos += this._stemLengthExtension
                var bottomCenterY: Double = sr.centerStaffStemY(this.direction)
                bottomCenterY += this._stemLengthExtension
                return com.omnifret.gplayer.core.ecmaScript.Math.max(bottomCenterY, pos)
            }
            com.omnifret.gplayer.rendering.NoteYPosition.StemUp -> 
            {
                pos -= (if(sr.smuflMetrics.stemUp.has(n.symbol))  sr.smuflMetrics.stemUp.get(n.symbol)!!.bottomY else 0.0) * scale
            }
            com.omnifret.gplayer.rendering.NoteYPosition.StemDown -> 
            {
                pos -= (if(sr.smuflMetrics.stemDown.has(n.symbol))  sr.smuflMetrics.stemDown.get(n.symbol)!!.topY else -sr.smuflMetrics.glyphHeights.get(n.symbol)!! / (2.0).toDouble()) * scale
            }
            else -> { }
        }
        return pos
    }
    
    /**
     */
    public fun addMainNoteGlyph(noteGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase, note: com.omnifret.gplayer.model.Note, noteLine: Double): Unit{
        super.add(noteGlyph, noteLine)
        this._noteGlyphLookup.set(note.id, noteGlyph)
        this._notes.push(note)
    }
    
    /**
     */
    public fun addEffectNoteGlyph(noteGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase, noteLine: Double): Unit{
        super.add(noteGlyph, noteLine)
    }
    
    public override fun doLayout(): Unit{
        super.doLayout()
        var scoreRenderer: com.omnifret.gplayer.rendering.ScoreBarRenderer = (this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)
        if (this.beat.deadSlapped)
        {
            this._deadSlapped = com.omnifret.gplayer.rendering.glyphs.DeadSlappedBeatGlyph()
            this._deadSlapped!!.renderer = this.renderer
            this._deadSlapped!!.doLayout()
            this.width = this._deadSlapped!!.width
            this.onTimeX = this.width / (2.0).toDouble()
        }
        var aboveBeatEffectsY: Double = 0.0
        var belowBeatEffectsY: Double = 0.0
        var effectSpacing: Double = this.renderer.smuflMetrics.onNoteEffectPadding
        if (this.beat.deadSlapped)
        {
            belowBeatEffectsY = scoreRenderer.getScoreY(0.0)
            aboveBeatEffectsY = scoreRenderer.getScoreY(scoreRenderer.heightLineCount)
        }
        else 
        {
            if (this.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
            {
                belowBeatEffectsY = this._internalGetNoteY(this.maxStepsNote!!.glyph, com.omnifret.gplayer.rendering.NoteYPosition.Bottom) + effectSpacing
                aboveBeatEffectsY = this._internalGetNoteY(this.minStepsNote!!.glyph, com.omnifret.gplayer.rendering.NoteYPosition.TopWithStem) - effectSpacing
            }
            else 
            {
                belowBeatEffectsY = this._internalGetNoteY(this.maxStepsNote!!.glyph, com.omnifret.gplayer.rendering.NoteYPosition.BottomWithStem) + effectSpacing
                aboveBeatEffectsY = this._internalGetNoteY(this.minStepsNote!!.glyph, com.omnifret.gplayer.rendering.NoteYPosition.Top) - effectSpacing
            }
        }
        var minEffectY: Double? = null
        var maxEffectY: Double? = null
        for (effect in this.aboveBeatEffects.values())
        {
            effect.renderer = this.renderer
            effect.doLayout()
            aboveBeatEffectsY -= effect.height
            effect.y = aboveBeatEffectsY
            if (minEffectY == null || minEffectY!! > aboveBeatEffectsY)
            {
                minEffectY = aboveBeatEffectsY
            }
            if (maxEffectY == null || maxEffectY!! < aboveBeatEffectsY)
            {
                maxEffectY = aboveBeatEffectsY
            }
            aboveBeatEffectsY -= effectSpacing
        }
        for (effect in this.belowBeatEffects.values())
        {
            effect.renderer = this.renderer
            effect.doLayout()
            effect.y = belowBeatEffectsY
            if (minEffectY == null || minEffectY!! > belowBeatEffectsY)
            {
                minEffectY = belowBeatEffectsY
            }
            if (maxEffectY == null || maxEffectY!! < belowBeatEffectsY)
            {
                maxEffectY = belowBeatEffectsY
            }
            belowBeatEffectsY += effect.height + effectSpacing
        }
        if (minEffectY != null)
        {
            scoreRenderer.registerBeatEffectOverflows(minEffectY!!, maxEffectY ?: 0.0)
        }
        if (this.beat.isTremolo && !this.beat.deadSlapped)
        {
            this._tremoloPicking = com.omnifret.gplayer.rendering.glyphs.TremoloPickingGlyph(0.0, 0.0, this.beat.tremoloPicking!!)
            this._tremoloPicking!!.renderer = this.renderer
            this._tremoloPicking!!.doLayout()
            this._alignTremoloPickingGlyph()
        }
    }
    
    private fun _alignTremoloPickingGlyph(): Unit{
        var g: com.omnifret.gplayer.rendering.glyphs.TremoloPickingGlyph = this._tremoloPicking!!
        var direction: com.omnifret.gplayer.rendering.utils.BeamDirection = this.direction
        if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        {
            g.alignTremoloPickingGlyph(direction, this.getHighestNoteY(com.omnifret.gplayer.rendering.NoteYPosition.TopWithStem), this.getHighestNoteY(com.omnifret.gplayer.rendering.NoteYPosition.Center), this.beat.duration)
        }
        else 
        {
            g.alignTremoloPickingGlyph(direction, this.getLowestNoteY(com.omnifret.gplayer.rendering.NoteYPosition.BottomWithStem), this.getLowestNoteY(com.omnifret.gplayer.rendering.NoteYPosition.Center), this.beat.duration)
        }
        this._stemLengthExtension = g.stemExtensionHeight
        var tremoloX: Double = this.stemX
        if (this.beat.duration < com.omnifret.gplayer.model.Duration.Half)
        {
            tremoloX = this.width / (2.0).toDouble()
        }
        g.x = tremoloX
    }
    
    /**
     */
    public fun buildBoundingsLookup(beatBounds: com.omnifret.gplayer.rendering.utils.BeatBounds, cx: Double, cy: Double): Unit{
        for (note in this._notes)
        {
            if (this._noteGlyphLookup.has(note.id))
            {
                var glyph: com.omnifret.gplayer.rendering.glyphs.EffectGlyph = this._noteGlyphLookup.get(note.id)!!
                var noteBounds: com.omnifret.gplayer.rendering.utils.NoteBounds = com.omnifret.gplayer.rendering.utils.NoteBounds()
                noteBounds.note = note
                noteBounds.noteHeadBounds = com.omnifret.gplayer.rendering.utils.Bounds()
                noteBounds.noteHeadBounds.x = cx + this.x + glyph.x
                noteBounds.noteHeadBounds.y = cy + this.y + glyph.y - glyph.height / (2.0).toDouble()
                noteBounds.noteHeadBounds.w = glyph.width
                noteBounds.noteHeadBounds.h = glyph.height
                beatBounds.addNote(noteBounds)
            }
        }
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        this._paintEffects(cx, cy, canvas)
        super.paint(cx, cy, canvas)
    }
    
    /**
     */
    private fun _paintEffects(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        (com.omnifret.gplayer.rendering.utils.ElementStyleHelper.beat(canvas, com.omnifret.gplayer.model.BeatSubElement.StandardNotationEffects, this.beat))
        .use {
            for (g in this.aboveBeatEffects.values())
            {
                g.paint(cx + this.x + this.width / (2.0).toDouble(), cy + this.y, canvas)
            }
            for (g in this.belowBeatEffects.values())
            {
                g.paint(cx + this.x + this.width / (2.0).toDouble(), cy + this.y, canvas)
            }
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._tremoloPicking)))
            {
                this._tremoloPicking!!.paint(cx, cy, canvas)
            }
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._deadSlapped)))
            {
                this._deadSlapped!!.paint(cx, cy, canvas)
            }
        }
    }
    
    public constructor()
        : super()
}

