// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.glyphs
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal abstract class ScoreNoteChordGlyphBase: com.omnifret.gplayer.rendering.glyphs.Glyph
{
    private var _infos: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>(
    )
    
    
    private var _noteHeadInfo: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo? = null
    
    protected var noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup? = null
    
    public var minStepsNote: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo? = null
    
    
    public var maxStepsNote: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo? = null
    
    
    public val stemX: Double
    get(){
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.noteGroup)))
        {
            return 0.0
        }
        return this.noteGroup!!.stemX + this.noteGroup!!.multiVoiceShiftX
    }
    
    public var noteStartX: Double = 0.0
    
    
    public var onTimeX: Double = 0.0
    
    
    public constructor()
        : super(0.0, 0.0)
    public abstract val direction: com.omnifret.gplayer.rendering.utils.BeamDirection
    
    public abstract val hasFlag: Boolean
    
    public abstract val hasStem: Boolean
    
    public abstract val scale: Double
    
    public override fun getBoundingBoxTop(): Double{
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.minStepsNote)))  this.minStepsNote!!.glyph.getBoundingBoxTop() else this.y
    }
    
    public override fun getBoundingBoxBottom(): Double{
        return if(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.maxStepsNote)))  this.maxStepsNote!!.glyph.getBoundingBoxBottom() else this.y + this.height
    }
    
    /**
     */
    protected fun add(noteGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase, noteSteps: Double): Unit{
        var info: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo = com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo(glyph = noteGlyph, steps = noteSteps)
        this._infos.push(info)
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.minStepsNote)) || this.minStepsNote!!.steps > info.steps)
        {
            this.minStepsNote = info
        }
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.maxStepsNote)) || this.maxStepsNote!!.steps < info.steps)
        {
            this.maxStepsNote = info
        }
    }
    
    protected abstract fun getScoreChordNoteHeadInfo(): com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo
    
    /**
     */
    private fun _prepareForLayout(info: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo): com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup{
        var direction: com.omnifret.gplayer.rendering.utils.BeamDirection = this.direction
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(info.groups)))
        {
            info.mainVoiceDirection = direction
        }
        if (direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        {
            this._infos.sort(fun(a: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo, b: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo): Double{
                return b.steps - a.steps
            }
            )
        }
        else 
        {
            this._infos.sort(fun(a: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo, b: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo): Double{
                return a.steps - b.steps
            }
            )
        }
        var group: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup
        var hasFlag: Boolean = this.hasFlag
        var hasStem: Boolean = this.hasStem
        if (info.groups!!.has(direction))
        {
            group = info.groups!!.get(direction)!!
            if (hasFlag)
            {
                group.hasFlag = hasFlag
            }
            if (hasStem)
            {
                group.hasStem = hasStem
            }
        }
        else 
        {
            group = com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup(correctNotes = com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide(notes = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>>(), width = 0.0, minX = com.omnifret.gplayer.core.ecmaScript.Number.NaN), 
            direction = direction, 
            stemX = 0.0, 
            maxX = com.omnifret.gplayer.core.ecmaScript.Number.NaN, 
            minX = com.omnifret.gplayer.core.ecmaScript.Number.NaN, 
            minStep = com.omnifret.gplayer.core.ecmaScript.Number.NaN, 
            maxStep = com.omnifret.gplayer.core.ecmaScript.Number.NaN, 
            multiVoiceShiftX = 0.0, 
            hasFlag = hasFlag, 
            hasStem = hasStem)
            info.groups.set(direction, group)
        }
        return group
    }
    
    public override fun doLayout(): Unit{
        var info: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo = this.getScoreChordNoteHeadInfo()
        var noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup = this._prepareForLayout(info)
        this.noteGroup = noteGroup
        this._noteHeadInfo = info
        this._collectNoteDisplacements(noteGroup)
        this._alignNoteHeadsGroup(noteGroup)
        info.update()
        this._updateSizes()
    }
    
    private fun _updateSizes(): Unit{
        var noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup = this.noteGroup!!
        this.onTimeX = noteGroup.correctNotes.minX + noteGroup.correctNotes.width / (2.0).toDouble()
        this.width = this.noteStartX + noteGroup.multiVoiceShiftX + noteGroup.maxX - noteGroup.minX
    }
    
    public fun doMultiVoiceLayout(): Unit{
        this._noteHeadInfo!!.finish(this.renderer.smuflMetrics)
        this._updateSizes()
    }
    
    /**
     */
    private fun _alignNoteHeadsGroup(noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup): Unit{
        if (noteGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
        {
            this._alignNoteHeads(noteGroup, noteGroup.correctNotes, true)
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.displacedNotes)))
            {
                this._alignNoteHeads(noteGroup, noteGroup.displacedNotes!!, false)
            }
        }
        else 
        {
            this._alignNoteHeads(noteGroup, noteGroup.correctNotes, false)
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.displacedNotes)))
            {
                this._alignNoteHeads(noteGroup, noteGroup.displacedNotes!!, true)
            }
        }
    }
    
    /**
     */
    private fun _alignNoteHeads(noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup, side: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide, leftOfStem: Boolean): Unit{
        var scale: Double = this.scale
        var smufl: com.omnifret.gplayer.EngravingSettings = this.renderer.smuflMetrics
        for (stepInfos in side.notes.values())
        {
            for (info in stepInfos)
            {
                info.glyph.x = noteGroup.stemX
                if (info.glyph.centerOnStem)
                {
                }
                else if (leftOfStem)
                {
                    if (smufl.stemUp.has(info.glyph.symbol))
                    {
                        info.glyph.x -= smufl.stemUp.get(info.glyph.symbol)!!.x * scale
                    }
                    else 
                    {
                        info.glyph.x -= smufl.glyphWidths.get(info.glyph.symbol)!! * scale
                    }
                }
                else 
                {
                    if (smufl.stemDown.has(info.glyph.symbol))
                    {
                        info.glyph.x += smufl.stemDown.get(info.glyph.symbol)!!.x * scale
                    }
                }
                side.width = com.omnifret.gplayer.core.ecmaScript.Math.max(side.width, info.glyph.width)
                if (com.omnifret.gplayer.core.ecmaScript.Number.isNaN(side.minX) || info.glyph.x < side.minX)
                {
                    side.minX = info.glyph.x
                }
                if (com.omnifret.gplayer.core.ecmaScript.Number.isNaN(noteGroup.minX) || info.glyph.x < noteGroup.minX)
                {
                    noteGroup.minX = info.glyph.x
                }
                var maxX: Double = info.glyph.x + info.glyph.width
                if (com.omnifret.gplayer.core.ecmaScript.Number.isNaN(noteGroup.maxX) || maxX > noteGroup.maxX)
                {
                    noteGroup.maxX = maxX
                }
            }
        }
    }
    
    /**
     */
    private fun _collectNoteDisplacements(noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup): Unit{
        for (info in this._infos)
        {
            info.glyph.renderer = this.renderer
            info.glyph.doLayout()
            var isGroupCollision: Boolean = com.omnifret.gplayer.rendering.glyphs.ScoreNoteChordGlyphBase._hasCollision(noteGroup.correctNotes, info)
            var noteLookup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide
            if (isGroupCollision)
            {
                if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.displacedNotes)))
                {
                    noteGroup.displacedNotes = com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide(notes = com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>>(), width = 0.0, minX = 0.0)
                }
                noteLookup = noteGroup.displacedNotes!!
            }
            else 
            {
                noteLookup = noteGroup.correctNotes!!
            }
            var stepInfos: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>
            if (noteLookup.notes.has(info.steps))
            {
                stepInfos = noteLookup.notes.get(info.steps)!!
            }
            else 
            {
                stepInfos = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>(
                )
                
                noteLookup.notes.set(info.steps, stepInfos)
            }
            stepInfos.push(info)
            if (com.omnifret.gplayer.core.ecmaScript.Number.isNaN(noteGroup.minStep) || info.steps < noteGroup.minStep)
            {
                noteGroup.minStep = info.steps
            }
            if (com.omnifret.gplayer.core.ecmaScript.Number.isNaN(noteGroup.maxStep) || info.steps > noteGroup.maxStep)
            {
                noteGroup.maxStep = info.steps
            }
            this._updateGroupStemXPosition(info, noteGroup)
        }
    }
    
    /**
     */
    private fun _updateGroupStemXPosition(info: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo, noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup): Unit{
        var smufl: com.omnifret.gplayer.EngravingSettings = this.renderer.smuflMetrics
        var scale: Double = this.scale
        var stemX: Double
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up || com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.displacedNotes))))
        {
            if (smufl.stemUp.has(info.glyph.symbol))
            {
                var stemInfo: com.omnifret.gplayer.EngravingStemInfo = smufl.stemUp.get(info.glyph.symbol)!!
                stemX = stemInfo.x * scale
            }
            else 
            {
                stemX = smufl.glyphWidths.get(info.glyph.symbol)!! * scale
            }
        }
        else 
        {
            if (smufl.stemDown.has(info.glyph.symbol))
            {
                var stemInfo: com.omnifret.gplayer.EngravingStemInfo = smufl.stemDown.get(info.glyph.symbol)!!
                stemX = stemInfo.x * scale
            }
            else 
            {
                stemX = 0.0
            }
        }
        stemX += this.noteStartX
        if (stemX > noteGroup.stemX)
        {
            noteGroup.stemX = stemX
        }
    }
    
    /**
     */
    public override fun paint(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        var paramcx = cx
        var paramcy = cy
        paramcx += this.x
        paramcy += this.y
        this._paintLedgerLines(paramcx, paramcy, canvas)
        var noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup = this.noteGroup!!
        paramcx += noteGroup.multiVoiceShiftX
        var infos: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo> = this._infos
        for (g in infos)
        {
            g.glyph.renderer = this.renderer
            g.glyph.paint(paramcx, paramcy, canvas)
        }
    }
    
    /**
     */
    private fun _paintLedgerLines(cx: Double, cy: Double, canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.minStepsNote)))
        {
            return
        }
        var scoreRenderer: com.omnifret.gplayer.rendering.ScoreBarRenderer = (this.renderer as com.omnifret.gplayer.rendering.ScoreBarRenderer)
        (com.omnifret.gplayer.rendering.utils.ElementStyleHelper.bar(canvas, com.omnifret.gplayer.model.BarSubElement.StandardNotationStaffLine, scoreRenderer.bar, true))
        .use {
            var scale: Double = this.scale
            var lineExtension: Double = this.renderer.smuflMetrics.legerLineExtension * scale
            var lineWidth: Double = this.width + lineExtension * (2.0).toDouble() - this.noteStartX
            var lineSpacing: Double = scoreRenderer.getLineHeight(1.0)
            var firstTopLedgerY: Double = scoreRenderer.getLineY(-1.0)
            var firstBottomLedgerY: Double = scoreRenderer.getLineY(scoreRenderer.drawnLineCount)
            var minNoteLineY: Double = scoreRenderer.getLineY(this.minStepsNote!!.steps / (2.0).toDouble())
            var maxNoteLineY: Double = scoreRenderer.getLineY(this.maxStepsNote!!.steps / (2.0).toDouble())
            var lineYOffset: Double = (this.renderer.smuflMetrics.legerLineThickness * scale) / (2.0).toDouble()
            var y: Double = firstTopLedgerY
            while (y >= minNoteLineY)
            {
                canvas.fillRect(cx - lineExtension + this.noteStartX, cy + y - lineYOffset, lineWidth, this.renderer.smuflMetrics.legerLineThickness * scale)
                y -= lineSpacing
            }
            y = firstBottomLedgerY
            while (y <= maxNoteLineY)
            {
                canvas.fillRect(cx - lineExtension + this.noteStartX, cy + y - lineYOffset, lineWidth, this.renderer.smuflMetrics.legerLineThickness * scale)
                y += lineSpacing
            }
        }
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _hasCollision(side: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide, info: com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo): Boolean{
            return side.notes.has(info.steps) || side.notes.has(info.steps + 1.0) || side.notes.has(info.steps - (1.0).toDouble())
        }
        
    }
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreChordNoteHeadGroupSide: com.omnifret.gplayer.core.IRecord
{
    /**
     * A lookup for the notes located at particular steps.
     * If we have more than 2 filled voices at the same spot, we might have the additional voices
     * placed where the secondary voice already is.
     */
    public var notes: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>>
    
    /**
     * The width of this individual side.
     */
    public var width: Double
    
    /**
     * The smallest X-coordinate of all glyphs. Used later to calculate
     * the overall shift needed to place notes within the bounds.
     */
    public var minX: Double
    
    public constructor(notes: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo>>, width: Double, minX: Double){
        this.notes = notes
        this.width = width
        this.minX = minX
    }
    
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreChordNoteHeadGroup: com.omnifret.gplayer.core.IRecord
{
    /**
     * All notes on the "correct" side of the stem,
     * that's left for upwards stems, and right for downward stems.
     */
    public var correctNotes: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide
    
    /**
     * All displaced notes (the other side of the stem compared to )
     */
    public var displacedNotes: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide? = null
    
    /**
     * The direction this group defines.
     */
    public var direction: com.omnifret.gplayer.rendering.utils.BeamDirection
    
    public var minStep: Double
    
    public var maxStep: Double
    
    /**
     * The offset of the stem for this group.
     * Offset is relative to the group.
     */
    public var stemX: Double
    
    /**
     * Smallest X-coordinate in this group.
     * Offset is relative to the group.
     */
    public var minX: Double
    
    /**
     * Largest X-coordinate in this group.
     * Offset is relative to the group.
     */
    public var maxX: Double
    
    /**
     * The shift applied for the group to avoid overlaps.
     */
    public var multiVoiceShiftX: Double
    
    public var hasFlag: Boolean
    
    public var hasStem: Boolean
    
    public constructor(correctNotes: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide, 
    direction: com.omnifret.gplayer.rendering.utils.BeamDirection, 
    minStep: Double, 
    maxStep: Double, 
    stemX: Double, 
    minX: Double, 
    maxX: Double, 
    multiVoiceShiftX: Double, 
    hasFlag: Boolean, 
    hasStem: Boolean, 
    displacedNotes: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroupSide? = null){
        this.correctNotes = correctNotes
        this.displacedNotes = displacedNotes
        this.direction = direction
        this.minStep = minStep
        this.maxStep = maxStep
        this.stemX = stemX
        this.minX = minX
        this.maxX = maxX
        this.multiVoiceShiftX = multiVoiceShiftX
        this.hasFlag = hasFlag
        this.hasStem = hasStem
    }
    
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreChordNoteHeadInfo
{
    /**
     * The direction of the main voice.
     */
    public var mainVoiceDirection: com.omnifret.gplayer.rendering.utils.BeamDirection = com.omnifret.gplayer.rendering.utils.BeamDirection.Up
    
    
    /**
     * All groups respective to their direction.
     */
    public var groups: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.utils.BeamDirection, com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.rendering.utils.BeamDirection, com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup>()
    
    
    public var minX: Double = 0.0
    
    
    public var maxX: Double = 0.0
    
    
    private var _isFinished: Boolean = false
    
    public constructor(mainVoiceDirection: com.omnifret.gplayer.rendering.utils.BeamDirection){
        this.mainVoiceDirection = mainVoiceDirection
    }
    
    public fun update(): Unit{
        var minX: Double = 0.0
        var maxX: Double = 0.0
        for (g in this.groups.values())
        {
            var gMinX: Double = g.minX + g.multiVoiceShiftX
            var gMaxX: Double = g.maxX + g.multiVoiceShiftX
            if (gMinX < minX)
            {
                minX = gMinX
            }
            if (maxX < gMaxX)
            {
                maxX = gMaxX
            }
        }
        this.minX = minX
        this.maxX = maxX
    }
    
    /**
     */
    public fun finish(smufl: com.omnifret.gplayer.EngravingSettings): Unit{
        if (this._isFinished)
        {
            return
        }
        this._isFinished = true
        for (g in this.groups.values())
        {
            this._checkForGroupDisplacement(g, smufl)
        }
        this.update()
    }
    
    /**
     */
    private fun _checkForGroupDisplacement(noteGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup, smufl: com.omnifret.gplayer.EngravingSettings): Unit{
        if (this.mainVoiceDirection == noteGroup.direction)
        {
            return
        }
        var mainGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup = this.groups.get(this.mainVoiceDirection)!!
        var intersection: com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind = com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo._checkIntersection(mainGroup, noteGroup)
        var spacing: Double = smufl.multiVoiceDisplacedNoteHeadSpacing
        when (intersection)
        {
            com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.NoIntersection -> 
            {
                return
            }
            com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.ExactMatch -> 
            {
                if (!com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo._canShareNoteHead(mainGroup, noteGroup))
                {
                    if (mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
                    {
                        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(noteGroup.displacedNotes)))
                        {
                            noteGroup.multiVoiceShiftX = noteGroup.stemX + noteGroup.correctNotes.width + spacing
                        }
                        else 
                        {
                            noteGroup.multiVoiceShiftX = noteGroup.correctNotes.width + spacing
                        }
                    }
                    else 
                    {
                        mainGroup.multiVoiceShiftX = noteGroup.stemX + spacing
                    }
                }
            }
            com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.EndsTouchingOuter -> 
            {
                if (mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
                {
                    if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(mainGroup.displacedNotes)))
                    {
                        noteGroup.multiVoiceShiftX = mainGroup.stemX
                    }
                    else 
                    {
                        var diff: Double = mainGroup.stemX - noteGroup.stemX
                        noteGroup.multiVoiceShiftX = diff
                    }
                }
                else 
                {
                    if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(mainGroup.displacedNotes)))
                    {
                        noteGroup.multiVoiceShiftX = -noteGroup.stemX
                    }
                    else 
                    {
                        var diff: Double = noteGroup.stemX - mainGroup.stemX
                        mainGroup.multiVoiceShiftX = diff
                    }
                }
            }
            com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.EndsTouchingInner -> 
            {
                if (mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
                {
                    mainGroup.multiVoiceShiftX = mainGroup.stemX
                    if (noteGroup.hasFlag)
                    {
                        mainGroup.multiVoiceShiftX += spacing
                    }
                }
                else 
                {
                    noteGroup.multiVoiceShiftX = noteGroup.stemX
                    if (mainGroup.hasFlag)
                    {
                        noteGroup.multiVoiceShiftX += spacing
                    }
                }
            }
            com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.FullIntersection -> 
            {
                if (!mainGroup.hasStem && !noteGroup.hasStem)
                {
                }
                else if (mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
                {
                    mainGroup.multiVoiceShiftX = mainGroup.stemX
                    if (noteGroup.hasFlag)
                    {
                        mainGroup.multiVoiceShiftX += spacing
                    }
                    else 
                    {
                        mainGroup.multiVoiceShiftX -= spacing
                    }
                }
                else 
                {
                    noteGroup.multiVoiceShiftX = noteGroup.stemX
                    if (mainGroup.hasFlag)
                    {
                        noteGroup.multiVoiceShiftX += spacing
                    }
                    else 
                    {
                        noteGroup.multiVoiceShiftX -= spacing
                    }
                }
            }
            else -> { }
        }
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _canShareNoteHead(mainGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup, thisGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup): Boolean{
            var mainGroupBottom: Double = if(mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)  mainGroup.maxStep else mainGroup.minStep
            var thisGroupBottom: Double = if(thisGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)  thisGroup.maxStep else thisGroup.minStep
            var mainGroupBottomNoteHead: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo> = mainGroup.correctNotes.notes.get(mainGroupBottom)!!
            if (mainGroupBottomNoteHead.length > 1)
            {
                return false
            }
            var thisGroupBottomNoteHead: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.ScoreNoteGlyphInfo> = thisGroup.correctNotes.notes.get(thisGroupBottom)!!
            if (thisGroupBottomNoteHead.length > 1)
            {
                return false
            }
            return com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadInfo._canShareNoteHeadGlyph(mainGroupBottomNoteHead[(0).toInt()].glyph, thisGroupBottomNoteHead[(0).toInt()].glyph)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _canShareNoteHeadGlyph(mainGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase, thisGlyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase): Boolean{
            return (mainGlyph.glyphScale == thisGlyph.glyphScale && mainGlyph.centerOnStem == thisGlyph.centerOnStem && com.omnifret.gplayer.model.MusicFontSymbolLookup.isBlackNoteHead(mainGlyph.symbol) && com.omnifret.gplayer.model.MusicFontSymbolLookup.isBlackNoteHead(thisGlyph.symbol))
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _checkIntersection(mainGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup, thisGroup: com.omnifret.gplayer.rendering.glyphs.ScoreChordNoteHeadGroup): com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind{
            var bottomGap: Double = 0.0
            if (mainGroup.direction == com.omnifret.gplayer.rendering.utils.BeamDirection.Up)
            {
                var mainGroupBottom: Double = mainGroup.maxStep
                var thisGroupBottom: Double = thisGroup.minStep
                bottomGap = thisGroupBottom - mainGroupBottom
            }
            else 
            {
                var mainGroupBottom: Double = mainGroup.minStep
                var thisGroupBottom: Double = thisGroup.maxStep
                bottomGap = mainGroupBottom - thisGroupBottom
            }
            if (bottomGap == 0.0)
            {
                return com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.ExactMatch
            }
            if (bottomGap == 1.0)
            {
                return com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.EndsTouchingOuter
            }
            if (bottomGap == -1.0)
            {
                return com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.EndsTouchingInner
            }
            if (bottomGap < 0)
            {
                return com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.FullIntersection
            }
            return com.omnifret.gplayer.rendering.glyphs.NoteHeadIntersectionKind.NoIntersection
        }
        
    }
}

internal enum class NoteHeadIntersectionKind(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    NoIntersection(0),
    EndsTouchingOuter(1),
    EndsTouchingInner(2),
    ExactMatch(3),
    FullIntersection(4);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<NoteHeadIntersectionKind>{
        public override val values = arrayOf(NoIntersection, EndsTouchingOuter, EndsTouchingInner, ExactMatch, FullIntersection) 
        public override fun fromValue(v:Double): NoteHeadIntersectionKind{
            return when(v.toInt()){
                NoIntersection.value -> NoIntersection
                EndsTouchingOuter.value -> EndsTouchingOuter
                EndsTouchingInner.value -> EndsTouchingInner
                ExactMatch.value -> ExactMatch
                FullIntersection.value -> FullIntersection
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class ScoreNoteGlyphInfo: com.omnifret.gplayer.core.IRecord
{
    public var glyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase
    
    public var steps: Double
    
    public constructor(glyph: com.omnifret.gplayer.rendering.glyphs.NoteHeadGlyphBase, steps: Double){
        this.glyph = glyph
        this.steps = steps
    }
    
}

