// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.xml
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class XmlParser
{
    companion object{
        @kotlin.jvm.JvmStatic
        public val CharCodeLF: Double = 10.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeTab: Double = 9.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeCR: Double = 13.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeSpace: Double = 32.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeLowerThan: Double = 60.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeAmp: Double = 38.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeBrackedClose: Double = 93.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeBrackedOpen: Double = 91.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeGreaterThan: Double = 62.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeExclamation: Double = 33.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeUpperD: Double = 68.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeLowerD: Double = 100.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeMinus: Double = 45.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeQuestion: Double = 63.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeSlash: Double = 47.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeEquals: Double = 61.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeDoubleQuote: Double = 34.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeSingleQuote: Double = 39.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeSharp: Double = 35.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeLowerX: Double = 120.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeLowerA: Double = 97.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeLowerZ: Double = 122.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeUpperA: Double = 65.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeUpperZ: Double = 90.0
        
        @kotlin.jvm.JvmStatic
        public val CharCode0: Double = 48.0
        
        @kotlin.jvm.JvmStatic
        public val CharCode9: Double = 57.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeColon: Double = 58.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeDot: Double = 46.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeUnderscore: Double = 95.0
        
        @kotlin.jvm.JvmStatic
        public val CharCodeSemi: Double = 59.0
        
        @kotlin.jvm.JvmStatic
        private var _escapes: com.omnifret.gplayer.collections.Map<String, String> = com.omnifret.gplayer.collections.Map<String, String>(com.omnifret.gplayer.collections.SimpleIterable<com.omnifret.gplayer.core.IArrayTuple<String, String>>(
            com.omnifret.gplayer.core.ArrayTuple<String, String>("lt", "<"), com.omnifret.gplayer.core.ArrayTuple<String, String>("gt", ">"), com.omnifret.gplayer.core.ArrayTuple<String, String>("amp", "&"), com.omnifret.gplayer.core.ArrayTuple<String, String>("quot", "\""), com.omnifret.gplayer.core.ArrayTuple<String, String>("apos", "'"))
        )
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun parse(str: String, p: Double, parent: com.omnifret.gplayer.xml.XmlNode): Double{
            var paramp = p
            var c: Double = str.charCodeAt(paramp)
            var state: com.omnifret.gplayer.xml.XmlState = com.omnifret.gplayer.xml.XmlState.Begin
            var next: com.omnifret.gplayer.xml.XmlState = com.omnifret.gplayer.xml.XmlState.Begin
            var start: Double = 0.0
            var buf: StringBuilder = StringBuilder()
            var escapeNext: com.omnifret.gplayer.xml.XmlState = com.omnifret.gplayer.xml.XmlState.Begin
            var xml: com.omnifret.gplayer.xml.XmlNode? = null
            var aname: String? = null
            var nbrackets: Double = 0.0
            var attrValQuote: Double = 0.0
            while (paramp < str.length.toDouble())
            {
                c = str.charCodeAt(paramp)
                when (state)
                {
                    com.omnifret.gplayer.xml.XmlState.IgnoreSpaces -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeLF, com.omnifret.gplayer.xml.XmlParser.CharCodeCR, com.omnifret.gplayer.xml.XmlParser.CharCodeTab, com.omnifret.gplayer.xml.XmlParser.CharCodeSpace -> 
                            {
                            }
                            else -> 
                            {
                                state = next
                                continue
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Begin -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeLowerThan -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                                next = com.omnifret.gplayer.xml.XmlState.BeginNode
                            }
                            else -> 
                            {
                                start = paramp
                                state = com.omnifret.gplayer.xml.XmlState.Pcdata
                                continue
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Pcdata -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeLowerThan)
                        {
                            buf.append(str.substr(start, paramp - start))
                            var child: com.omnifret.gplayer.xml.XmlNode = com.omnifret.gplayer.xml.XmlNode()
                            child.nodeType = com.omnifret.gplayer.xml.XmlNodeType.Text
                            child.value = buf.toString()
                            buf.setLength(0)
                            parent.addChild(child)
                            state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                            next = com.omnifret.gplayer.xml.XmlState.BeginNode
                        }
                        else if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeAmp)
                        {
                            buf.append(str.substr(start, paramp - start))
                            state = com.omnifret.gplayer.xml.XmlState.Escape
                            escapeNext = com.omnifret.gplayer.xml.XmlState.Pcdata
                            start = paramp + 1.0
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Cdata -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeBrackedClose && str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeBrackedClose && str.charCodeAt(paramp + 2.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan)
                        {
                            var child: com.omnifret.gplayer.xml.XmlNode = com.omnifret.gplayer.xml.XmlNode()
                            child.nodeType = com.omnifret.gplayer.xml.XmlNodeType.CDATA
                            child.value = str.substr(start, paramp - start)
                            parent.addChild(child)
                            paramp += 2.0
                            state = com.omnifret.gplayer.xml.XmlState.Begin
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.BeginNode -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeExclamation -> 
                            {
                                if (str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeBrackedOpen)
                                {
                                    paramp += 2.0
                                    if (str.substr(paramp, 6.0).uppercase() != "CDATA[")
                                    {
                                        throw com.omnifret.gplayer.xml.XmlError("Expected <![CDATA[", str, paramp)
                                    }
                                    paramp += 5.0
                                    state = com.omnifret.gplayer.xml.XmlState.Cdata
                                    start = paramp + 1.0
                                }
                                else if (str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeUpperD || str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeLowerD)
                                {
                                    if (str.substr(paramp + 2.0, 6.0).uppercase() != "OCTYPE")
                                    {
                                        throw com.omnifret.gplayer.xml.XmlError("Expected <!DOCTYPE", str, paramp)
                                    }
                                    paramp += 8.0
                                    state = com.omnifret.gplayer.xml.XmlState.Doctype
                                    start = paramp + 1.0
                                }
                                else if (str.charCodeAt(paramp + 1.0) != com.omnifret.gplayer.xml.XmlParser.CharCodeMinus || str.charCodeAt(paramp + 2.0) != com.omnifret.gplayer.xml.XmlParser.CharCodeMinus)
                                {
                                    throw com.omnifret.gplayer.xml.XmlError("Expected <!--", str, paramp)
                                }
                                else 
                                {
                                    paramp += 2.0
                                    state = com.omnifret.gplayer.xml.XmlState.Comment
                                    start = paramp + 1.0
                                }
                            }
                            com.omnifret.gplayer.xml.XmlParser.CharCodeQuestion -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.Header
                                start = paramp
                            }
                            com.omnifret.gplayer.xml.XmlParser.CharCodeSlash -> 
                            {
                                if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(parent)))
                                {
                                    throw com.omnifret.gplayer.xml.XmlError("Expected node name", str, paramp)
                                }
                                start = paramp + 1.0
                                state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                                next = com.omnifret.gplayer.xml.XmlState.Close
                            }
                            else -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.TagName
                                start = paramp
                                continue
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.TagName -> 
                    {
                        if (!com.omnifret.gplayer.xml.XmlParser._isValidChar(c))
                        {
                            if (paramp == start)
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected node name", str, paramp)
                            }
                            xml = com.omnifret.gplayer.xml.XmlNode()
                            xml!!.nodeType = com.omnifret.gplayer.xml.XmlNodeType.Element
                            xml!!.localName = str.substr(start, paramp - start)
                            parent.addChild(xml!!)
                            state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                            next = com.omnifret.gplayer.xml.XmlState.Body
                            continue
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Body -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeSlash -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.WaitEnd
                            }
                            com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.Childs
                            }
                            else -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.AttribName
                                start = paramp
                                continue
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.AttribName -> 
                    {
                        if (!com.omnifret.gplayer.xml.XmlParser._isValidChar(c))
                        {
                            if (start == paramp)
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected attribute name", str, paramp)
                            }
                            var tmp: String = str.substr(start, paramp - start)
                            aname = tmp
                            if (xml!!.attributes.has(aname!!))
                            {
                                throw com.omnifret.gplayer.xml.XmlError("""Duplicate attribute [${(aname!!).toTemplate()}]""", str, paramp)
                            }
                            state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                            next = com.omnifret.gplayer.xml.XmlState.Equals
                            continue
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Equals -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeEquals -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                                next = com.omnifret.gplayer.xml.XmlState.AttvalBegin
                            }
                            else -> 
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected =", str, paramp)
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.AttvalBegin -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeDoubleQuote, com.omnifret.gplayer.xml.XmlParser.CharCodeSingleQuote -> 
                            {
                                buf.setLength(0)
                                state = com.omnifret.gplayer.xml.XmlState.AttribVal
                                start = paramp + 1.0
                                attrValQuote = c
                            }
                            else -> { }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.AttribVal -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeAmp -> 
                            {
                                buf.append(str.substr(start, paramp - start))
                                state = com.omnifret.gplayer.xml.XmlState.Escape
                                escapeNext = com.omnifret.gplayer.xml.XmlState.AttribVal
                                start = paramp + 1.0
                            }
                            else -> 
                            {
                                if (c == attrValQuote)
                                {
                                    buf.append(str.substr(start, paramp - start))
                                    var value: String = buf.toString()
                                    buf.setLength(0)
                                    xml!!.attributes.set(aname!!, value)
                                    state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                                    next = com.omnifret.gplayer.xml.XmlState.Body
                                }
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Childs -> 
                    {
                        paramp = com.omnifret.gplayer.xml.XmlParser.parse(str, paramp, xml!!)
                        start = paramp
                        state = com.omnifret.gplayer.xml.XmlState.Begin
                    }
                    com.omnifret.gplayer.xml.XmlState.WaitEnd -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan -> 
                            {
                                state = com.omnifret.gplayer.xml.XmlState.Begin
                            }
                            else -> 
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected >", str, paramp)
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.WaitEndRet -> 
                    {
                        when (c)
                        {
                            com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan -> 
                            {
                                return paramp
                            }
                            else -> 
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected >", str, paramp)
                            }
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Close -> 
                    {
                        if (!com.omnifret.gplayer.xml.XmlParser._isValidChar(c))
                        {
                            if (start == paramp)
                            {
                                throw com.omnifret.gplayer.xml.XmlError("Expected node name", str, paramp)
                            }
                            var v: String = str.substr(start, paramp - start)
                            if (v != parent.localName)
                            {
                                throw com.omnifret.gplayer.xml.XmlError("""Expected </${(parent.localName).toTemplate()}>""", str, paramp)
                            }
                            state = com.omnifret.gplayer.xml.XmlState.IgnoreSpaces
                            next = com.omnifret.gplayer.xml.XmlState.WaitEndRet
                            continue
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Comment -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeMinus && str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeMinus && str.charCodeAt(paramp + 2.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan)
                        {
                            paramp += 2.0
                            state = com.omnifret.gplayer.xml.XmlState.Begin
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Doctype -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeBrackedOpen)
                        {
                            nbrackets++
                        }
                        else if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeBrackedClose)
                        {
                            nbrackets--
                        }
                        else if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan && nbrackets == 0.0)
                        {
                            var node: com.omnifret.gplayer.xml.XmlNode = com.omnifret.gplayer.xml.XmlNode()
                            node.nodeType = com.omnifret.gplayer.xml.XmlNodeType.DocumentType
                            node.value = str.substr(start, paramp - start)
                            parent.addChild(node)
                            state = com.omnifret.gplayer.xml.XmlState.Begin
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Header -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeQuestion && str.charCodeAt(paramp + 1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeGreaterThan)
                        {
                            paramp++
                            state = com.omnifret.gplayer.xml.XmlState.Begin
                        }
                    }
                    com.omnifret.gplayer.xml.XmlState.Escape -> 
                    {
                        if (c == com.omnifret.gplayer.xml.XmlParser.CharCodeSemi)
                        {
                            var s: String = str.substr(start, paramp - start)
                            if (s.charCodeAt(0.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeSharp)
                            {
                                var code: Double = if(s.charCodeAt(1.0) == com.omnifret.gplayer.xml.XmlParser.CharCodeLowerX)  com.omnifret.gplayer.core.ecmaScript.Number.parseInt("""0${(s.substr(1.0, s.length.toDouble() - (1.0).toDouble())).toTemplate()}""", 10.0) else com.omnifret.gplayer.core.ecmaScript.Number.parseInt(s.substr(1.0, s.length.toDouble() - (1.0).toDouble()), 10.0)
                                buf.append(com.omnifret.gplayer.core.ecmaScript.CoreString.fromCharCode(code))
                            }
                            else if (com.omnifret.gplayer.xml.XmlParser._escapes.has(s))
                            {
                                buf.append(com.omnifret.gplayer.xml.XmlParser._escapes.get(s))
                            }
                            else 
                            {
                                buf.append("""&${(s).toTemplate()};"""?.toString())
                            }
                            start = paramp + 1.0
                            state = escapeNext
                        }
                        else if (!com.omnifret.gplayer.xml.XmlParser._isValidChar(c) && c != com.omnifret.gplayer.xml.XmlParser.CharCodeSharp)
                        {
                            buf.append("&")
                            buf.append(str.substr(start, paramp - start))
                            paramp--
                            start = paramp + 1.0
                            state = escapeNext
                        }
                    }
                    else -> { }
                }
                paramp++
            }
            if (state == com.omnifret.gplayer.xml.XmlState.Begin)
            {
                start = paramp
                state = com.omnifret.gplayer.xml.XmlState.Pcdata
            }
            if (state == com.omnifret.gplayer.xml.XmlState.Pcdata)
            {
                if (paramp != start)
                {
                    buf.append(str.substr(start, paramp - start))
                    var node: com.omnifret.gplayer.xml.XmlNode = com.omnifret.gplayer.xml.XmlNode()
                    node.nodeType = com.omnifret.gplayer.xml.XmlNodeType.Text
                    node.value = buf.toString()
                    parent.addChild(node)
                }
                return paramp
            }
            if (state == com.omnifret.gplayer.xml.XmlState.Escape && escapeNext == com.omnifret.gplayer.xml.XmlState.Pcdata)
            {
                buf.append("&")
                buf.append(str.substr(start, paramp - start))
                var node: com.omnifret.gplayer.xml.XmlNode = com.omnifret.gplayer.xml.XmlNode()
                node.nodeType = com.omnifret.gplayer.xml.XmlNodeType.Text
                node.value = buf.toString()
                parent.addChild(node)
                return paramp
            }
            throw com.omnifret.gplayer.xml.XmlError("Unexpected end", str, paramp)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _isValidChar(c: Double): Boolean{
            return ((c >= com.omnifret.gplayer.xml.XmlParser.CharCodeLowerA && c <= com.omnifret.gplayer.xml.XmlParser.CharCodeLowerZ) || (c >= com.omnifret.gplayer.xml.XmlParser.CharCodeUpperA && c <= com.omnifret.gplayer.xml.XmlParser.CharCodeUpperZ) || (c >= com.omnifret.gplayer.xml.XmlParser.CharCode0 && c <= com.omnifret.gplayer.xml.XmlParser.CharCode9) || c == com.omnifret.gplayer.xml.XmlParser.CharCodeColon || c == com.omnifret.gplayer.xml.XmlParser.CharCodeDot || c == com.omnifret.gplayer.xml.XmlParser.CharCodeUnderscore || c == com.omnifret.gplayer.xml.XmlParser.CharCodeMinus)
        }
        
    }
    public constructor()
}

internal enum class XmlState(override val value: Int): com.omnifret.gplayer.core.IGPlayerEnum
{
    IgnoreSpaces(0),
    Begin(1),
    BeginNode(2),
    TagName(3),
    Body(4),
    AttribName(5),
    Equals(6),
    AttvalBegin(7),
    AttribVal(8),
    Childs(9),
    Close(10),
    WaitEnd(11),
    WaitEndRet(12),
    Pcdata(13),
    Header(14),
    Comment(15),
    Doctype(16),
    Cdata(17),
    Escape(18);
    companion object : com.omnifret.gplayer.core.IGPlayerEnumCompanion<XmlState>{
        public override val values = arrayOf(IgnoreSpaces, Begin, BeginNode, TagName, Body, AttribName, Equals, AttvalBegin, AttribVal, Childs, Close, WaitEnd, WaitEndRet, Pcdata, Header, Comment, Doctype, Cdata, Escape) 
        public override fun fromValue(v:Double): XmlState{
            return when(v.toInt()){
                IgnoreSpaces.value -> IgnoreSpaces
                Begin.value -> Begin
                BeginNode.value -> BeginNode
                TagName.value -> TagName
                Body.value -> Body
                AttribName.value -> AttribName
                Equals.value -> Equals
                AttvalBegin.value -> AttvalBegin
                AttribVal.value -> AttribVal
                Childs.value -> Childs
                Close.value -> Close
                WaitEnd.value -> WaitEnd
                WaitEndRet.value -> WaitEndRet
                Pcdata.value -> Pcdata
                Header.value -> Header
                Comment.value -> Comment
                Doctype.value -> Doctype
                Cdata.value -> Cdata
                Escape.value -> Escape
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}
