// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.io
import com.omnifret.gplayer.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class IOHelper
{
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt32BE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            var ch3: Double = input.readByte()
            var ch4: Double = input.readByte()
            return (((ch1).toInt() shl 24) or ((ch2).toInt() shl 16) or ((ch3).toInt() shl 8) or (ch4).toInt()).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readFloat32BE(readable: com.omnifret.gplayer.io.IReadable): Double{
            var bits: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(4.0)
            readable.read(((bits as com.omnifret.gplayer.core.ecmaScript.Uint8Array)), 0.0, bits.length)
            bits.reverse()
            return com.omnifret.gplayer.io.TypeConversions.bytesToFloat32LE(((bits as com.omnifret.gplayer.core.ecmaScript.Uint8Array)))
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readFloat64BE(readable: com.omnifret.gplayer.io.IReadable): Double{
            var bits: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(8.0)
            readable.read(((bits as com.omnifret.gplayer.core.ecmaScript.Uint8Array)), 0.0, bits.length)
            bits.reverse()
            return com.omnifret.gplayer.io.TypeConversions.bytesToFloat64LE(((bits as com.omnifret.gplayer.core.ecmaScript.Uint8Array)))
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt32LE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            var ch3: Double = input.readByte()
            var ch4: Double = input.readByte()
            return (((ch4).toInt() shl 24) or ((ch3).toInt() shl 16) or ((ch2).toInt() shl 8) or (ch1).toInt()).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt64LE(input: com.omnifret.gplayer.io.IReadable): Double{
            var b: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(8.0)
            input.read(((b as com.omnifret.gplayer.core.ecmaScript.Uint8Array)), 0.0, b.length)
            return com.omnifret.gplayer.io.TypeConversions.bytesToInt64LE(((b as com.omnifret.gplayer.core.ecmaScript.Uint8Array)))
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readUInt32LE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            var ch3: Double = input.readByte()
            var ch4: Double = input.readByte()
            return (((ch4).toInt() shl 24) or ((ch3).toInt() shl 16) or ((ch2).toInt() shl 8) or (ch1).toInt()).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun decodeUInt32LE(`data`: com.omnifret.gplayer.core.ecmaScript.Uint8Array, index: Double): Double{
            var ch1: Double = `data`[(index).toInt()]
            var ch2: Double = `data`[(index + 1.0).toInt()]
            var ch3: Double = `data`[(index + 2.0).toInt()]
            var ch4: Double = `data`[(index + 3.0).toInt()]
            return (((ch4).toInt() shl 24) or ((ch3).toInt() shl 16) or ((ch2).toInt() shl 8) or (ch1).toInt()).toDouble()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readUInt16LE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            return com.omnifret.gplayer.io.TypeConversions.int32ToUint16((((ch2).toInt() shl 8) or (ch1).toInt()).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt16LE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            return com.omnifret.gplayer.io.TypeConversions.int32ToInt16((((ch2).toInt() shl 8) or (ch1).toInt()).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readUInt32BE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            var ch3: Double = input.readByte()
            var ch4: Double = input.readByte()
            return com.omnifret.gplayer.io.TypeConversions.int32ToUint32((((ch1).toInt() shl 24) or ((ch2).toInt() shl 16) or ((ch3).toInt() shl 8) or (ch4).toInt()).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readUInt16BE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            return com.omnifret.gplayer.io.TypeConversions.int32ToInt16((((ch1).toInt() shl 8) or (ch2).toInt()).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt16BE(input: com.omnifret.gplayer.io.IReadable): Double{
            var ch1: Double = input.readByte()
            var ch2: Double = input.readByte()
            return com.omnifret.gplayer.io.TypeConversions.int32ToInt16((((ch1).toInt() shl 8) or (ch2).toInt()).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readByteArray(input: com.omnifret.gplayer.io.IReadable, length: Double): com.omnifret.gplayer.core.ecmaScript.Uint8Array{
            var v: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(length)
            input.read(v, 0.0, length)
            return v
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun read8BitChars(input: com.omnifret.gplayer.io.IReadable, length: Double): String{
            var b: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.core.ecmaScript.Uint8Array(length)
            input.read(b, 0.0, b.length)
            return com.omnifret.gplayer.io.IOHelper.toString(b, "utf-8")
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun read8BitString(input: com.omnifret.gplayer.io.IReadable): String{
            var s: StringBuilder = StringBuilder()
            var c: Double = input.readByte()
            while (c != 0.0)
            {
                s.append(com.omnifret.gplayer.core.ecmaScript.CoreString.fromCharCode(c))
                c = input.readByte()
            }
            return s.toString()
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun read8BitStringLength(input: com.omnifret.gplayer.io.IReadable, length: Double): String{
            var s: StringBuilder = StringBuilder()
            var z: Double = -1.0
            if (true) {
                var i: Double = 0.0
                
                while(i < length){
                    var c: Double = input.readByte()
                    if (c == 0.0 && z == -1.0)
                    {
                        z = i
                    }
                    s.append(com.omnifret.gplayer.core.ecmaScript.CoreString.fromCharCode(c))
                    i++
                }
            }
            var t: String = s.toString()
            if (z >= 0)
            {
                return t.substr(0.0, z)
            }
            return t
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readSInt8(input: com.omnifret.gplayer.io.IReadable): Double{
            var v: Double = input.readByte()
            return (((v).toInt() and 255) shr 7) * -256.0 + ((v).toInt() and 255)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt24(input: com.omnifret.gplayer.core.ecmaScript.Uint8Array, index: Double): Double{
            var i: Double = ((input[(index).toInt()]).toInt() or ((input[(index + 1.0).toInt()]).toInt() shl 8) or ((input[(index + 2.0).toInt()]).toInt() shl 16)).toDouble()
            if (((i).toInt() and 8388608) == 8388608)
            {
                i = ((i).toInt() or (255 shl 24)).toDouble()
            }
            return i
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun readInt16(input: com.omnifret.gplayer.core.ecmaScript.Uint8Array, index: Double): Double{
            return com.omnifret.gplayer.io.TypeConversions.int32ToInt16(((input[(index).toInt()]).toInt() or ((input[(index + 1.0).toInt()]).toInt() shl 8)).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun toString(`data`: com.omnifret.gplayer.core.ecmaScript.Uint8Array, encoding: String): String{
            var paramencoding = encoding
            var detectedEncoding: String? = com.omnifret.gplayer.io.IOHelper._detectEncoding(`data`)
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(detectedEncoding)))
            {
                paramencoding = detectedEncoding!!
            }
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(paramencoding)))
            {
                paramencoding = "utf-8"
            }
            var decoder: com.omnifret.gplayer.core.ecmaScript.TextDecoder = com.omnifret.gplayer.core.ecmaScript.TextDecoder(paramencoding)
            return decoder.decode((`data`.buffer as com.omnifret.gplayer.core.ecmaScript.ArrayBuffer))
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _detectEncoding(`data`: com.omnifret.gplayer.core.ecmaScript.Uint8Array): String?{
            if (`data`.length > 2 && `data`[(0.0).toInt()] == 254.0 && `data`[(1.0).toInt()] == 255.0)
            {
                return "utf-16be"
            }
            if (`data`.length > 2 && `data`[(0.0).toInt()] == 255.0 && `data`[(1.0).toInt()] == 254.0)
            {
                return "utf-16le"
            }
            if (`data`.length > 4 && `data`[(0.0).toInt()] == 0.0 && `data`[(1.0).toInt()] == 0.0 && `data`[(2.0).toInt()] == 254.0 && `data`[(3.0).toInt()] == 255.0)
            {
                return "utf-32be"
            }
            if (`data`.length > 4 && `data`[(0.0).toInt()] == 255.0 && `data`[(1.0).toInt()] == 254.0 && `data`[(2.0).toInt()] == 0.0 && `data`[(3.0).toInt()] == 0.0)
            {
                return "utf-32le"
            }
            return null
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun stringToBytes(str: String): com.omnifret.gplayer.core.ecmaScript.Uint8Array{
            var decoder: com.omnifret.gplayer.core.ecmaScript.TextEncoder = com.omnifret.gplayer.core.ecmaScript.TextEncoder()
            return decoder.encode(str)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeInt32BE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            o.writeByte((((v).toInt() shr 24) and 255).toDouble())
            o.writeByte((((v).toInt() shr 16) and 255).toDouble())
            o.writeByte((((v).toInt() shr 8) and 255).toDouble())
            o.writeByte((((v).toInt() shr 0) and 255).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeInt32LE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            o.writeByte((((v).toInt() shr 0) and 255).toDouble())
            o.writeByte((((v).toInt() shr 8) and 255).toDouble())
            o.writeByte((((v).toInt() shr 16) and 255).toDouble())
            o.writeByte((((v).toInt() shr 24) and 255).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeUInt16LE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            o.writeByte((((v).toInt() shr 0) and 255).toDouble())
            o.writeByte((((v).toInt() shr 8) and 255).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeInt16LE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            o.writeByte((((v).toInt() shr 0) and 255).toDouble())
            o.writeByte((((v).toInt() shr 8) and 255).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeInt16BE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            o.writeByte((((v).toInt() shr 8) and 255).toDouble())
            o.writeByte((((v).toInt() shr 0) and 255).toDouble())
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun writeFloat32BE(o: com.omnifret.gplayer.io.IWriteable, v: Double): Unit{
            var b: com.omnifret.gplayer.core.ecmaScript.Uint8Array = com.omnifret.gplayer.io.TypeConversions.float32BEToBytes(v)
            o.write(b, 0.0, b.length)
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun iterateCodepoints(input: String): kotlin.collections.Iterator<Double> = iterator{
            var i: Double = 0.0
            while (i < input.length.toDouble())
            {
                var c: Double = input.charCodeAt(i)
                if (com.omnifret.gplayer.io.IOHelper.isLeadingSurrogate(c) && i + 1.0 < input.length.toDouble())
                {
                    i++
                    c = (c - (55296.0).toDouble()) * (1024.0).toDouble() + (input.charCodeAt(i) - (56320.0).toDouble()) + 65536.0
                }
                i++
                yield(c)
            }
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun isLeadingSurrogate(charCode: Double): Boolean{
            return charCode >= 55296 && charCode <= 56319
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun isTrailingSurrogate(charCode: Double): Boolean{
            return charCode >= 56320 && charCode <= 57343
        }
        
    }
    public constructor()
}
