// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer
import com.omnifret.gplayer.core.*

/**
 * This public class contains central definitions for controlling the visual appearance.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class RenderingResources
{
    /**
     * The name of the SMuFL Font to use for rendering music symbols.
     */
    internal var smuflFontFamilyName: String? = null
    
    /**
     * The SMuFL Metrics to use for rendering music symbols.
     */
    public var engravingSettings: com.omnifret.gplayer.EngravingSettings = com.omnifret.gplayer.EngravingSettings.bravuraDefaults
    
    
    public var copyrightFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.ScoreCopyright)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.ScoreCopyright, value)
    }
    
    public var titleFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.ScoreTitle)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.ScoreTitle, value)
    }
    
    public var subTitleFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.ScoreSubTitle)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.ScoreSubTitle, value)
    }
    
    public var wordsFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.ScoreWords)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.ScoreWords, value)
    }
    
    public var timerFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.EffectBeatTimer)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.EffectBeatTimer, value)
    }
    
    public var directionsFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.EffectDirections)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.EffectDirections, value)
    }
    
    public var fretboardNumberFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.ChordDiagramFretboardNumbers)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.ChordDiagramFretboardNumbers, value)
    }
    
    /**
     * Unused, see deprecation note.
     */
    @kotlin.Deprecated("Since 1.7.0 the library uses the glyphs contained in the SMuFL font")
    public var fingeringFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.RenderingResources._effectFont
    
    
    /**
     * Unused, see deprecation note.
     */
    @kotlin.Deprecated("Since 1.7.0 the library uses the glyphs contained in the SMuFL font")
    public var inlineFingeringFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.RenderingResources._effectFont
    
    
    public var markerFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.EffectMarker)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.EffectMarker, value)
    }
    
    /**
     * Ununsed, see deprecation note.
     */
    @kotlin.Deprecated("use elementFonts with the respective")
    public var effectFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.RenderingResources._effectFont
    
    
    public var barNumberFont: com.omnifret.gplayer.model.Font
    get(){
        return this.elementFonts.get(com.omnifret.gplayer.NotationElement.BarNumber)!!
    }
    set(value){
        this.elementFonts.set(com.omnifret.gplayer.NotationElement.BarNumber, value)
    }
    
    /**
     * The fonts used by individual elements. Check `defaultFonts` for the elements which have custom fonts.
     * Removing fonts from this map can lead to unexpected side effects and errors. Only update it with new values.
     */
    public var elementFonts: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>()
    
    
    /**
     * The font to use for displaying the numbered music notation in the music sheet.
     */
    public var numberedNotationFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 16.0, com.omnifret.gplayer.model.FontStyle.Plain)
    
    
    /**
     * The font to use for displaying the grace notes in numbered music notation in the music sheet.
     */
    public var numberedNotationGraceFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 14.0, com.omnifret.gplayer.model.FontStyle.Plain)
    
    
    /**
     * The font to use for displaying the guitar tablature numbers in the music sheet.
     */
    public var tablatureFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 14.0, com.omnifret.gplayer.model.FontStyle.Plain)
    
    
    /**
     * The font to use for grace notation related texts in the music sheet.
     */
    public var graceFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 12.0, com.omnifret.gplayer.model.FontStyle.Plain)
    
    
    /**
     * The color to use for rendering the lines of staves.
     */
    public var staffLineColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(165.0, 165.0, 165.0, 255.0)
    
    
    /**
     * The color to use for rendering bar separators, the accolade and repeat signs.
     */
    public var barSeparatorColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(34.0, 34.0, 17.0, 255.0)
    
    
    /**
     * The color to use for displaying the bar numbers above the music sheet.
     */
    public var barNumberColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(200.0, 0.0, 0.0, 255.0)
    
    
    /**
     * The color to use for music notation elements of the primary voice.
     */
    public var mainGlyphColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(0.0, 0.0, 0.0, 255.0)
    
    
    /**
     * The color to use for music notation elements of the secondary voices.
     */
    public var secondaryGlyphColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(0.0, 0.0, 0.0, 100.0)
    
    
    /**
     * The color to use for displaying the song information above the music sheets.
     */
    public var scoreInfoColor: com.omnifret.gplayer.model.Color = com.omnifret.gplayer.model.Color(0.0, 0.0, 0.0, 255.0)
    
    
    public constructor(){
        for ((k, v) in com.omnifret.gplayer.RenderingResources.defaultFonts)
        {
            this.elementFonts.set(k, v.withSize(v.size))
        }
    }
    
    /**
     */
    internal fun getFontForElement(element: com.omnifret.gplayer.model.ScoreSubElement): com.omnifret.gplayer.model.Font{
        var notationElement: com.omnifret.gplayer.NotationElement = com.omnifret.gplayer.NotationElement.ScoreWords
        when (element)
        {
            com.omnifret.gplayer.model.ScoreSubElement.Title -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreTitle
            }
            com.omnifret.gplayer.model.ScoreSubElement.SubTitle -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreSubTitle
            }
            com.omnifret.gplayer.model.ScoreSubElement.Artist -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreArtist
            }
            com.omnifret.gplayer.model.ScoreSubElement.Album -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreAlbum
            }
            com.omnifret.gplayer.model.ScoreSubElement.Words -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreWords
            }
            com.omnifret.gplayer.model.ScoreSubElement.Music -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreMusic
            }
            com.omnifret.gplayer.model.ScoreSubElement.WordsAndMusic -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreWordsAndMusic
            }
            com.omnifret.gplayer.model.ScoreSubElement.Copyright, com.omnifret.gplayer.model.ScoreSubElement.CopyrightSecondLine -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreCopyright
            }
            else -> 
            {
                notationElement = com.omnifret.gplayer.NotationElement.ScoreWords
            }
        }
        return if(this.elementFonts.has(notationElement))  this.elementFonts.get(notationElement)!! else com.omnifret.gplayer.RenderingResources.defaultFonts.get(com.omnifret.gplayer.NotationElement.ScoreWords)!!
    }
    
    companion object{
        @kotlin.jvm.JvmStatic
        private var _sansFont: String = "Arial, sans-serif"
        
        @kotlin.jvm.JvmStatic
        private var _serifFont: String = "Georgia, serif"
        
        @kotlin.jvm.JvmStatic
        private var _effectFont: com.omnifret.gplayer.model.Font = com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 12.0, com.omnifret.gplayer.model.FontStyle.Italic)
        
        /**
         * The default fonts for notation elements if not specified by the user.
         */
        @kotlin.jvm.JvmStatic
        public var defaultFonts: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.collections.SimpleIterable<com.omnifret.gplayer.core.IArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>>(
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreTitle, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 32.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreSubTitle, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 20.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreArtist, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 20.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreAlbum, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 20.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreWords, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 15.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreMusic, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 15.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreWordsAndMusic, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 15.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreCopyright, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 12.0, com.omnifret.gplayer.model.FontStyle.Plain, com.omnifret.gplayer.model.FontWeight.Bold)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectBeatTimer, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 12.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectDirections, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 14.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ChordDiagramFretboardNumbers, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 11.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectFingering, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 14.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectMarker, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 14.0, com.omnifret.gplayer.model.FontStyle.Plain, com.omnifret.gplayer.model.FontWeight.Bold)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectCapo, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectFreeTime, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectLyrics, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectTap, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ChordDiagrams, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectChordNames, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectText, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectPalmMute, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectLetRing, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectBeatBarre, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectTripletFeel, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectHarmonics, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectPickSlide, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.GuitarTuning, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectRasgueado, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectWhammyBar, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.TrackNames, com.omnifret.gplayer.RenderingResources._effectFont), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.RepeatCount, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 11.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.BarNumber, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 11.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.ScoreBendSlur, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._sansFont, 11.0, com.omnifret.gplayer.model.FontStyle.Plain)), 
            
            com.omnifret.gplayer.core.ArrayTuple<com.omnifret.gplayer.NotationElement, com.omnifret.gplayer.model.Font>(com.omnifret.gplayer.NotationElement.EffectAlternateEndings, com.omnifret.gplayer.model.Font(com.omnifret.gplayer.RenderingResources._serifFont, 15.0, com.omnifret.gplayer.model.FontStyle.Plain)))
        )
        
        
    }
}

