// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.layout
import com.omnifret.gplayer.core.*

/**
 * This registry keeps track of which slurs and ties were started and needs completion.
 * Slurs might span multiple systems, and in such cases we need to create additional
 * slur/ties in the intermediate and end system.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class SlurRegistry
{
    private var _staffLookup: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.layout.SlurInfoContainer> = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.layout.SlurInfoContainer>()
    
    public fun clear(): Unit{
        this._staffLookup.clear()
    }
    
    /**
     */
    public fun startMultiSystemSlur(startGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph): Unit{
        var staffId: String = com.omnifret.gplayer.rendering.layout.SlurRegistry._staffId(startGlyph.renderer.staff!!)
        var container: com.omnifret.gplayer.rendering.layout.SlurInfoContainer
        if (!this._staffLookup.has(staffId))
        {
            container = com.omnifret.gplayer.rendering.layout.SlurInfoContainer(startedSlurs = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.layout.SlurRegistration>())
            this._staffLookup.set(staffId, container)
        }
        else 
        {
            container = this._staffLookup.get(staffId)!!
        }
        container.startedSlurs.set(startGlyph.slurEffectId, com.omnifret.gplayer.rendering.layout.SlurRegistration(startGlyph = startGlyph))
    }
    
    /**
     */
    public fun completeMultiSystemSlur(endGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph): com.omnifret.gplayer.rendering.glyphs.TieGlyph?{
        var staffId: String = com.omnifret.gplayer.rendering.layout.SlurRegistry._staffId(endGlyph.renderer.staff!!)
        if (!this._staffLookup.has(staffId))
        {
            return null
        }
        var container: com.omnifret.gplayer.rendering.layout.SlurInfoContainer = this._staffLookup.get(staffId)!!
        if (container.startedSlurs.has(endGlyph.slurEffectId))
        {
            var info: com.omnifret.gplayer.rendering.layout.SlurRegistration = container.startedSlurs.get(endGlyph.slurEffectId)!!
            info.endGlyph = endGlyph
            return info.startGlyph
        }
        return null
    }
    
    /**
     */
    public fun getAllContinuations(renderer: com.omnifret.gplayer.rendering.BarRendererBase): kotlin.collections.Iterator<com.omnifret.gplayer.rendering.glyphs.TieGlyph> = iterator{
        var staffId: String = com.omnifret.gplayer.rendering.layout.SlurRegistry._staffId(renderer.staff!!)
        if (!this@SlurRegistry._staffLookup.has(staffId) || renderer.index > 0)
        {
            return@iterator
        }
        var container: com.omnifret.gplayer.rendering.layout.SlurInfoContainer = this@SlurRegistry._staffLookup.get(staffId)!!
        for (g in container.startedSlurs.values())
        {
            if (g.startGlyph.shouldCreateMultiSystemSlur(renderer))
            {
                yield(g.startGlyph)
            }
        }
    }
    
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _staffId(staff: com.omnifret.gplayer.rendering.staves.RenderStaff): String{
            return """${(staff.modelStaff.index).toTemplate()}.${(staff.modelStaff.track.index).toTemplate()}.${(staff.staffId).toTemplate()}"""
        }
        
    }
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class SlurRegistration: com.omnifret.gplayer.core.IRecord
{
    public var startGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph
    
    public var endGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph? = null
    
    public constructor(startGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph, endGlyph: com.omnifret.gplayer.rendering.glyphs.TieGlyph? = null){
        this.startGlyph = startGlyph
        this.endGlyph = endGlyph
    }
    
}

/**
 * Holds the slur information specific for an individual staff
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class SlurInfoContainer: com.omnifret.gplayer.core.IRecord
{
    /**
     * A set of started slurs and ties.
     */
    public var startedSlurs: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.layout.SlurRegistration>
    
    public constructor(startedSlurs: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.rendering.layout.SlurRegistration>){
        this.startedSlurs = startedSlurs
    }
    
}

