// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "UNNECESSARY_LATEINIT",
    "CAST_NEVER_SUCCEEDS",
    "SENSELESS_COMPARISON",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.importer
import com.omnifret.gplayer.core.*

/**
 * This ScoreImporter can read Guitar Pro 6 (gpx) files.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class GpxImporter: com.omnifret.gplayer.importer.ScoreImporter
{
    public override val name: String
    get(){
        return "Guitar Pro 6"
    }
    
    /**
     * Reads the  contained in the data.
     */
    public override fun readScore(): com.omnifret.gplayer.model.Score{
        com.omnifret.gplayer.Logger.debug(this.name, "Loading GPX filesystem")
        var fileSystem: com.omnifret.gplayer.importer.GpxFileSystem = com.omnifret.gplayer.importer.GpxFileSystem()
        fileSystem.fileFilter = fun(s: String): Boolean{
            return (s.endsWith("score.gpif") || s.endsWith("BinaryStylesheet") || s.endsWith("PartConfiguration") || s.endsWith("LayoutConfiguration"))
        }
        
        fileSystem.load(this.`data`)
        com.omnifret.gplayer.Logger.debug(this.name, "GPX filesystem loaded")
        var xml: String? = null
        var binaryStylesheetData: com.omnifret.gplayer.core.ecmaScript.Uint8Array? = null
        var partConfigurationData: com.omnifret.gplayer.core.ecmaScript.Uint8Array? = null
        var layoutConfigurationData: com.omnifret.gplayer.core.ecmaScript.Uint8Array? = null
        for (entry in fileSystem.files)
        {
            when (entry.fileName)
            {
                "score.gpif" -> 
                {
                    xml = com.omnifret.gplayer.io.IOHelper.toString(entry.`data`!!, this.settings.importer.encoding)
                }
                "BinaryStylesheet" -> 
                {
                    binaryStylesheetData = entry.`data`
                }
                "PartConfiguration" -> 
                {
                    partConfigurationData = entry.`data`
                }
                "LayoutConfiguration" -> 
                {
                    layoutConfigurationData = entry.`data`
                }
                else -> { }
            }
        }
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(xml)))
        {
            throw com.omnifret.gplayer.importer.UnsupportedFormatError("No score.gpif found in GPX")
        }
        com.omnifret.gplayer.Logger.debug(this.name, "Start Parsing score.gpif")
        var gpifParser: com.omnifret.gplayer.importer.GpifParser = com.omnifret.gplayer.importer.GpifParser()
        gpifParser.parseXml(xml!!, this.settings)
        com.omnifret.gplayer.Logger.debug(this.name, "score.gpif parsed")
        var score: com.omnifret.gplayer.model.Score = gpifParser.score
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(binaryStylesheetData)))
        {
            com.omnifret.gplayer.Logger.debug(this.name, "Start Parsing BinaryStylesheet")
            var binaryStylesheet: com.omnifret.gplayer.importer.BinaryStylesheet = com.omnifret.gplayer.importer.BinaryStylesheet(binaryStylesheetData!!)
            binaryStylesheet.apply(score)
            com.omnifret.gplayer.Logger.debug(this.name, "BinaryStylesheet parsed")
        }
        var partConfigurationParser: com.omnifret.gplayer.importer.PartConfiguration? = null
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(partConfigurationData)))
        {
            com.omnifret.gplayer.Logger.debug(this.name, "Start Parsing Part Configuration")
            partConfigurationParser = com.omnifret.gplayer.importer.PartConfiguration(partConfigurationData!!)
            partConfigurationParser!!.apply(score)
            com.omnifret.gplayer.Logger.debug(this.name, "Part Configuration parsed")
        }
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(layoutConfigurationData)) && partConfigurationParser != null))
        {
            com.omnifret.gplayer.Logger.debug(this.name, "Start Parsing Layout Configuration")
            var layoutConfigurationParser: com.omnifret.gplayer.importer.LayoutConfiguration = com.omnifret.gplayer.importer.LayoutConfiguration(partConfigurationParser!!, layoutConfigurationData!!)
            layoutConfigurationParser.apply(score)
            com.omnifret.gplayer.Logger.debug(this.name, "Layout Configuration parsed")
        }
        return score
    }
    
    public constructor()
    : super()
}

